﻿# 新手教程 v2 · 实现方案（正本）

> **本文是新手教程 v2 的方案正本**（2026-09-19 由 S1 落进仓库，同日 S12 收口改成 as-built）。
> 老方案已归档为 `docs/archive/新手引导_实现方案_v1_2026-09-19.md`，只作历史查阅。
>
> ## ✅ 收口状态（2026-09-19 · S12）
>
> **S1～S13 全部落地**：第一～三章六关 + 间章「癌变」整条打通。
> 逐关端到端由无头套件顶着（`t_tutor_c1` / `_c2` / `_interlude` / `_c3`，真盘面真规则真带子跑完）；
> 真机**逐关从主菜单真进**各留一帧（十三帧，S12），第一关是从主菜单点进去一路打到静默切第二关的连打。
> 主菜单「新手引导」入口**已恢复**（`main_menu.gd` 的 `ITEMS`，唯一一处开关，`t_entry_smoke_tutorial` 正面钉住）。
>
> 下文的时态请这样读：**§1～§6 是 as-built**（写的就是仓库里今天真跑着的东西，落地时改过的字都带「实测改判 S*」）；
> **§7 是做完的拆片账**（保留是为了留下依赖与工期的实绩）；**§8 只剩没解掉的那几条**。
> 逐片的落地经过在 `docs/开发日志.md` 2026-09-19 那一串条目里，改判汇总见下面 §0‴。
>
> **三条已定案**（★ Kevin 2026-09-19 拍板，S12 收口当天；实现与现状**完全一致，一行没改**）：
> ① 间章分镜 4「分化后转普通免疫」= **纯演出** —— 引擎里玩家仍是他分化后的那一种，直到分镜 6 阵营翻转（§4 的 399 行）；
> ② 第六关第 18 步【细胞毒素】= **演出** —— T 不真放技能、**不给它行动回合**，25 步的节拍不动（§4.1 改判 ①）；
> ③ 第六关第 25 步「癌细胞死亡」= **演出** —— 能量保持 Null、**不真死**，PRD:455 与 PRD:527 的打架就这么收（§4.1 改判 ②）。
>
> **还挂着一条**：④ 第六关**镜头档等 Kevin 看图再选**（现状 1.27 倍 + 玩家调右，T 隔 11 格时卡在左边缘只露半只）。
> 两档示意图已出、**只出图不合入**，路径见 `docs/开发日志.md` 2026-09-19 · S12 那条。
>
> ## ⚠ 读之前先看这一条：Kevin 2026-09-19 的界面八问是**逐帧拍板**，不是「两版皮都否」
>
> 本稿正文（§0′ / §5.2 / §5.5 / §7 / §8.3）成文时把 Kevin 的「1-7 两个都不好，重做」读成了
> 「两版方向稿整体都被否、要第二轮」——**这是错的**，下面这一段**取代正文里所有
> 「等第二轮方向稿」「S3 阻塞」的说法**：
>
> | 拍板 | 内容 |
> |---|---|
> | **整体** | 走**方向 A「贴身气泡」**（`docs/archive/新手引导v2_方向A.md` + `game/tests/preview/preview_tut_v2_A.gd`） |
> | ① 章节提示 | 用 **B 的样子**：全屏黑底 + 居中大字 + 英文副标（`docs/archive/新手引导v2_方向B.md`） |
> | ③【迁移】提亮 | 按钮**保持原样单线**，只用慢闪提示 —— **不**在控件旁加气泡 |
> | ⑤ 目录 | **间章与三个主章节平级单列** |
> | ⑦ 自动重置提示 | **只有这一帧**两版都否、要重做（S7 的事，已出三候选待挑，见 §0″） |
> | ②④⑥⑧ | 照 **A** |
>
> 另两条口径：
> 1. **第一～三章右栏藏「第 X 回合」**，且只留状态框 + 抗原记忆框（其余第四章内容加闸）；**S5 修订（2026-09-19）已落地**：「癌性加权」那一整块在教程局整块藏掉（`CWMatchPanel.guide_layers` 第三个层位，`match.gd:_sync_tutor_layers` 写死 `false`；**只藏不挪** —— 让出来的 66px 不给下面的行，九席那套配平是按「藏着也占位」算的）；
> 2. **能量 ∞ 补字形**、补不出用 `INF`（S13 另有人做；流程侧只留一处显示串常量 `CWTutorLayers.ENERGY_INF_MARK`）。
>
> ⇒ **S3（皮实装）不阻塞**，按方向 A 做。但 **S1 仍按本稿用「计数皮 + 占位皮」验收** ——
> 那两件的意义是让「第一关端到端跑通」与「皮长什么样」解耦，皮 A 的实装归 S3。


> 综合者产出。读物：简报 `scratchpad/tut_v2_plan_brief.md`、剧本 `D:/Projects/SpringSense/2026-2027/Cell War/Cell_War_新手引导PRD_hxr.md`（09-18 版，508 行，整份读完）、三份方案（甲 765 行 / 乙 965 行 / 丙 828 行）、两份评分（`tut_v2_judge_1.md` / `tut_v2_judge_2.md`，任务里两个路径写重了，实际读的是 judge_1 与 judge_2）。
> **只读**：本轮没有改仓库、没有 git、没有跑 Godot。行号沿用三份稿与两位评委各自 grep 出来的值；**两处三家给的行号不一致，已在正文标红，开工第一件事按文件核一次**。
> 范围：第一～三章 + 间章 + 第七关。第四章（PRD:505-508）不做。开场动画（`tutorial_opening.gd` + `tutorial_opening.tscn` + `data/tutorial/cutscenes/opening.json`）**保留不动**。
> **本版（第二轮）比初稿多的东西**：把 **Kevin 2026-09-19 的三段追加回答**落进方案 —— 见 §0′（∞ 补字形 / 否则 `INF`；间章独立成段；迁移按钮单线原样 + 慢闪；方向稿两版都否、要第二轮）。受影响的是 §2.2 / §2.5 / §2.6 / §2.10 / §3.2 / §3.6 / §5.2 / §5.5 / §6.1 / §6.2 / §7 / §8.3，逐处都标了 ★。拆片见 `tut_v2_slices.json`（13 片，第一片是端到端原子片）。

---

## 0′. Kevin 2026-09-19 的追加回答（逐字照录）与落点

> 本轮派工时 Kevin 给了三段原话，逐字照录如下。**凡与本稿原有默认冲突的，一律以这三段为准。**
>
> ```
> 1.
> 1、B
> 2、A
> 3、A 迁移按钮改为单线原样，用闪烁来提示用户
> 4、A
> 5、A 但是间章不是主章节的附属章节
> 6、A
> 7、两个都不好，重做
> 8、A
>
> 2.要
> 3.补字形，如果没有相似字形，就用INF
> ```

| 原话 | 落到哪 | 本稿据此改了什么 |
|---|---|---|
| **「3. 补字形，如果没有相似字形，就用 INF」** | §2.3 / §3.2(b) / §6.2 / 拆片 **S13** | **Q-09 结案，不再退成「无限」**：先给缝合像素 10px 字库**补 U+221E 字形**；补不出相似字形就把显示串常量改成 **`INF`**（三个渲染点一条路，一处常量）。新增一片 S13 专做这件事，与主线并行 |
| **「1-5. A，但是间章不是主章节的附属章节」** | §2.2 / §2.5 / §3.6 / S9 | 间章**独立成一段**：自己一份 `levels/interlude.json`，`index.json` 里与三个主章节**平级单列**，不挂在第二章（也不挂第三章）下面。顶层键加一个 `chapter_kind`（`main` / `interlude`），15 键 → 16 键 |
| **「1-3. A，迁移按钮改为单线原样，用闪烁来提示用户」** | §5.5 | 提亮**不换按钮样式**：按钮保持**单线原样**，只用通用规则 8 的轻微慢闪来提示（`point.mode == "soft"` 的皮侧口径）。写进两版皮的验收判据 |
| **「1-7. 两个都不好，重做」** | §5.2 / §5.5 / §7 | ⚠ **本行成文时读错了**（见文首那一段）：Kevin 是**逐帧**拍的 —— 整体走方向 A，只有**第 7 帧「自动重置提示」**两版都否、要重做（归 S7）。S3 **不**阻塞。S1/S2 仍用**计数皮 + 占位皮**端到端验收，那是为了让主线与皮解耦，不是因为皮没定 |
| 「1-1 / 2 / 4 / 6 / 8」与「**2. 要**」 | §5.5 | ⚠ **已补**（见文首那一段）：②④⑥⑧ 照方向 A，①用 B 的章节提示，③按钮单线原样 + 慢闪，⑤间章平级单列。成文时的原话是：可以确定的是：它们全部落在**表现层（皮）与流程之外的安排**上，**不改 §1～§4 的任何一条**。派工的人请把原问题连同答案一并交给做 S3 的 agent |

---

## 0″. Kevin 2026-09-19 的**第二轮**回答（S1 落库时补记）

> 第一轮（§0′）答的是界面方向稿的八问与三条追加；这一轮答的是 §8.3 那张问答表里挡着的几条。
> **凡与正文默认冲突的，一律以本节为准。**

| # | 原问 | Kevin 二答 | 落点 |
|---|---|---|---|
| **Q-03** | 第七关第 8 步「重复 3-5」还是「3-7」？ | **「重复 3、4、7」** —— 不是连续区间，是**点名的那三条**（围一圈 / 结算压迫增生侵蚀 / 免疫回合），跳过 5、6 两条（图鉴解锁与按钮提示只做一次） | §2.9 / S10 / S11。轮数仍按我方默认 2~3（世界回合 ≤ 5，保住癌 I 期），带子照此录 |
| **Q-17** | 第二关 Step2 一击必杀 vs 文案「攻击癌细胞直到其死亡」 | **改文案**：PRD:203 写成**「击杀癌细胞」**（不抬能量、不加骰子） | S4 的 `c1_l2.json` 照这句写 |
| **Q-21** | 目录要不要「重看开场」？叫什么？ | **要**，按钮名就叫 **「Cell War」**（开场动画的片名，不写「重看开场」四个字） | §3.6 常驻目录 / S6 的目录面板 |
| **Q-13 + 第 7 帧** | 像素错误的美术口径；「自动重置提示」那一帧重做 | **两件都已出图待挑**：像素错误三模式（抖动 / 色块错位 / 扫描线）与重置提示三候选，**S7 已出预览图**，等 Kevin 点一个 | S7（演出库）→ S2/S4 接上 |
| 其余 | Q-01 / 02 / 04 / 06 / 07 / 10 / 11 / 12 / 14 / 15 / 16 / 18 / 19 / 20 与 Q-09b | **按本稿默认做** | 各片照 §8.3 那一列执行 |

---

## 0‴. 改判表汇总（S1～S13 一处看全 · S12 收口补）

> 每一片落地时都在 `docs/开发日志.md` 自己那条里写了一张「原 → 新 → 依据」的改判表。
> 这里只做**索引 + 一句话**，要看依据翻那一条 —— 复制一遍必然漂移，而漂移了的汇总表比没有更糟。
> 「口径改判」= 方案写的做法在真机 / 真引擎上不成立，换了一种；「测试改判」= 既有 `check()` 的判据改了。

| 片 | 口径改判（一句话） | 测试改判 | 在哪 |
|---|---|---|---|
| S1 | 老教程整套推倒：`cwtut/1` 与 `guide*.gd` 七个文件连同**老测试 18 支**一起删（纪律破例 Q-07） | 18 支整份删 + 4 支改判（见 §6.4） | 开发日志 S1 |
| S2 | —— | 一条没删没改，两支新测试全是新增断言 | 开发日志 S2 |
| S3 | 「两个都不好」是**误读**：只否了自动重置那一帧，整体走方向 A ⇒ 皮 A 成缺省、S3 不阻塞 | 无改判，只新增；`speaker_of` 是注入位，九个签名没动 | §5.5 第 4 行 |
| S4 | ① 攻击得手把攻击方**挪进那一格**并顺手净化 ⇒ 第三关起点比第二关终点退一格；② 攻击成功本身也 +1 抗原记忆；③ 第一关两格改到 v4 坐标 `(-5,-1)(-4,-1)` | 无改判，只新增 | 开发日志 S4 |
| S5 | **∞ 的显示判据是一条带宽不是一个数**：新增 `INFINITE_MIN = 90000`，数据里仍写 `INFINITE_AT = 99990` | `t_tutorial_npc` 零改动 | §3.2(b) / §4 的 301 行 |
| S5 修订 | Step2 保留分化种类；飘字只静玩家那只；右栏「癌性加权」整块藏掉（**只藏不挪**） | 见开发日志同条 | 开发日志 S5 修订 |
| S6 | 图鉴**解锁通知留、闸去掉**；`_mark_locked` 的纯函数判据保留不删 | 8 条（全在 `t_codex` / `t_tutor_chrome`），一条都没静默删 | §3.8 / 开发日志 S6 |
| S7 | 演出库是**时间的纯函数**，零内核 rng | `t_tutor_fx` 的 `PUBLIC_FX_MD5` 重录两支（表现组按 issue 改的） | 开发日志 S7 |
| S8 | 四条：① 钩子种子读 `hook.args.seed`，没写按关 id 定死；② 钩子里**必须** `await ctx.fail(...)`；③ 换局走 `director.open()`（第一行就是 `invalidate()`）；④ 对象账改成**两轮 churn 涨幅一样大**（`queue_free` 收不回挂死的协程） | `t_tutor_hooks` 的对象账那一条 | §3.7 |
| S9a | 格网按**世界半径**长；`set_active_tiles` 自己先 `ensure_radius` | 无改判，只新增 | 开发日志 S9a |
| S9b | 间章 PRD:423「分化后转普通免疫」落成**纯演出**（★ Kevin 09-19 定案；关内 `load` 那条作废：那一刻是活局面，写不死）；击退 = **重装**不是规则 | 无改判 | §4 的 399 行 |
| S10 | —— | `t_tutor_c2` 关表断言五关 → 六关（数据加了一关的必然结果） | 开发日志 S10 |
| S11 | 四条：① 第 18 步【细胞毒素】落成**演出**（★ Kevin 09-19 定案）；② 第 25 步「癌细胞死亡」落成**演出**（PRD:455 与 :527 打架，★ Kevin 09-19 定案）；③ `player` 条目也许写 `mode` / `tip`（否则覆写掉上一条 `point`）；④ 带子仍写 `rolls: []` | 无改判，`t_tutor_c3` 34 → 49 条 | §4.1 |
| S12 | 入口**恢复**（`main_menu.gd` 的 Guide `enabled` → true，唯一一处）；占位皮 P **留作兜底**（理由见 §5.2） | 3 条：`t_entry_smoke_tutorial`「入口灰着」→「入口已恢复」；`t_font_coverage` 阈值 `1 / 5` → **`4 / 20`** + 补一条「`energy_text` 的 ∞ 串逐字符在字库里」；`t_tutor_c1` 补迁 `t_guide_no_win` 的「不产 `game_over`」 | 开发日志 S12 |
| S13 | `∞` 走**补字形**那条终态（`tools/add_infinity_glyph.py` 手补 U+221E），没用 `INF` 兜底 | `t_font_coverage` 加 `supported.has(0x221E)` | §6.2 |

---

## 0. 裁决：主方案取丙，从甲搬三段、从乙搬四段

两位评委独立给出同一个排序（评委 1：主方案取丙；评委 2：丙 ≈ 甲 > 乙，并建议「丙的骨 + 甲的拆片 + 乙的四件」）。本稿照此裁决，逐段注明出处。

| 段 | 采纳谁 | 为什么 |
|---|---|---|
| §1 架构 / 目录 / 三张表 | **丙** | 教程整块住 `scripts/tutor/`（老教程散在 ui×7 + kernel×3 + core×1，这次挖了一天）；非 core 改动最小（只动 `cw_tutorial_stage.gd` 3 处 + `cw_guide_progress.gd` 1 处，约 8 行） |
| §1 结构闸的落法 | **丙 + 甲的理由** | 甲让导演住 `scripts/ui/` 是为了白嫖现成的 `t_no_engine_in_ui`（零护栏改动）；但代价是教程又散回 ui 目录。取丙的新目录 + **把闸改成递归并扩一条目录**（改的是测试不是内核，顺带罩住将来的子目录） |
| §2 数据格式 `cwtut/2` | **丙** | 从 PRD:5-30 的关卡通用模板**逐段直译**；九条数据纪律条条可查；**`flow[]` 每条带 `prd` 行号 + 对账闸**是三家里唯一能把「剧本覆盖度」变红绿灯的做法（剧本是 hxr 还在改的活文档，这条最值钱） |
| §3 流程机语义 | **丙**，取消语义补**乙的 epoch** | 丙的钩子取消语义整份没写（评委 2 点名）；乙的 `epoch + 永挂` 有 `match.gd:583/1099/1174` 的先例，直接搬 |
| §3.3 表现接口 | **丙**（基类给六个默认实现 + 三皮）+ **甲的 `point.mode`** | 通用规则 1/4/5/7/8/9 与「说话的样子」无关，两皮各抄一份必然漂移 —— 只有丙想到并解决；但丙的 `point()` 少了 `mode`，通用规则 8「较慢频次反差较低的轻微闪烁」落不了地，补甲的 `soft / arrow / fullscreen` |
| §4 特殊关落点表 | **甲 ∩ 丙**（两稿独立撞上同一答案 ⇒ 当定论用）+ **乙的 F5** | 间章阵营翻转**必须走完整换局、不是 `reload_world`**（`cw_tutorial_stage.gd:56-72` 注释原文「跳过算关 / 换席位 / 重挂面板三段」）—— 乙独家抓到，甲丙都漏 |
| §5 表现接口纪律 | 丙 + **乙的第三条** | `toast.keep_out` 禁区矩形归皮不归导演（`toast.gd`、`match.gd:798`），两皮形状必不同 —— 乙独家 |
| §6 测试 | 丙为骨 + **甲的 12 条覆盖率账** + **甲的桩关卡假皮** + **乙的 `t_tut_energy_formula`** | 丙测「时序」、甲测「意图序列」，两条互补都要；能量 66（v4）是人算的账，只有乙的「引擎现算复核」才是红绿灯 |
| §7 拆片 | **甲的形状** | 简报第 7 条硬要求「第一片必须是删老教程 + 新骨架 + 第一关端到端」，丙公开拒绝（T0/T1/T2 三连）。照甲合并成一个原子片，**允许它超尺寸**（评委 1、评委 2 同一建议） |
| §8 问答 | 三家并集去重 | 三家默认高度一致的（跳号 / 3-7 / 2.0 秒 / 黏 / 「无限」/ 规则 11 漏「无」字）打包问一次 |

**乙整体不取的两条理由**（两位评委一致）：① **改动频度倒挂** —— 天天改的（台词 / 顺序 / 数值）焊进 `.gd` 走代码评审，一次写完就稳的（盘面）留在 JSON，而 PRD 眼下待办几乎全是文案与数值；② 三处硬错（`immune_move_*` 当成旋钮、第三关能量 76 无账、转移几何写成「整数倍」而非 `5k+1`）。乙的**四件独家好东西**单独剥离搬进本稿（F5 / 能量复核闸 / epoch / 禁区矩形归皮），另加它列全的 `guide_layers.gd` **五个破口**清单。

---

## 1. 架构

### 1.1 一句话

**会改的东西进 JSON，一次写完就不动的东西进脚本，两段表达不了的进钩子。**
盘面 / 席位 / 旋钮 / 带子 / 活跃格 / 台词 / 顺序 → 一关一份 JSON；流程 → 同一份 JSON 里 `flow[]` 的九个动词；第七关的 25 步摆拍与间章的 10 分镜编排 → 各一个关卡钩子文件，经**九个方法的窄接口 `ctx`** 回调导演，**钩子够不着引擎、够不着皮**。

### 1.2 文件三张表

#### ① 保留（一个字不改）

| 文件 | 依据 |
|---|---|
| `game/scripts/kernel/cw_world_loader.gd` | cwxworld/2 装载器。顶层 15 键 `:37-39`、席位 5 键 `:41`、格 12 键 `:43`、细胞 33 键 `:45-50`；`load_world()` `:117`；`g.init(order, 1)` 种子恒 1 `:142`；半径按 `spec.radius` `:143-145`；「loader 不编数据」`:15-18`。C# `KeyTableTests` 按路径读它，**别搬别改** |
| `game/scripts/kernel/cw_roll_tape.gd` | 预设骰子 `:23-34`；`overrun` / `bad_range` 双向记账 `:11-12`；**`overrun` 静默回落真 rng** `:26-28` |
| `game/scripts/kernel/cw_tutorial_npc.gd` | NPC 席位驱动（Kevin 点名保留）：`POLICIES` `:31`（`approach` / `attack_if_adjacent` 正好是 PRD:453 那句话）、`decide()` `:39`、三级兜底 `:55-66`、`index_of()` `:120`、`Decider extends CWBridge` `:139-156`、`plan` `:147` |
| `game/scripts/kernel/cw_play_queue.gd`、`cw_kernel*.gd`、`game/scripts/core/**` | **零改动**（§4 逐条核过：PRD 全案没有一条要落到规则代码上） |
| `game/scripts/ui/board.gd` 活跃格一路 | `set_active_tiles` `:666`、`is_active` `:705`、`active_tiles` `:710`、`ring_delays` `:320`、`tile_center` `:107`、`hex_at` 只扫活跃集 |
| `game/scripts/ui/tutorial_opening.gd` + `game/scenes/tutorial_opening.tscn` + `data/tutorial/cutscenes/opening.json` | **开场动画保留**（Kevin 09-19 明令）。它是时间的纯函数、自带 rng（`:90`）、跳过 = `seek(duration())`；`main.gd:128-147` 的接线一字不动 |
| `action_bar.gd:278 button_rect` / `:288 bar_rect`、`match_panel.gd:265-289 rect_of` | 提亮层算矩形用，只换调用方 |

#### ② 保留但改（两个文件，约 8 行）

| 文件 | 改什么 | 为什么不重写 |
|---|---|---|
| `game/scripts/kernel/cw_tutorial_stage.gd` | ① `const DATA` 指新数据门面（`:23`）；② `_rolls()` 字段名跟新 schema（`:130-134`）；③ 文件头注释 | 它的价值全在那条四步拆装序列 `abort → queue.stop → close → dispose`（`:62-70`）。**`abort` 永远排在 `stop` 之前** —— 只有 `abort()` 里的 `_barrier_seq = 0` 能放掉正在等 ack 的那条 roll，先停队列 5 秒后内核报 barrier timeout，`tools/run_tests.sh` 当场判红。重写 = 把同一个坑再踩一遍 |
| `game/scripts/core/cw_guide_progress.gd` | 改 `_migrate_unlocked`（`:41-50`，它引用要删的 `CWGuideData`）；`codex_gated()`（`:146`）退役；`done` / `unlocked` / `at` 语义保留 | **`PATH`（`:20`）与 `SECTION`（`:21`）一个字都不能动** —— 开场动画的 `opening_seen` 住在同一份 cfg 的同一个 section（`tutorial_opening.gd:124-146`）。换文件名 / 段名 = 所有人的开场动画重播一次。**删这个文件 = 开场动画当场编译不过**（甲点名，`tutorial_opening.gd:131/137/146`） |

#### ③ 删（逐个核过，连 `.uid`）

`game/scripts/ui/guide.gd`（591）、`guide_bridge.gd`（264）、`guide_data.gd`（181）、`guide_layers.gd`（97）、`guide_shell.gd`（282）、`guide_spotlight.gd`（233）、`guide_watch.gd`（177）、`game/scripts/kernel/cw_tutorial_data.gd`（275）、`data/tutorial/index.json` + `levels/*.json`（5 份）+ `codex_map.json`（**`cutscenes/opening.json` 留**）、`match.gd` 的教程分支、`main.gd:_begin_tutorial` 的装配段、`game/tests/dump_guide.gd`（重写）、`guide_gate_probe.gd`、`preview/preview_guide.gd`、`screenshot.gd` 里的 guide 步骤（重写）。

**机制照抄、代码不留**：三态闸（`guide_bridge.gd:121-150`）、下标只映射一次（`:145-150`）、`mutes_result`（`:72-73`）、提亮矩形 / 六边形取法（`guide_spotlight.gd:143-158` / `:217-223` / `:176-224` 的四个纯几何函数）、UI 层「三个渲染点一条路」的教训（`guide_layers.gd:7-10`）——出处写进新文件注释。

> **删 `guide_layers.gd` 之前必须先接上五个破口**（乙独家列全，评委 1 点名直接写进第一片判据）：
> `match_panel.gd:341`、`tile_info.gd:145`、`ui_bridge.gd:630`（能量文本三个渲染点）、`ui_bridge.gd:506`（价签 `on("cost")`）、`ui_bridge.gd:526`（`on("move_path")` / `_plan_ok`）。
> **漏接一个就是真机上能量数字或价签当场不对**，而且不报错。

`docs/新手引导_实现方案.md`（1269 行）**已归档不删**（S12）：现在是 `docs/archive/新手引导_实现方案_v1_2026-09-19.md`，头部逐节写明了哪几节仍然有效（§1.3 世界半径 / §1.8 NPC 三级兜底 / §1.10 三类演出时序 / §2.2 装载器搬家 + 附 C 八个坑），其余随代码作废。仓库里指向老路径的 7 处引用同日一并改到新路径。

#### ④ 新建

```
game/scripts/kernel/                 ← 允许碰引擎的那一层
  cw_tutor_script.gd     数据门面：读 JSON / resolve(继承) / validate(十三条判据)
  cw_tutor_beats.gd      条目文法：九个动词表 + 三类谓词表 + allow 前缀匹配。纯函数、零引擎、零节点

game/scripts/tutor/                  ← 新目录：教程整块住这里，不许碰引擎（护栏 §6.2）
  cw_tutor_director.gd   导演：游标 + 装闸 + 意图分发 + 钩子调度 + epoch
  cw_tutor_ctx.gd        ★钩子接口：九个方法（§3.7，本稿新增，补丙的承重件图纸）
  cw_tutor_gate.gd       闸桥（extends CWUIBridge）：三态 allow + 下标只映射一次
  cw_tutor_view.gd       表现接口（基类 + 六个默认实现）
  cw_tutor_view_bubble.gd    皮 A：贴身气泡
  cw_tutor_view_theater.gd   皮 B：剧场对白
  cw_tutor_view_tally.gd     皮 T：计数皮（只记账不画，无头验收用）
  cw_tutor_chrome.gd     常驻壳：章节提示 / 全屏 STOP / 重置 / 目录（两皮共用）
  cw_tutor_spot.gd       提亮层：矩形 + 六边形（两皮共用）
  cw_tutor_layers.gd     UI 层白名单（13 层）——五个破口改指它
  cw_tutor_fx.gd         教程演出库：像素错误 / 冲击波 / 受击 / 重置动画 / 浮现，一律 apply(t) 纯函数
  levels/c3_l7.gd        第七关钩子
  levels/interlude.gd    间章钩子

game/data/tutorial/
  index.json  levels/c1_l1.json …  cutscenes/opening.json（保留不动）
```

### 1.3 职责边界：一条依赖线

```
data/tutorial/*.json                纯数据
      ↓ cw_tutor_script.resolve()/validate()      纯函数（校验期 load_world 一次，只为圆环比对）
cw_tutorial_stage.gd                ← 产品代码里唯一持 CWGame 的文件
      · load_world(spec) → CWGame ; g.rng = CWRollTape(rolls)  ★必须在 open() 之前
      · kernel.open({adopt, consumer, observe_viewer, autorun:false, decider, deciders}) → CWKernel
      ↓
cw_tutor_director.gd                只有 CWKernel + CWMirror + CWPlayQueue 三样
      ├── cw_tutor_gate.gd          人类作答（闸）
      ├── cw_tutorial_npc.Decider   NPC 席位作答
      ├── cw_tutor_view.gd          ← 意图（九类，§5），不知道皮长什么样
      └── levels/*.gd               关卡钩子，只经 ctx 的九个方法
```

四条不许跨的线：
1. **`scripts/tutor/**` 里零 `CWGame` / `CWWorld` / `CWActions` / `CWSetup` / `game.`**（源码护栏 §6.2）。
2. **导演不认识皮的实现**：只调基类的九个方法，换皮 = 换一个实例。
3. **钩子不认识导演的内部**：只经 `ctx` 的九个方法；`ctx` **不暴露 `kernel` / `mirror` / `game` 任何原始句柄**（评委 2 点名的开工前提）。
4. **钩子不许有成员变量**：状态只能放 `ctx.state()`（护栏扫；这是堵「把状态藏进钩子成员变量」那条慢性腐化的唯一实招）。

### 1.4 演出层与内核 rng 的隔离

| 类 | 谁产 | 怎么播 | rng |
|---|---|---|---|
| ① 内核演出（roll / result / fx / beam / erosion / card_*） | 内核 | `CWPlayQueue.play_one()` → 桥的 `show_*` | 内核 rng（= 带子） |
| ② 教程脚本演出（击退受击 / 像素错误 / 冲击波 / 浮现 / 重置动画） | `flow[].play` 或钩子 | `cw_tutor_fx.apply(t)`，**绝不入内核队列** | **自带 `RandomNumberGenerator` 实例 + 数据里写种子** |
| ③ 开场动画 | `cutscenes/opening.json` | 独立场景，压根不建内核 | 自带（`tutorial_opening.gd:90`） |

纪律两条理由：(a) 内核 rng 此刻是带子，多掷一次整条错位，而 `overrun` 是**静默**回落真 rng（`cw_roll_tape.gd:26-28`），错了不报；(b) 测试要「同种子逐帧复现」。
护栏：扫 `scripts/tutor/**` 与 `data/tutorial/**`，演出层不许出现裸 `randf(` / `randi(`（必须走实例方法）；`t_tutor_fx` 断言「整段零内核 rng 消耗（跑完带子 `at == 0`）」。

### 1.5 热更约束

- 新脚本**一律不带 `class_name`、调用方 `preload`**（补丁里新增的 `class_name` 进不了热更，全局类表导出时烘死；新类还要先 `--import` 才进无头测试）。先例：`cw_world_loader.gd:26`、`cw_tutorial_npc.gd:26`、`cw_tutorial_stage.gd:16-17`。
- **三个例外**，写进文件头「带 class_name，代价是走不了热更，别再往里塞新逻辑」：
  - `cw_tutor_chrome.gd` 与两版皮 —— 真机截图要 `screenshot.gd` 的 `call:类名:方法` 驱动（合成鼠标点击到不了 `Control`）；
  - `cw_tutor_layers.gd` —— 能量数字三个互不认识的渲染点，静态表最省。
- **会反复改的四件**（`cw_tutor_script.gd` / `cw_tutor_beats.gd` / `cw_tutor_director.gd` / `cw_tutor_gate.gd` + 两个钩子）**一个 `class_name` 都不许有**，护栏扫。本次随全量发版无痛，但日后调台词 / 调闸 / 调谓词 / 调钩子都能热更。
- 一个真坑：内部类里**不能有名为 `script` 的成员**（`Object` 自带），`cw_tutorial_npc.gd:146-147` 原话「叫 `plan` 不叫 `script`，同名当场编译不过」。

---

## 2. 数据格式 `cwtut/2`（丙，逐段直译剧本模板）

### 2.1 PRD:5-30 → 字段

| PRD 模板段 | 出处 | 落点 |
|---|---|---|
| 1 界面变化 | PRD:11 | `flow[].ui`（增量覆写 11 层，支持 `"*": false` 先全关再覆写）+ `flow[].reveal` |
| 2 游戏状态变化 | PRD:13 | 优先**预置进 `worlds.base` + `reveal` 揭示**；预置不了的才 `worlds{}` + `flow[].load` |
| 3 玩家任务 | PRD:15 | `flow[].until`（三类谓词，§3.3） |
| 4 自动重置条件 | PRD:17 | `flow[].reset_when`（+ `advise_when` / `advise` 劝重置那一档） |
| 5 流程 | PRD:19-29 | `flow[]` 本身，九个动词 |
| 5.1【O-玩家】 | PRD:21 | `{"do":"player"}` |
| 5.2 文本提示 | PRD:23 | `{"do":"say"}` |
| 5.3 UI 提示 | PRD:25 | `{"do":"point"}` |
| 5.4 动画演出 | PRD:27 | `{"do":"play"}` 或 `{"do":"hook"}` |
| 5.5 图鉴解锁 | PRD:29 | `{"do":"unlock"}` |

### 2.2 顶层 16 键（白名单）

```
schema id chapter chapter_kind chapter_title title subtitle seats human_seat
worlds active_tiles rolls hook flow on_done _doc
```

- `chapter` **变了才弹全屏章节提示**（PRD:35），没变就静默切关（PRD:37）。
- `chapter_kind`（★ Kevin 09-19 追加，丙原稿 15 键上多的那一个）：`"main"`（默认）/ `"interlude"`。**间章不是主章节的附属**，它自己一份数据、在目录里与三个主章节**平级单列**；章节提示的触发比的是 `(chapter_kind, chapter)` 这个二元组，不是单个整数。
- `seats` / `human_seat` 是**设计量不是副产品**：`players[]` 条数 = 引擎 `order.size()`，按人数分档的表直接读它（`CWData.level_min_memory` 里只有 4 人一档，其余一律回落六人档，`cw_data.gd:260/272`）。逐关显式写、逐关标定。
- `hook`（可选）：`"res://scripts/tutor/levels/c3_l7.gd"`。只有第七关与间章有。
- `rolls`：`[[from,to,value], …]`。**`rolls: []` ≠ 省略** —— 空带子 = 「这一关一次 rng 都不许消耗」的断言。
- `_doc` 不进字形闸（现状口径保留）。

### 2.3 九条数据纪律（写进 `index.json` 的 `_doc`，校验器逐条核）

1. `worlds.*` 只许 `cw_world_loader.gd:37-39` 的 15 个顶层键；每份过 `load_world` 且 `dump_world(load_world(spec)) ≡ minify(spec)`。
2. **省略 `type` = 棋盘本来的特殊组织**（`cw_data.gd` 的 `special_of`）。11 个特殊格：核心 `(0,-3) (3,0) (-3,3)`（`cw_data.gd:529`）、骨髓 `(3,-3) (0,3) (-3,0) (6,-3) (-3,6) (-3,-3)`（`:530-533`）、血管 `(6,0) (-6,0)`（`:534`）。压到这 11 格的活跃格要逐格显式写 `"type": "normal"`，否则白送收入格。**推论：这 11 格的 `r` 只取 -3/0/3/6 ⇒ `r=-1` 与 `r=-2` 两整排零特殊格**，第一～三章的教学带就走这两排。
   ★ **第四关起整盘 127 格全在活跃集里，这 11 格写的是它**本来的名字**（`core` / `marrow` / `vessel`）而不是 `normal`**（v4 口径 4，S5）：第一～五关从 `PlayerAction` 中途开局、闸里永不放「结束回合」⇒ 进不到 S 阶段 ⇒ 收入与存卡不结算，摊不摊平零影响；而第六关要真结算，那时它们本来就该是特殊格。校验器只要求**显式写**，不要求写 `normal`。
3. 能量一律写**十分位整数**（`INIT_ENERGY := 30` = 3.0，`cw_data.gd:76`）。
4. **一格一细胞**（装载器 `:279-284` 拦，连 `alive:false` 的死细胞一起数）、**一席一细胞**、`players[i].seat == i`。PRD 的「若干癌细胞」逐只展开成席位。
5. 多个免疫席的 `level` / `memory` 必须一致（GD 里是阵营共享量，`cw_world_loader.gd:201`）。
6. **数字不写死在文案里**：要出现数值就写 `{{tune.attack_dmg_success}}`，渲染期从 `CWMirror.tune` 现取。
7. 旋钮只走 `worlds.*.tuning`（装载器四档白名单 `_load_tuning` `:443` / `_load_knob` `:464`），不许绕过去 set。
8. **缺席阵营**（只有第一关）：给癌席一只 `alive:false` 的死细胞，占**活跃集之外**的格（`hex_at` 只扫活跃集，看不见也点不到）。**不要写「不给细胞」**（与「每席恰好一只」冲突，S2 实测），也不要写「只有一个免疫席的局」。
9. **固化癌组织写 `state: "solid"`，不是 `solid: n`**（后者是固化**计数**，TILE_KEYS `:43` 里两者并列）。两种写法都合法 ⇒ 圆环比对抓不到，**单列一条断言**。

### 2.4 `worlds` 继承（这次真实现）

```jsonc
"worlds": {
  "base":   { /* 完整 cwxworld/2 */ },
  "knock1": { "from": "base",   "patch": { "cells": [ { "seat": 0, "at": "-4,-1" } ] } },
  "signet": { "from": "knock1", "patch": {
      "players": [ { "seat": 0, "cancer_type": "SignetRing" } ],
      "cells":   [ { "seat": 0, "type": "SignetRing" } ] } }
}
```
`patch` 语义只四条：`tiles` 按 `at`、`cells` / `players` 按 `seat` upsert；值写 `null` = 删这一条；顶层标量直接盖；数组不合并。**继承在教程侧纯函数 `resolve()` 里做完，装载器永远拿到完整 spec**（`cw_world_loader.gd:15-18` 一个字不动）。

### 2.5 Step 与关的关系（定死）

- **一关 = 一份 JSON = 一次换局。PRD 的 Step 只是 `flow[].step` 上的标签**，用来对账与目录显示，**不切关、不换局**。两条硬理由：
  - 第三关（PRD:223-283）的界面 / 状态变化写在**关级**（PRD:225-243），能量公式是**整关一个预算**；Step2 一重装，Step1 的整堂课与自动重置判据当场作废。
  - 第二关 Step1 玩家亲手净化两格（PRD:155-171），Step2 才延伸一格癌组织（PRD:187）。重装就要把「玩家净化过哪两格、人站哪」重新写死 ⇒ 用 `reveal`（预置 + 遮罩揭示），零重装。
- **关内 world 重装只在三处**：第五关 Step2 癌块扩大（PRD:361，改的是**已露出**的格，遮罩揭不了）、间章（阵营翻转 / 生固化 / 击退）、第七关（击退 / 癌种切换 / 复活拨能量）。
- **落点优先级**（校验器核）：① 能预置的一律预置 + `reveal`；② 预置不了的（改已露出格的性质、换阵营 / 癌种、击退、复活后拨能量）→ `load`；③ 两条都落不到 → 纯演出层。
- **间章是独立的一段，不是第五关的尾巴**（★ Kevin 09-19：「间章不是主章节的附属章节」）：自己一份 `levels/interlude.json`（`chapter_kind: "interlude"`、`chapter_title: "癌变"`、`hook: levels/interlude.gd`），第五关的 `on_done` 指它、它的 `on_done` 指 `c3_l7`。
  甲原稿把间章挂在第五关最后一个 Step 的 `flow` 末尾（理由是 PRD:393「在上一关最后一个癌细胞被杀死时」要无缝），**本稿否掉那种挂法**：无缝是靠「关切换本来就静默 + 间章第一条 `state` 不重装、只关 UI」做到的，不需要把它做成第五关的附属。
  代价与判据：第五关 Step2 是自由游玩（PRD:381「来场盛大的爆炸吧」），**终局盘面不是作者期能写死的**（哪几格被净化、免疫 NPC 站哪都随玩家）。所以间章这样接：
  - **第一拍不重装**：`flow[0]` 写 `{"do":"state","load": null, "ui": {"*": false}}` —— 承接第五关的活局面，冲击波在玩家细胞**原地**起（PRD:393）。⇒ §2.10 校验第 11 条加一条例外：**只有 `chapter_kind == "interlude"` 允许 `load` 为 `null`，且必须显式写出来**（省略仍判红，避免「忘了写」冒充「有意不装」）。
  - 「最近一个免疫细胞」（PRD:409）由钩子在**运行期**用 `ctx.read("cells")` 找（正是钩子的本分，数据写不死）。
  - 后面两次重装（PRD:403 阵营翻转、PRD:411 固化 + 击退 1 格）**照常重装**，而且**正好盖在像素错误 / 剧烈抖动 / 冲击波的演出里** —— 重装的跳变被演出遮住，这是间章唯一能安全重装的两个窗口。
  - `t_tutor_interlude` 判据：① 进间章前后玩家细胞坐标一致、无黑场；② 翻转那一次走的是**完整换局**（下表 PRD:403 那一行）。
  - **S9b 已实装（2026-09-19）**：承接落在 `CWMatch._tutor_next_level` 的「承接」那一支 —— `CWTutorScript.adopts_live(lv)`（`flow[0]` 显式写了 `"load": null`）为真就**一局都不拆**（局面 / 席位 / 桥 / 队列全留着），只换导演手里的剧本 + 把舞台的 `level` 换成新那一份。连带口径：间章的「重置本关」不装 world（`_tutor_entry_world` 给空串）—— 它没有关首那一份，也因此**开不了冷局**（`guide_progress` 停在间章时进不去，唯一合法入口是第五关的 `on_done`）。翻转那一次写成 `state.load` 的第三种表写法 `{"world": "flip", "rematch": true}` → 导演的 `want_rematch` → `CWMatch._tutor_rematch` → 与跨关换局共用 `_tutor_reopen(wid, fresh_cursor)`，差别只有两处：**游标不动**、**UI 层表不推回全开**。

### 2.6 `flow[]` 的九个动词

每条通用字段：`do`（必填）、`step`（Step 标签）、`prd`（**PRD 行号，对账闸用**）。

| `do` | 字段 | 语义 | 阻塞？ |
|---|---|---|---|
| `state` | `load` `ui` `reveal` `npc` | 结算界面 + 状态。**PRD:39 ⇒ `flow[0]` 必须是它且必须带 `load`**（校验器硬核；**唯一例外是间章：`load` 可以显式写 `null` 承接上一关的活局面**，§2.5）。**`load` 有两种写法**（S5 修订，2026-09-19）：① 字符串 = 点名一份 world；② `{"by_player_type": {"BCell": "b", "TCell": "t", …}}` = **按玩家此刻的免疫种类**挑一份 ——键就是 world spec 里 `cells[].type` 那个词，导演运行期照镜像里玩家那只现挑（`cw_tutor_director._world_for`），`flow[0]` 只许写法 ①（「重置本关」退回的就是它）；③ `{"recenter": "player", "radius": 11}` = **不点名任何一份 world**，把**活局面**`dump_world` 出来、每个坐标键平移 −P（P = 锚点那只此刻那格 ⇒ 它落到 `(0,0)`）、半径改成这里写的那个数，再走**关内换盘**（间章分镜 2，S9a；平移本体在 `CWTutorScript.translate`，全案唯一一处）。②③ **互斥**，且都只许出现在关内的 `state` 上 | 否 |
| `say` | `who` `lines` `beats` `auto` | `who`：`player`（默认，PRD:23）/ `seat:<n>`（PRD:407）/ `narrator`（PRD:397 的「……」）/ `ui:<控件 id>`（PRD:447、PRD:479 按钮弹提示） | 是 |
| `point` | `ui` `hex` `mode` `tip` | UI 提示。`ui`：`["bar:迁移","panel:end","panel:level","hand","skill:转移"]`；**`mode`：`soft`（默认，PRD:49 轻微慢闪）/ `arrow` / `fullscreen`（PRD:445 全屏引导指向）**；`tip` 挂在目标上的一句话（PRD:447） | 否 |
| `unlock` | `ids` | 图鉴解锁（PRD:29 的 12 处） | 否 |
| `play` | `fx` `at` `secs` `args` `seed` `await` | 教程演出层的一段（`cw_tutor_fx` 的一支）。**S9b 已接线**：导演发一条 `want_play(fx, args, done)`（同 `want_npc` 的形制），`CWMatch` 喂给挂在棋盘底下的演出库；`at` / `args.actor` 里的 `"player"` / `"seat:<n>"` 由导演翻成席位号（演出层再用注入的 `seat_at` 换成格）、`"q,r"` 翻成 `Vector2i`；`await: true` 等回执才翻页、`false` 只等 `secs`，回执带**段号**（上一段的迟到回执解不开这一段）；`args.actor` 那一席的**真身由 `CWMatch._sync_cells` 让位**（演出层自己 `_hide` 藏不住，每帧会被重写），贴图 `args.tex` 也由它现补 | 是 |
| `wait` | `secs` | 「等待几秒」（PRD:395） | 是 |
| `player` | `allow` `until` `hint` `hex` `ui` `reset_when` `advise_when` `advise` | 【O-玩家】：开闸 + 完成判据 | 是 |
| `npc` | `seat` `plan` | 给某席换脚本（`Decider.plan`，`cw_tutorial_npc.gd:147`） | 否 |
| `hook` | `call` `args` | 交给关卡脚本的一段（§3.7） | 是 |

**只有九个动词，不允许第十个**（甲的纪律照搬）：新需求先问「能不能写成 `play` 的一支 fx」，再问「能不能进钩子」。
连续的不阻塞条目同帧跑完 ⇒ `state → point → unlock → say` 对玩家就是「界面换好了、格子亮了、书解锁了、然后角色开口」，正是 PRD:39 的次序。

### 2.7 样例 A · 第一关（PRD:91-137，整关）

```jsonc
{
  "schema": "cwtut/2", "id": "c1_l1",
  "chapter": 1, "chapter_title": "Cell", "title": "第一关 免疫",
  "subtitle": "认识健康组织，学会【迁移】",
  "seats": 2, "human_seat": 0,

  "worlds": {
    "base": {
      "radius": 6,                 // 全程 6：小棋盘靠活跃集，长地图靠 reveal，零重装
      "round": 1,
      "phase": "PlayerAction",     // 从行动回合中途开局：S 阶段一条都不跑 ⇒ 零 rng 消耗
      "seat": 0,
      "players": [
        { "seat": 0, "faction": "immune", "level": "I", "memory": 0 },
        { "seat": 1, "faction": "cancer", "cancer_type": "Osteosarcoma" }
      ],
      "cells": [
        { "seat": 0, "type": "ImmuneBasic", "at": "-1,-1", "energy": 99990 },
        // 纪律 8：缺席阵营 = alive:false 的死细胞，占活跃集之外的格
        { "seat": 1, "type": "Osteosarcoma", "at": "6,-1", "alive": false }
      ]
      // tuning 省略 ⇒ 整关零旋钮
    }
  },

  "active_tiles": ["-1,-1", "0,-1"],   // PRD:95「两个横向连接的健康组织」
  "rolls": [],                          // PRD:91-137 全关零抽取 —— 空带子 = 断言

  "flow": [
    { "do": "state", "prd": 93, "load": "base",
      "ui": { "*": false, "action_bar": true, "move_path": false, "cost": false, "energy": "infinite" } },

    { "do": "say", "prd": 117, "who": "player",
      "lines": ["欢迎来到Cell_War！", "你是一个Q弹软萌的免疫细胞——", "作为主人忠诚的卫士，正在工作中…"] },

    { "do": "say", "prd": 123, "who": "player",
      "lines": ["眼前的绿色格子是组成身体的基本单元——**健康组织**"] },
    { "do": "unlock", "prd": 125, "ids": ["tissue_healthy"] },

    { "do": "say", "prd": 127, "who": "player",
      "lines": ["下面继续巡逻吧！", "使用【迁移】，向前行动一格"] },
    { "do": "unlock", "prd": 131, "ids": ["move"] },

    // PRD:137「按玩家操作依次使【迁移】按钮，地图上目的格子闪烁」—— 两个目标并存、慢闪
    { "do": "point", "prd": 137, "ui": ["bar:迁移"], "hex": ["0,-1"], "mode": "soft" },

    { "do": "player", "prd": 133,
      "hint": "点底部「迁移」，再点右边那一格",
      "allow": ["k=action|act=move|to=0,-1"],
      "until": { "delta": "moved" } }
  ],

  "on_done": "c1_l2"
}
```

### 2.8 样例 B · 第三关 Step1 / Step2（PRD:239-301，整关一份，零关内重装）

★ **已落地（S4，2026-09-19）**：正本是 `game/data/tutorial/levels/c1_l3.json`，下面这份样例按**盘面提案 v4** 同步过数字，细节（PRD 行号基线、纪律 2 的四个特殊格、要 hxr 答的那条）以正本的 `_doc` 为准。

盘面标定（Kevin 09-19：「可以踩癌组织，只要在确定的关卡条件下是最短路就行」；坐标照盘面提案 v4）：免疫起 `(0,-1)`；癌块**唯一一个、9 格**＝中排 `(3,-1) (4,-1) (5,-1) (6,-1)` + 柄 `(5,-2) (5,-3)` + 下排 `(3,0) (4,0) (5,0)`（PRD:245 的「凸」）；3.0 能量的癌细胞站在连通块正中 `(5,-1)`。
最短路 = **3.0，两条并列**（Q3-6 接受并列）：直线 2 格健康（`IMMUNE_MOVE_HEALTHY[0] = 5`，`cw_data.gd:181`）+ 2 格癌（`IMMUNE_MOVE_CANCEROUS[0] = 10`，`:190`）落 `(4,-1)`；绕 `r=-2` 排 4 格健康 + 1 格癌落 `(5,-2)`。⇒ 判据写「到相邻格」（`state: beside`），**不判路径**。
**能量 `66` = 30（最省路）+ 30（三次攻击 × 1.0）+ 5（失效自损 `COUNTER_DMG_ON_FAIL := 5`，`:382`）+ 1（PRD:261 的 +0.1）。**
劝重置阈值 **35**（= 攻击三次 30 + 反弹 5）把两档分得干干净净：走 3.0 剩 36 ≥ 35 不劝，次优 3.5 剩 31 < 35 当场劝。
伤害 10 + 0 + 20 = 30 = 癌细胞 3.0 能量，**第三次刚好打死**（`ATTACK_DMG_SUCCESS := 10` / `ATTACK_DMG_CRIT := 20`，`:377-378`）。

```jsonc
{
  "schema": "cwtut/2", "id": "c1_l3",
  "chapter": 1, "chapter_title": "Cell", "title": "第三关 ATP",
  "seats": 2, "human_seat": 0,

  "worlds": {
    "base": {
      "radius": 6, "round": 1, "phase": "PlayerAction", "seat": 0,
      "players": [
        { "seat": 0, "faction": "immune", "level": "I", "memory": 0 },
        { "seat": 1, "faction": "cancer", "cancer_type": "Osteosarcoma" }
      ],
      "tiles": [
        // 纪律 2：r=0 这一排压到 4 个特殊格（血管 (-6,0) (6,0)、骨髓 (-3,0)、核心 (3,0)），逐格显式写 type
        { "at": "-6,0", "type": "normal" }, { "at": "-3,0", "type": "normal" },
        { "at": "3,0", "type": "normal", "state": "cancer" }, { "at": "6,0", "type": "normal" },
        { "at": "3,-1", "state": "cancer" }, { "at": "4,-1", "state": "cancer" },
        { "at": "5,-1", "state": "cancer" }, { "at": "6,-1", "state": "cancer" },
        { "at": "5,-2", "state": "cancer" }, { "at": "5,-3", "state": "cancer" },
        { "at": "4,0", "state": "cancer" }, { "at": "5,0", "state": "cancer" }
      ],
      "cells": [
        { "seat": 0, "type": "ImmuneBasic",  "at": "0,-1", "energy": 66 },
        { "seat": 1, "type": "Osteosarcoma", "at": "5,-1", "energy": 30 }
      ]
    }
  },

  // PRD:243「延伸部分纵向宽度扩充为 3 格」：r=-2 的 q -4…6、r=-1 的 q -5…6、r=0 的 q -6…6 三整排 + 外突的 (5,-3)，共 37 格
  "active_tiles": ["-4,-2", …, "6,-2",  "-5,-1", …, "6,-1",  "-6,0", …, "6,0",  "5,-3"],

  // PRD:239「下三次攻击结算为成功、失效、大成功」（r==6 大成功 / r<=2 失效 / 3~5 成功）
  "rolls": [[1,6,3], [1,6,1], [1,6,6]],

  "flow": [
    { "do": "state", "step": "Step1", "prd": 225, "load": "base",
      "ui": { "*": false, "action_bar": true, "sidebar": true,   // PRD:247 第三关才弹右栏
              "round_no": false, "end_turn": false,              // 只留状态框 + 抗原记忆框（Kevin：第一～三章藏回合数）
              "move_path": false, "cost": false, "energy": "plain",
              "camera": { "anchor": "map", "align": "center" } } },   // 2026-09-20 改地图调中：PRD:249 写「角色调左」，v4 横带向左接上前两关后左边六格出镜（Kevin 09-20）

    { "do": "say", "prd": 257, "who": "player",
      "lines": ["发现新的癌细胞，继续清理", "使用【迁移】移动到癌细胞相邻格"] },

    { "do": "player", "prd": 261,
      "hint": "自己算一条最省的路",
      "allow": ["k=action|act=move"],
      "until":       { "state": "beside" },
      // PRD:251 第一条：能量不足以移动 → 自动重置
      "reset_when":  { "state": "stuck" },
      // PRD:251 第二条：到了相邻格但所剩能量小于预期 → 劝重置（Kevin 09-19：不自动重置）
      // 35 = 攻击三次 3.0 + 反弹自损 0.5，十分能量
      "advise_when": { "state": "low_energy_beside", "arg": 35 },
      "advise": "能量算亏了，这一路打不完。点左上角「重置本关」再来一次吧" },

    { "do": "say", "step": "Step2", "prd": 271, "who": "player", "lines": ["继续攻击癌细胞"] },

    // PRD:275「玩家前两次攻击」
    { "do": "player", "prd": 273,
      "hint": "迁到癌细胞那一格就是攻击",
      "allow": ["k=action|act=move|to=5,-1"],
      "until": { "delta": "attacked", "count": 2 } },

    { "do": "say", "prd": 277, "who": "player", "lines": ["Oops! 攻击失效，收到了反弹伤害"] },
    { "do": "unlock", "prd": 279, "ids": ["attack"] },
    { "do": "say", "prd": 281, "who": "player", "lines": ["不要灰心，继续尝试攻击"] },

    { "do": "player", "prd": 283,
      "allow": ["k=action|act=move|to=5,-1"],
      "until": { "state": "all_dead" } }
  ],

  "on_done": "c2_l4"
}
```

**为什么 Step1 不给 `point.hex`**：这一关的全部教学量就是「自己算最省的路」，把答案闪出来等于替玩家做题；PRD 第三关本来就没有「UI 提示」那一段。（我方口径，要改就改数据一行。）

### 2.9 样例 C · 第七关前 8 条（PRD:417-459）

几何（甲、丙独立算出同一答案，**当定论用**）：【转移】固定跃进 5 格（`METASTASIS_RANGE := 5`，`cw_data.gd:341`）⇒ 转移那一刻的距离必须是 **`5k+1`**（`5k` 会落到 T 细胞头上 = 非法）。PRD:467-481 是「移动 1 → 击退 2」两轮、每轮净 **+1** ⇒ 起点距离 `D + 2 = 5k + 1`，**取 D = 9**：玩家癌细胞起 `(-3,-1)`、T 细胞 `(6,-1)`（`r=-1` 排零特殊格）。两轮后玩家落 `(-5,-1)`、距离 11 = 5×2+1 ⇒ 两次转移 `(0,-1) → (5,-1)`，正好邻接。
**别用 `(-5,-1)` 当起点**：击退会落到盘外的 `(-6,-1)`，装载器当场拒。

```jsonc
"hook": "res://scripts/tutor/levels/c3_l7.gd",

"flow": [
  // PRD:417-423 界面 + PRD:427-435 状态（关级，落在关首这一条）
  { "do": "state", "prd": 417, "load": "base",
    "ui": { "*": false, "sidebar": true, "end_turn": true,
            "round_no": false,                 // PRD:421「上方不显示第 X 回合」= 只隐藏、照常推进
            "move_path": false, "cost": false, // PRD:433 锁定迁移模式
            "energy": "null" } },              // PRD:431 Null / 内部无限（哨兵 99990 + overload_div:0）

  { "do": "npc", "prd": 455, "seat": 2, "plan": [] },   // 席位脚本在 hook 里按轮次换，这里只登记
  { "do": "say", "prd": 439, "who": "narrator", "lines": ["……"] },

  // PRD:443「引导玩家迁移将临近免疫细胞围一圈癌组织」——
  // 每次亮一个方向、玩家走一格，直到围满：**运行期才知道亮哪一格** ⇒ 钩子
  { "do": "hook", "prd": 443, "call": "encircle" },

  { "do": "point", "prd": 445, "ui": ["panel:end"], "mode": "fullscreen",
    "tip": "点击结算【微环境压迫】" },                     // PRD:445 + :447
  { "do": "player","prd": 445, "allow": ["k=action|act=end"], "until": { "delta": "ended" } },

  // PRD:449「正常结算【微环境压迫】【增生】【侵蚀】」= 真跑 E 阶段，导演等这一轮播完
  { "do": "play", "prd": 449, "fx": "none", "await": { "entry": "e_done" } },
  { "do": "unlock", "prd": 451, "ids": ["pressure", "proliferate", "erosion"] },

  // PRD:453 免疫靠近 / 邻接则攻击；PRD:455 B 细胞三次抗体；PRD:457 巨噬净化动画
  { "do": "hook", "prd": 453, "call": "immune_turn" },

  // PRD:459「重复 3-5（我方按 3-7 读，Q-03）直到剩余最后一个 T 细胞」——**终止条件是运行期的**
  { "do": "hook", "prd": 459, "call": "repeat_until_last_t" }
]
```

> **为什么这三条走钩子而不是抄死条目**（评委 1、评委 2 对甲的同一条致命伤）：PRD:443 的「围一圈」与 :459 的「直到剩最后一个 T 细胞」都是**要看运行期盘面才知道下一步亮哪一格 / 还要不要再来一轮**的事。甲的答案是「把第 3~7 条再抄两遍」，代价是盘面动一格、轮数改一轮就要重抄 JSON + 重录带子 + 重对双向归零。钩子把这三条变成改几行代码。

### 2.10 校验（`validate()` 十三条，装载期就红）

1 `schema == "cwtut/2"`；2 顶层 / flow 条目只许白名单键；3 每席恰好一只细胞、`players[i].seat == i`、一格一细胞；4 `active_tiles` 全在半径 6 盘内、压到 11 个特殊格的都显式写了 `type`；5 每个 world 名跑 `resolve → load_world → dump_world ≡ minify(resolve)`；6 `flow[].do` 在九个动词里；7 谓词键在 `cw_tutor_beats` 的三张表里（含 `count` / `arg` 形状）；8 `allow` 每条是合法语义键前缀（字段名在 `cw_semkey.gd` 的 `KEY_FIELDS` 里）；9 `unlock.ids` 在 `codex_map.json` 里有归宿；10 `play.fx` 与 `hook.call` 点名的分支 / 函数真实存在；11 **`flow[0].do == "state"` 且带 `load`**（PRD:39）——**唯一例外**：`chapter_kind == "interlude"` 的那一份允许 `"load": null`，但必须**显式写出**（省略照样判红）；12 `rolls` 写了就必须**双向归零**（少给报错、剩下没用完也报错，同 `l0_runner` 的 `_check_tape`）；13 **`prd` 行号单调不减且逐关覆盖 PRD 的编号行**（对账闸）；14 `state.ui.camera` 的形状与两个枚举（S3 加）；15 `state.load` 写成表时只许 `{"by_player_type": {<种类名>: <world 名>}}`，键在 `PLAYER_KINDS` 里、值是这一关真有的 world（S5 修订加）。

---

## 3. 流程机（导演）语义

### 3.1 推进

导演持一个游标 `_at`（flow 下标）。驱动只有三个源：

1. **`queue.on_step` 的 `step_end`**：装闸 / 判上一条 / 翻页的**正牌时机**。
2. **每帧 `_process`**：镜像谓词（`until` / `reset_when` / `advise_when`）、`say` 的节拍、`wait` 的计时、`play` 的 `apply(t)`、`hook.resume()`。
3. **玩家点「继续」**：皮发 `advance_pressed`（只有 `say` 且 `auto:false` 时导演才理）。

`_apply(at)` **幂等**：同一条被装两次不会出第二份效果。

**装闸的唯一正确时机是 `step_end`**：`cw_kernel_inproc.gd` 的 `_on_ask` decider 路是 `_close_step()`（推 step_end + sync）→ `await deciders[pid].ask(req)` → `_open_step()`（推 step_begin）。所以 **`step_begin` 标的是「这一问已经答了、动作开始演」**，不是「要问了」。
⚠ **行号存疑**：丙给 `:391/393/395/399`，甲与乙给 `:399/400-401/406`。**第一片开工第一件事按文件核一次**，把准确行号写进新文件注释。
**关首再装一次**（`open()` 返回后、`kernel.run()` 之前）：关的第一帧在队列泵到那条 `step_end` 之前就画出来了，不提前装玩家会先看见一瞬间的全套界面（`match.gd:532` 的注释原账）。

### 3.2 O-玩家 = 开操作闸

**(a) 决策闸 `allow`（三态）**，住 `cw_tutor_gate.gd`（`extends CWUIBridge`）：

| 值 | 语义 | 用在哪 |
|---|---|---|
| 缺省 `null` | 不过滤 | 自由游玩段（本 PRD 只有第五关 Step2 半开） |
| `[]` 空数组 | **全禁**：这一问挂起不作答，行动栏根本不建 | **所有非 `player` 条目**（PRD:51） |
| 非空 | 只留命中的选项（**前缀**匹配语义键） | 每一个 `player` 条目 |
| 非空但一条都没命中 | 剧本写错：**warning + 挂起**，绝不回落成全开、绝不替玩家乱答。出路是常驻「重置 / 目录」 | —— |

- 选项在观测协议里已带语义键（`cw_obs_codec.gd` 写 `"key": CWSemKey.key(req, data)`），文法 `k=<kind>[|g=<tag>]|<field>=<v>|…` 与 C# `SemanticKey.cs` 逐字相同。
- 行动栏从 `req["options"]` 建（`ui_bridge.gd` 的 `_ask_action`）⇒ **过滤掉的按钮根本不出现**，不是置灰。
- **下标只许映射一次**（附 C 那条最贵的坑）：`ask()` 里存的是**过滤后的 view**，`return keep[await _ask_ui(view)]` 是全文件唯一一处映射。存错了不崩，静默选错选项。
- **`ask()` 里必须自己先 `await _await_playback()`**：`allow` 是队列播到 `step_end` 才装的，而 `CWUIBridge` 的那次等在 `super.ask` 内部（`ui_bridge.gd:190/203 → :236-241`），不先等就读到上一条的闸。
- **第一～五关的 `allow` 里不放「结束回合」** ⇒ 永远进不了 E 阶段 ⇒ 胜负判定压根不跑（只在 E 阶段末判）。这替掉了老导演的 `g.win_checks = false`。

**(b) UI 变体** —— `flow[].ui` 的 13 层（`cw_tutor_layers.gd` 白名单，写错层名当场 warning；第 12 层 `camera` 见 §4 镜头，第 13 层 `notice` 是 S12 之后补的）：

```
"*"            通配：先全关再按下面覆写（间章 PRD:387「所有 UI 消失」一条搞定）
action_bar     行动栏（按哪些按钮由 allow 收，这里只管开不开）
sidebar        右栏（PRD:231 第三关弹出）
round_no       右栏顶部回合块（PRD:421 第七关不显示）
end_turn       右栏结束回合按钮（PRD:421）
hand           手牌抽屉（全程 false，Q-06）
skill_bar      技能按钮（PRD:477 第七关第 15 步才显示）
notice         结算说明气泡（「攻击成功」「攻击次数已用尽」…）；关掉只静字，盘面特效与日志照旧。
               教程七关全靠关首 `"*": false` 关掉（Kevin 09-19 晚「收掉」）；正式局缺省开
switch_type    切换种类按钮；值是一组 world 名（PRD:355 第五关 Step2）
move_path      迁移路径规划器（PRD:107/151/197）
cost           每格耗能与按钮价签（PRD:107）
energy         "plain" | "infinite" | "null" | "hidden"
```

`energy` 的准确语义（老 `guide_layers.gd:94-97` 实测）：**`"infinite"` 不是「强制显示无限」，是「见到哨兵值就写『无限』，其余照常写数字」** ⇒ 第三关（真能量 6.6）与第四关（哨兵）可以共用一档。
★ **实测改判（S5）：「见到哨兵值」是一条**带宽**，不是 `INFINITE_AT` 那一个数。** 哨兵 99990 不是真的无限 —— 玩家每走一格就被【迁移】啃掉 0.5~1.0，第四关整盘跑一趟约 100 能量。第一～三关右栏是关着的（`ui.sidebar: false`）所以没显形，**第四关是第一关「右栏开着 + 无限能量」的关** ⇒ 拿 `>= 99990` 去判的话，玩家走第一步那一刻「∞」就变回「9998.5」。落地：`cw_tutor_layers.gd` 新增 `INFINITE_MIN = 90000`，`energy_text` 的 `infinite` / `null` 两档比它；**数据里写的仍是 `INFINITE_AT = 99990`**，两个常量各管各的（一个是「数据写什么」、一个是「什么算无限」）。
**∞ 的字形（★ Kevin 09-19 结案，不再退成「无限」）**：缝合像素 10px 的 25070 个字形里没有 U+221E（`guide_layers.gd:20-23` 实测），字形闸 `t_font_coverage` 当场拦。Kevin 原话「**补字形，如果没有相似字形，就用 INF**」⇒ 落法两档，按顺序试：
1. **给字库补 U+221E**（也可以从字库里挑一个形近字形改，够像就用）⇒ 显示串常量 `ENERGY_INF_MARK := "∞"`，`t_font_coverage` 自然放行；
2. 补不出（没有相似字形可改）⇒ 常量改成 **`"INF"`**（三个 ASCII 字形字库里都有）。
**一处常量、三个渲染点一条路**（`match_panel.gd:341` / `tile_info.gd:145` / `ui_bridge.gd:630` 都走 `cw_tutor_layers.energy_text()`）。这件事**独立成一片 S13**，不塞进任何一关的片里 —— 它要动字库资产，与流程线零耦合，可并行。

**(c) 「不消耗能量」怎么办**（PRD:105/149/195）—— **落不到旋钮**：`immune_move_healthy` / `immune_move_cancerous` 都是 **tier C**（`game/data/contract_tune.json`，note 还写着「数组型，下标语法未定」），装载器双重拒。
落点 = **大能量 `99990` + `ui.cost=false` + `ui.move_path=false`**。攻击费（攻击 = 迁进癌细胞格，先扣费再判出攻击）一并被盖住。
> 两位评委都把这条列为**第一片就会撞的墙**（乙的稿在这里写错）。不建议为教程把这两条 tier C 升档 —— 那是跨语言契约改动。

### 3.3 完成判据 `until`：三类谓词

老 `guide_watch.gd` 的 `KEYS` 表作废，但**两条教训原样照抄**：
- **计数类谓词只在同一个行动回合内有效**（引擎每个行动回合把 `attacks_used` / `draws_used` 清零）⇒ 基线里记「这是谁的第几回合」，换回合自动重取基线。
- **默认值方向选保守那一边**：`can_move` 默认 **true**（「没在问 = 谈不上走不动」，`guide_watch.gd:54`）、`foes` 默认 **1**（「不知道 = 还有敌人」，`:56-57`）。反过来写，关卡会在「还没有镜像」那一瞬间被自动重置掉 / 被直接翻过去。

| 类 | 写法 | 怎么算 | 有哪些 |
|---|---|---|---|
| **差分** `delta` | `{"delta":"attacked","count":2}` | 条目入口拍一张 `snap()`，每帧与现在比 | `moved` `purified`（抗原记忆涨 = **亲手**净化，卡牌引发的不给记忆）`attacked` `drew` `played` `differentiated` `leveled` `ended` `round` |
| **状态** `state` | `{"state":"level_at_least","arg":"III"}` | 只看此刻，不看基线（重置过也算数） | `beside` `all_dead` `stuck` `level_at_least` `low_energy_beside` `tile_healthy:<q,r>` `cell_at:<seat>:<q,r>` |
| **条目流** `entry` | `{"entry":"e_done"}` | 导演在 `queue.on_step` / `on_log` 旁路上认 | `e_done`（这一轮 E 阶段播完）`roll:<reason>` `fx:<kind>` `skill:<名>` |

- **「玩家净化第一个」（PRD:171）** = `{"delta":"purified"}`。它落在两个 O-玩家 之间（PRD:169 / :177），所以流程天然是「开闸 → 净化一格 → 关闸说一句 → 再开闸」。
- **「玩家前两次攻击」（PRD:275）** = `{"delta":"attacked","count":2}`。
- **不用条目流认这两件**：`result` 条目的文案是引擎给的中文句子，拿它做判据等于把规则抄第二份（`cw_bridge.gd:37-40` 明写「文字由引擎给，表现层不许照着点数自己再判一遍」）。`entry` 那一类只留给「状态量表达不出来」的事。

### 3.4 提示期间禁操作（PRD:51）—— 两层，缺一不可

1. **闸这一层**：非 `player` 条目一律 `allow = []` ⇒ 这一问挂起、行动栏根本不建。
   （S8 的真机血账：第一版没写 `[]`，关首讲解步缺省 = 全开，行动栏当场把「基因表达」亮着建出来，之后翻到操作步**也不会重建** —— 闸是**问的时候**过的。）
2. **点击这一层**：`cw_tutor_chrome.gd` 起一层**真·全屏 `Control`**（`MOUSE_FILTER_STOP`），z 序盖在棋盘与行动栏之上、排在皮与常驻「重置 / 目录」**之下**（那两颗提示期照常可点，PRD:41/43）。
   **不能指望皮自己那层** —— 老 `CWGuide.ZONE := Rect2(88,16,600,200)`（`guide.gd:26`）只有几百像素，盖不住棋盘与右栏。

### 3.5 自动重置（PRD:17/47）与劝重置

- `reset_when` 命中 → `await view.reset_anim()`（PRD:47）→ `stage.reload_world(关首那份)` → **游标回 0** → 活跃格收回关首那一份（`reveal` 加进来的要收掉）→ **epoch += 1**（§3.7）。
- `advise_when` 命中 → **不重置**，只把提示行换成 `advise` 那一句 + 常驻「重置本关」跟着慢闪。（Kevin 09-19 拍板：PRD:251 第二条「所剩能量小于预期」不自动重置。）
- **顺带一道闸**：劝着的时候 `until` 不翻页（第三关 Step1 的 `beside` 在能量算亏时照样成立，翻过去劝退当场消失）。
- 手动「重置」按钮走同一条路，只是不播 `reset_anim`。
- **拆装次序钉死**：`abort → queue.stop → close → dispose`（`cw_tutorial_stage.gd:62-70`、`match.gd:584-593`）。

### 3.6 关切换、章节提示、进度

- **关切换静默**（PRD:37）：`flow` 走完 → `on_done` → 换局。序列照 `match.gd:580-616`：`abort → queue.stop → close → stage.dispose → 重挂皮与导演 → 新 stage.open_level → _start_queue → 关首装闸 → kernel.run → _observe_now`。
  - **adopt 模式的 `close()` 不 dispose**（「谁装配谁收摊」）⇒ 显式 `stage.dispose()`。
  - **换局会新建一个桥** ⇒ 必须把**同一个**导演 / 皮重挂上去，且 `bridge.kernel = kernel` 要在 `_start_queue` 里重指（`match.gd:1100-1106` 的原账：留着旧句柄，`_await_playback` 拿旧 `entry_seq` 等新队列的 `since`，**第二关起一问都到不了界面，而且不报任何警告**）。
  - **换局那一瞬间的脏基线**：两关免疫起点不同格，拿上一关的基线比 `delta:moved` 当场成立 ⇒ 导演在「新镜像刚落地」与「第一个 `step_end`」两处各重取一次基线。
- **先结算界面与状态再出文本**（PRD:39）：由 `flow[0].do == "state"` 的校验 + 导演执行序（`load → ui → reveal → 后续条目`）保证。
- **章节提示**（PRD:35）：关首比对 `(chapter_kind, chapter)` 二元组，变了才 `view.chapter(no, title)`（协程，播完才往下）。
  **间章不弹章节提示**（我方口径，一句话请 Kevin 确认）：PRD:393 要求冲击波「在上一关最后一个癌细胞被杀死时」**原地**起，中间插一屏半透明大字会把这条连贯性打断；而 Kevin 的「间章不是主章节的附属」说的是**结构**（目录里平级单列、不挂在第二章下），不等于要给它一屏章节提示。⇒ 间章静默进入，进第七关时照常弹「第三章 Cancer」。要弹的话是数据一行（`chapter_title: "癌变"` + 打开 banner 开关）。
- **进度存档**（★ **S6 已落地** 2026-09-19）：沿用 `user://guide_progress.cfg`（**PATH / SECTION 不许改**）。键：`done`（主菜单 `main_menu.gd:136` 还在读）、`at: {level, beat}`、`unlocked`、`opening_seen`（**别碰**，归 `tutorial_opening.gd`）。
  ⚠ 写盘一律 `ConfigFile.load` 后 `set_value`（两边各自读改写、互不覆盖，`tutorial_opening.gd:123` 已写明），**整份覆盖会把 `opening_seen` 抹掉、开场每次重播** —— `t_tutor_progress` 的**正面**断言（写完三个键之后 `OPENING.seen()` 仍为真）。
  **断点续读到「关」**，不续到「步」（Q-11）：`at.level` 是**关 id**（不是关下标 —— 下标会随关表增删漂移），`set_at()` 在导演的 `open()`（关首，beat=0）与 `_finish()`（关末）各写一次；`at_level()` 是挑关那一侧的唯一入口（`match.gd:_tutor_pick_level`），**旧档只有 `done` 也能起**（`at` 缺席 ⇒ 空串 ⇒ 退回按 `done` 数挑）。
  **`skipped` 键与 `codex_gated()` 同日退役**（§3.8 去闸），`set_skipped()` 一并删掉 —— 别再加回来。
- **常驻目录**（PRD:43，★ **S6 已落地**）：`cw_tutor_chrome.gd` 的面板，列 `index.json` 的章-关，未通关的灰显不可点、已通关的点了发 `menu_goto` → 皮 → 导演 `goto_level()` → `want_goto` → 调用方换局（**跳关不记「通关」**）。
  **落地时改了两处数**（原文那两个数算不过来，照实记）：
  ① 面板 **480×360**（方案原文的排版上限）居中摆在 960×540 的屏上 ⇒ `MENU_PANEL = Rect2(240, 90, 480, 360)`；
  ② **行高 26 不是 34**：满编是「**3 个章标题 + 6 关 + 1 个间章 = 10 行**」（原文写「7 行数据行 + 4 行标题行」是把间章数了两遍 —— 间章**自己就是一行**，不另插章标题），10 × 34 = 340 再加表头与底部那行就装不下；26 正好（`48 + 10 × 26 = 308 ≤ 316` 页脚横线）。`capacity()` / `row_y()` 是纯函数，`t_tutor_progress` 逐关算一遍 —— **再加关就得先加高面板**。
  ★ **间章在目录里与三个主章节平级单列**（Kevin 09-19）：与章标题**同一个 x**（关行缩进 24），而且它**打断分组** —— 间章之后那一章要重新出一条章标题。
  **底部一行「Cell War」= 重看开场**（Q-21，按钮名就叫片名）：常驻可点（不受「未通关灰显」管），发 `replay_opening` → `match.gd` 调开场脚本现成的 `clear_seen()` → `main.gd` 收摊这一局再重进引导（`_begin_tutorial` 见 `seen()` 为假会重播开场）。
  **页脚右侧「重置教程进度」**（Kevin 2026-09-20，要二次确认）：点了先在同一行换成「清空全部进度并重看开场？」+ 确认 / 取消（「Cell War」暂让位），确认才发 `reset_progress` → `match.gd` 的 `_tutor_reset_progress`：`CWGuideProgress.clear()` 整份清掉（done / at / unlocked / opening_seen）再走上面「重看开场」同一条重进路。壳只问、不读不写存档；驱动口 `press_reset_progress` / `cancel_reset_progress` / `confirm_reset_progress`（没在问时 confirm 是空操作）。
  **首次进入选择（Kevin 2026-09-20 修订）**：`main.gd:_ready` 仅在 Main 是 `current_scene` 且没有 `user://guide_progress.cfg` 时弹出「我是新手 / 进入新手教程」「我是老手 / 直接进入游戏」。前者保存选择并直接 `_begin_tutorial(0)`，后者保存选择、标记 `done=level_count()` 并留在主菜单；已有旧档视为已进入过游戏。教程中途退出后，再启动直接进主菜单，可从「新手引导」手动继续。

### 3.7 钩子接口 `ctx`：九个方法 + 取消语义（★本稿新增，补丙的承重件图纸）

> ✅ **S8（2026-09-19）已实装**：`game/scripts/tutor/cw_tutor_ctx.gd`，九个签名逐字同下。护栏 `t_tutor_hooks`（31 条）盯着它。下文三处标 **实测改判** 的是落地时改过的字。

> 评委 2 的开工前提第 1 条：「`ctx` 九个方法一条签名都没给，而护栏 `t_tutor_hooks` 的判据就是『`ctx.` 后面只许是那九个』—— 九个是哪九个没定义，这条闸写不出来。」本节把它定死。

```gdscript
## game/scripts/tutor/cw_tutor_ctx.gd —— 钩子 → 导演 的唯一接口。
## 纪律：ctx 不暴露 kernel / mirror / game / view / stage 任何原始句柄；钩子文件零成员变量。
## 每个 await 原语返回前都过一次代际闸（见下 alive()）。

## ① 跑一条声明式条目 —— 与 flow[] 完全同构的九个动词（say / point / unlock / play / wait /
##    player / npc / state / hook）。钩子不自己说话、不自己画，一切经这里回到导演。
func beat(row: Dictionary) -> void            ## 协程

## ② 等一个谓词（§3.3 的三类，同一张表、同一个基线）。timeout_secs > 0 时超时返回 false。
func until(pred: Dictionary, timeout_secs := 0.0) -> bool    ## 协程

## ③ 只读查询（白名单，返回派生量的副本，绝不返回镜像本身）：
##    "cells" -> [{seat, at:Vector2i, type, alive, energy}]        "tile" (arg: Vector2i) -> {state, type, solid}
##    "dist"  (arg: [a, b]) -> int                                  "beside" (arg: [seatA, seatB]) -> bool
##    "alive_count" (arg: "immune"|"cancer") -> int                 "round" -> int
##    "energy" (arg: seat) -> int                                   "active" -> [Vector2i]
func read(q: String, arg = null) -> Variant

## ④ 代际闸：这一代还活着吗（重置 / 目录跳关 / 换局后为 false）。
##    **护栏硬要求：钩子里每个 while 的条件都必须含 ctx.alive()**
func alive() -> bool

## ⑤ 让一帧（内含代际闸）
func frame() -> void                          ## 协程

## ⑥ 钩子自己的演出随机数（种子来自数据；**绝不碰内核 rng**）
##    【实测改判 S8】种子具体从哪读：`hook.args.seed`；没写就按**关 id** 定死（`hash(level.id)`）。
func rng() -> RandomNumberGenerator

## ⑦ 钩子唯一合法的状态落点（钩子文件不许有成员变量；重置时随代际一起清空）
func state() -> Dictionary

## ⑧ 记一笔（进无头流水账与开发日志，不上屏）
func log(msg: String) -> void

## ⑨ 剧本写不下去了：warning + 挂起（不静默继续、不替玩家乱答），出路是常驻「重置 / 目录」
##    【实测改判 S8】**钩子里必须写 `await ctx.fail(...)`**：不等它挂住，钩子自己就返回了，
##    主游标会把 `hook` 那一条翻过去 —— 恰好是“静默继续”那一种死法
func fail(why: String) -> void
```

**取消语义（搬乙的 epoch，`match.gd:583/1099/1174` 有先例）**：

```gdscript
## cw_tutor_director.gd
signal dead            ## 永不 emit
var epoch := 0
func invalidate() -> void: epoch += 1      ## 重置 / 目录跳关 / 换局各调一次
## 【实测改判 S8】换局走的就是 `director.open()` —— 它的第一行就是 `invalidate()`，
## 否则上一关挂着的钩子协程会在新关里接着跑。`invalidate()` 顺手清 `ctx.state()`

## cw_tutor_ctx.gd —— 每个 await 原语的结尾统一一句
func _gate() -> void:
    if _ep != director.epoch:
        await director.dead                ## 旧协程停在这里，随导演一起被回收
```
GDScript 的协程不能被杀，只能让它永挂。**风险与对策**：挂死的协程持 ctx / 导演引用 ⇒ ① 导演每关一只、关末显式 `dispose()`（**【实测改判 S8】这一条不成立** —— Godot 4.5 上 `queue_free()` 导演**并不能**把挂死的协程回收干净：20 代约 280 只对象，free 之后只掉 39 只）；② `t_tutor_hooks` 的对象账改成**两轮 churn 对比**：钩子分别跑 3 帧与 12 帧、各做 20 次重置，**两轮涨幅必须一样大**（实测 281 vs 280，约 14 只/代）—— 要钉的性质是「挂死的是**每代一只**、与钩子跑多久无关」，原来那句「不单调上涨」写不出真判别力；推论：**钩子里的 await 原语越少越省**（S10/S11 照这一条）；③ **每个 `while` 条件含 `ctx.alive()`** 的源码闸，让钩子自己从循环里退出来，把「永挂」压到最少的那几个 `await` 上。
（乙的原风险是「挂的是整关主协程」；本稿只有第七关与间章两个钩子会挂，且都被 `ctx.alive()` 的循环闸提前收口 —— 比乙的面小一个量级。）

### 3.8 图鉴：解锁通知留，闸去掉

- PRD 全文只写「图鉴解锁：【X】」（PRD:29/125/131/165/175/279/321/347/451/497），**一句「没解锁就看不到」都没有**。三家一致建议去闸，采纳。
- 落法（★ **S6 已落地** 2026-09-19）：`unlock` 条目落盘（`CWGuideProgress.unlock()` 的集合语义原样可用）+ 导演发 `codex_unlocked(ids)`（**通知小卡的画法归皮 A / S3**）+ 图鉴里那一条标题**慢闪一轮**（`_fresh` / `_glow` 那套一个字没动）；`cw_codex.gd` 的 `_refresh_unlocked()` 里那句 `_gate = _unlocked if codex_gated() else null` 已改成**恒 `null`**（那一行就是闸的全部开关），`codex_gated()` / `set_skipped()` / `skipped` 键**已删**。
- **通知小卡上写什么**（S6 定）：`codex_map.json` 新增 `names` 段（解锁点 → PRD 那个【X】），取法 `CWCodex.unlock_name(point)` / `unlock_names(points)`（**按次序去重**）。写的是【攻击】而不是两个条目标题 —— 【攻击】一条落到「怎么打」「攻击骰」两条上，拿条目标题拼会当场多出一行。
- **`_mark_locked`（`cw_codex.gd:244`）与 `chapters(unlocked)` / `search(query, unlocked)` 的可选参数留着不删**（丙的口径，比甲乙的「一起删」便宜）：老判据 `t_codex` 的 16 条靠它们，删了要连带改判；留着是死代码，将来要闸就是一行打开。
- **`codex_map.json` 留**（解锁点 → 条目 id 的归宿，剧本 `unlock` 写的 id 要有落点），**已按剧本 03:41 版重写**：12 个解锁点落到 9 个条目上，三处不是一一对应（净化 / 抗原记忆 / 免疫等级共用一条；攻击一对二；压迫 / 增生 / 侵蚀共用一条）—— **照实登记，不为了凑一一对应去拆图鉴条目**（→ Q-20 给 hxr 过目）。行号跟着 03:41 版走（压迫三条 451 → **455**、固化癌组织 497 → **501**），第七关全文改称**第六关**。

---

## 4. 特殊关逐条落点

> ⚠ **PRD 行号基线（2026-09-19 04:08 版，532 行）**：hxr 当天 04:08 又推了一版，给模板加了镜头一族（PRD:9-22 的「地图调中 / 左 / 右」「玩家调中 / 左 / 右」）并在各关「界面变化」里各插一行，于是**第一关起所有行号整体下移**（第二关 139→149、第三关 223→239、第四关 287→305…）。S4 落地的 `c1_l2` / `c1_l3` 已按新基线写 `prd`；下表与 §2.7-2.9 的行号是旧基线，**下一次通读时整批重编**，对账闸（判据 ⑬「逐关覆盖 PRD 的编号行」）也等那一次一起实现。新字段 `ui.camera = { anchor: "map"|"player", align: "center"|"left"|"right" }`（缺省 map/center）已进 `cw_tutor_layers` 的层白名单（第 12 层），**实装在 S3**。

> 口径：**走内核规则** = 引擎真跑；**重装** = 换一份 world；**演出层** = 纯表现，引擎不知道；**旋钮** = `worlds.*.tuning`；**数据** = 盘面预设计。
> **`game/scripts/core/**` 需要的改动：零。** 非 core 的改动只有 §1.2② 的两个文件约 8 行。
> 下表的落点是**甲与丙两份独立稿逐条撞上同一答案**的部分（评委 2：「这张表可以当定论用」），加上乙独家的 F5。

| PRD | 要什么 | 落点 | 依据 |
|---|---|---|---|
| 105/149/195 | 第一、二关【迁移】不消耗能量 | **数据**：大能量 99990 | `immune_move_*` 都是 **tier C**（`contract_tune.json`），装载器双重拒 |
| 107/151/197 | 不显示路径规划 / 能量消耗 | **UI 层**：`move_path:false` / `cost:false` | 五个破口改指 `cw_tutor_layers`（§1.2③） |
| 187-199 | 第二关 Step2 延伸一格 + 1 能量癌细胞 | **预置 + reveal**（零重装，玩家净化过的两格留住） | `match.gd:1926-1928` 的活跃格遮罩已在 |
| 199 | 免疫细胞下次攻击结果为成功 | **带子** `[[1,6,3]]` | 判定档 `r==6` 大成功 / `r<=2` 失效 / 3~5 成功（`cw_actions.gd:726-730`） |
| 259-261 | 第三关能量精确 | **数据** `energy: 66`（v4；v3 的 61 是 `(3,0)(4,0)(5,0)` 变癌之前的账） | 逐项账见样例 B；`t_tutor_energy_formula` **用引擎现算复核**，差一分当场红 |
| 239 | 第三关三次骰子 | **带子** `[[1,6,3],[1,6,1],[1,6,6]]` | `ATTACK_MAX_PER_TURN := 3`（`cw_data.gd:376`）正好锁死带子长度：打不出第四次 ⇒ 永不 overrun |
| 251 | 第三关两条自动重置 | 第一条 `reset_when: stuck`；第二条 **劝重置** `advise_when` | Kevin 09-19 拍板 |
| 301/369 | 无限能量、显示 ∞ | **数据** 99990 + **UI 层** `energy:"infinite"`（**显示判据比 `INFINITE_MIN = 90000` 那条带，不比 99990 那一个数**，实测改判 S5，理由见 §3.2(b)）；**凡跑 E 阶段的关另加 `overload_div: 0`** | 【能量过载】`overload_loss`（`cw_world.gd:458-462`）会把 99990 每回合啃掉 15.0 **并写日志到 CWFeed**；`overload_div` 是 **tier A**，`div <= 0` 整条关掉。（第四 / 五关不点结束回合 ⇒ 可不写；**第七关必写**） |
| 303 | 第四关不设攻击次数上限 | **旋钮** `attack_max_per_turn: 0`（tier A）。★ **第五关也要写**（S5 实测；**Kevin 2026-09-19 追认**） | 引擎判的是 `if cap > 0`。⚠ 实名是 `attack_max_per_turn`，不是 `attacks_per_turn`。★ `cell.attacks_used` 只在 `cw_turn` 的回合开始清零，而第一～五关**永不点结束回合** ⇒ 它一辈子不清零；第五关不拧这一档，玩家打满 3 次就再也攻击不了，「把全部癌细胞杀死」当场变成死局。**Kevin 2026-09-19 追认，行为不变**；⚠ 剧本正本（09-19 06:32 的 534 行版）里这一条**仍只写在第四关** ——现文 PRD:325「玩家本关不设攻击次数上限」，第一章另有章节设定 PRD:99「本章不设回合/攻击次数上限」，第五关 PRD:351-405 通篇没有这一句。**第一章三关 2026-09-19 晚补拧**（Kevin「看一下现在的 PRD，在第一章这里加了描述」）：`c1_l1` / `c1_l2` / `c1_l3` 的 `base` 世界各加 `tuning.attack_max_per_turn: 0`，`t_tutor_c1` 三条断言；「回合上限」不拧 —— `limit_round` 是 tier C（关卡数据不许动），而第一～三关永不点结束回合、世界回合停在 1，`cw_world.gd:76` 那条终局到不了 |
| 307 | 免疫等级升到 III | **数据**：席位数 + 起始 `memory` | `LEVEL_MIN_MEMORY` 不在旋钮里；表里只有 4 人一档，**`seats != 4` 一律回落六人档**（`cw_data.gd:260/272`；Kevin 09-19：两关一律六人档，判据钉 `seats != 4`） |
| 355 | 第五关切换种类按钮 | **UI 层 `switch_type`（值 = 一组 world 名 `["b","t","macro","dc"]`）+ 关内 `load`**。**已实装 S5**：按钮在常驻壳（`cw_tutor_chrome.set_switch`，**懒建**），显隐跟着其余 ui 层走 `match._sync_tutor_layers` 每帧全量刷（**不占一条导演 → 皮的意图** —— 加了第十类意图会把 `t_tutor_flow` / `t_tutor_view` 的序列断言打红）；按下走 `chrome.switch_pressed → view.switch_type_pressed → director.switch_type()` → `want_load`，轮转下标随代际闸清 | 分化在规则里是一次性的；就地改 `itype` = 绕开规则往引擎状态写字。**Step2 那次重装保留 Step1 挑的那一种**（Kevin 2026-09-19「不接受」摆回 B 细胞）：`state.load` 写成 `{by_player_type: {BCell: b, TCell: t, Macrophage: macro, Dendritic: dc}}`，导演按镜像里玩家那只的种类现挑（§2.6），四份 world 一个字没改；「切换种类」的轮转下标随之对到装上的那一份 ⇒ 按一下是「从现在这种往下一种」 |
| 361 | 第五关 Step2 癌块扩大 | **关内 `load`**（全案三处之一） | 改的是已露出的格，遮罩揭不了 |
| 365/367 | 固化癌组织 + 各种类免疫各一 | **数据**：`state:"solid"`（纪律 9）+ 逐只一席 ⇒ **9 席**。★ **Step1 那四只必须是未分化的 `ImmuneBasic`**（S5 实测） | **右栏实测：让掉回合块那 62px 之后 9 席底边 532 ≤ 540，10 席 576 放不下。写死上限，别再往上加**（`CWMatchPanel.level_bottom()` 是纯函数，`t_tutor_c2` 两头都钉）。★ `_diff_choices()` 按 `game.differentiated` 过滤，而那张表由「`differentiated == true` 且 itype ≠ BASIC 的细胞」现算：Step1 就摆上四种已分化免疫的话四种全被占、玩家一个【分化】选项都没有（PRD:387 本来也把这四只写在 **Step2 的「游戏状态变化」**里）。代价：玩家挑的那一种必然与某一只 NPC 撞种（**Kevin 2026-09-19：可以撞种**，不改） |
| **间章** 387 | 所有 UI 消失 | UI 层 `{"*": false}` | 一条搞定 |
| 393 | 暗黑像素冲击波 | **演出层**（`cw_tutor_fx.shockwave`）。**S9b 已接线**：`{"do":"play","fx":"shockwave","at":"player","await":true}` | 规则里没有这回事 |
| 395 | 等待几秒 | `{"do":"wait","secs":2.0}` | Q-04 |
| **395-397** | 镜头居中玩家 + 地图向四周延伸、补齐缺格使玩家处于**完整棋盘的中央格** | **UI 层 + 关内 `load`**（★ Kevin 2026-09-19 拍板「世界重心平移」，盘面提案 §6.3）：一条 `{"do":"state","ui":{"camera":{"anchor":"player","align":"center"}},"load":{"recenter":"player","radius":11}}` 就够 —— `ui` 那一层排在 `load` 前面，所以重装前镜头已经盯着玩家，平移后他仍在屏幕正中、老格相对位置一格没换 ⇒ **画面不跳**，只有新格浮现 | 格网 `CWBoard.ensure_radius`（按镜像半径长、只加不重铺，正式局零变化）；拆装 `CWTutorialStage.reload_recentered`（关内换盘四步，**不是跨关完整换局**）；半径 11 = §7.4 里 T 细胞平移后的 `(-11,1)` 恰好落在真外环。⚙ 11 格特殊组织要显式钉 `type` 才跟着搬（`CWData.special_of` 是绝对坐标表） |
| 397/405/439/475 | 文字提示「……」 | `say`（`who:"narrator"`） | Q-04：建议就是留白本身 |
| 399 | 像素错误 + 分化后转回普通免疫 | **纯演出层**（S9b 改判）：`glitch` 的 `morph_to: "ImmuneBasic"`，而且这一段**一直演到分镜 6 的 glitch 接手**（`args.secs` 长过中间那两条 `say`，`begin()` 里 `clear()` → `_prepare()` 同帧换手，真节点一帧都没露出来）。原计划的「关内 `load`」作废 —— 那一刻的盘面是第五关的活局面、写不死，要真改引擎里那只的 `type` 就得新造一种「就地改一只细胞」的机制，代价大得多。**引擎里玩家仍是他分化后的那一种**，要不要做成真退回，见开发日志那条「还要 Kevin / hxr 的一件」 | 分化状态在细胞上 |
| **403** | 转为 Null 能量的小细胞肺癌（**阵营翻转**） | ★ **整份重装，且必须走「完整换局」那条路、不是 `reload_world`** | 席位 order 在 `g.init(order, 1)` 时定死（`cw_world_loader.gd:142`）；而 `reload_world` 是四步拆装的**短路版**，注释原文「跳过算关 / 换席位 / 重挂面板三段」「这里不重挂引导面板」（`cw_tutorial_stage.gd:56-72`）。**这是间章最容易踩的一脚，甲丙都漏了，乙独家抓到（评委 1 的 F5）**。判据：翻转后 `player_count` / `human_players` / 右栏面板真的重挂过 |
| 407 | 周围免疫弹文字 | `{"do":"say","who":"seat:<n>"}` | 表现接口 |
| 409 | 最近一个免疫移过来攻击三次 | **走内核规则**（NPC `approach` + 三次攻击）+ **带子** `[[1,6,3]]×3` 全钉成功。**S9b 实装补两脚**：① 行动权靠 `CWTutorialStage._point_cursor` 把 `flow["i"]` 对到 `seat` 那一席上（cwxworld/3 的 `seat` 只写进 `current_pid`，不补这一脚永远是席 0 先行）；② `proliferate_per_adjacent[1]` / `proliferate_per_solid[1]` **必须拧 0** —— 巨噬打完会结束回合、后面三只免疫跟着各结束一次，E 阶段真的会跑一次，【增生】按合格健康格逐格掷骰（实测 18 次）会把三格带子当场冲了 | 玩家是大能量 ⇒ 打不死 |
| 411 | 脚下生固化 + 一环免疫外推 1 格 | **关内 `load` + 受击特效**（S9b：钩子 `erupt` 先记下「谁从哪被推到哪」再换盘，换完逐只补 `knockback`） | 规则里没有「击退」（`grep 击退 game/scripts/core/*.gd` 零命中）。差分演出走 `CWTeleportFx` 先例：引擎零改动、UI 自己差分认出来（`teleport_fx.gd:8-9`） |
| **第七关** 429 | 强制演出，只许点 UI 提示的 | **闸**：非 `player` 条目 `allow:[]`，`player` 条目只放点名那一条 + 全屏 STOP 留洞 | §3.2/3.4 |
| 431 | 能量 Null、内部无限 | **数据** 99990 + `energy:"null"` + `overload_div:0` | 复活后引擎给 2.0（`REVIVE_ENERGY := 20`，`cw_data.gd:368`）⇒ 复活那一步紧跟一份重装拨回（Q-12） |
| 433 | 锁定迁移模式、六向只许一个方向 | **UI 层 `move_path:false`** + **闸**（`allow` 写死 `to=<那一格>`） | 两件事分两层，别混 |
| 443 | 围一圈癌组织 | **钩子 `encircle`**（运行期算下一格）+ 走内核（玩家自己迁移，迁到健康格会癌化） | 数据表达不了 |
| 445/447 | 点结束回合 + 按钮弹提示 | `point mode:"fullscreen"` + `tip` + `allow:["k=action\|act=end"]` | |
| 449 | 正常结算压迫 / 增生 / 侵蚀 | **压迫真结算**（不掷骰、必然生效）；**增生拧 0**（`proliferate_per_adjacent[1]` / `proliferate_per_solid[1]`，**tier A′**，下标 1 基，引擎在掷骰之前早退 ⇒ 零 rng）再用**演出层补可见范围内的转化**；**侵蚀承认打不到**（只吃「不与外缘连通的健康连通块」，`erosion_tiles` 是 tier C），图鉴照解锁、演出层补 | 半径 6 下真结算要对每个合格健康格各掷一次骰，带子上百条且多数在遮罩外 |
| 453 | 免疫靠近 / 邻接则攻击 | **NPC 脚本**（`approach` / `attack_if_adjacent`，`cw_tutorial_npc.gd:31`）+ 钩子 `immune_turn` | 零新代码 |
| 455 | B 细胞三次抗体、无视邻接限制 | 次数：`npc.plan` 点三次 + `antibody_max_per_round`（tier A）；**无视限制：盘面保证邻接**（目标集合写死在规则里，没有旋钮） | PRD:57「地图全部预设计」给了这个自由度 |
| 457 | 巨噬净化动画 | **走内核规则** | 一行不写 |
| 459 | 重复 3-5（按 3-7 读）直到剩最后一个 T | **钩子 `repeat_until_last_t`**（`while ctx.alive() and ctx.read("alive_count","immune") > 1`） | 终止条件是运行期的 |
| 461 | T 细胞站位远且在一条直线上 | **数据**：`r=-1` 排，起点距离 9 | 见样例 C |
| 463/501 | 效应应答「一直持续」/ 多只齐发 | **纯演出层** | 规则是每细胞每局 1 次 + 免疫方每世界回合 1 次 |
| 465/483 | 效应应答特效命中不贯穿 / 始终止于癌细胞 | **教程自己的 fx 变体（`cw_tutor_fx`），不动公共 `beam_fx.gd`** | 乙要改共享特效，那文件真人对局也在用，回归面会溢出教程之外。丙的做法代价更小，采纳 |
| 469/473 | 击退两格 + 受击特效 | **关内 `load` + 演出层** | 同 411 |
| 477/479 | 显示技能按钮 + 弹提示 | `ui.skill_bar:true` + `point ui:["skill:转移"]` + `tip` | |
| 481 | 【转移】若干次正好到相邻格 | **几何 + 闸**：起点距离 9 → 两轮净 +1×2 → 11 = 5×2+1 → 两跳落相邻 | `METASTASIS_RANGE := 5`（`cw_data.gd:341`）；**5k 会落到 T 头上 = 非法**。`metastasis_max_per_round` / `metastasis_cost` 都是 tier A，费用已被大能量盖住 |
| 485 | T 细胞释放细胞毒素 | **走真技能 + 钉带子**（默认；会造坏死格 `NECROSIS_TOXIN := 2`，`cw_data.gd:465`，影响后面每一份重装盘面） | Q-13 |
| 487-489 | 像素错误随机切换、最终定格印戒细胞癌 | **演出层**（随机走自带 rng）+ **关内 `load`**（癌种在 `players[]`） | |
| 491/493 | 【黏液破裂】 | **走真技能 + 钉带子** | 随机转化最多 10 格（`MUCUS_MAX_CONVERT := 10`，`cw_data.gd:321`），不钉带子复活点与结局画面不可预期 |
| 495/497 | 固化癌组织上复活 + 解锁【固化癌组织】 | **走内核规则**（复活问）+ 紧跟一份重装拨能量。⚠ **死亡窗口内盘上至少一格 `state:"solid"` 且不被免疫占据** —— 数据硬断言 | 自毁到下一个 S 阶段复活之间隔着一次 E，那一刻 `living_cells(CANCER)` 为空，第一道闸（`cw_game.gd:1085`）过不住，只剩固化格兜底（`:1092-1095`）。**Kevin 09-12 截图报过的「教程过完直接弹结算」就是这条路径** |
| 499 | 地图边缘再生 T / B 细胞 | **预置 + `reveal`**（不是重装） | 席位与细胞开局就在盘上、停在活跃格外；`hex_at` 只扫活跃集 ⇒ 看不见也点不到。**第七关会结束回合**，所以这些席位必须是脚本 decider 管的 |
| 503 | 癌细胞死亡 | **走内核规则**（最后一次致死） | 之后接什么 PRD 没写 → Q-14 |
| 421 | 不显示第 X 回合 | **只隐藏、照常推进** | **留够余量**：I 期 = 第 1~5 回合 ⇒ `round: 1` 起、世界回合 ≤ 5 就停在 I 期，增生 / 侵蚀 / 固化的分档下标不漂 |
| — | 免疫胜利不能弹 | **数据**：场上有活癌（玩家自己）⇒ `check_immune_win` 第一行 return（`cw_game.gd:1085`） | |
| — | 癌方加权胜利不能弹 | **旋钮** `cancer_win_hold_rounds: 99`（tier A） | 要连续 N 回合达标才判（`cw_game.gd:1112-1116`） |
| — | 【根深蒂固】固化扩散 | **带子只能录**（`game/tests/record_level_rolls.gd` 无头录制；S10 改字：`--script` 只认 `res://`，仓库根的 `tools/` 进不去。**第六关实测零消耗** —— 本条只在癌 II/III 期成立，第六关世界回合 ≤ 5 恒 I 期） | 每个有癌邻格的固化格各 `pick_random` 若干次（`cw_world.gd:878-920`），**拧不掉**（第七关必须有固化格）。验收 = 带子**双向归零** |
| — | `limit_round` 兜底 | 是 15 且 **tier C**（拧不动，正好不需要） | 第一～五关零个世界回合；第七关 2~3 轮 |

**NPC 三级兜底**（`cw_tutorial_npc.gd:55-66`，第七关的命门）：① 选项里 `data.stop` / `data.skip` 的第一条；② 顶层 action 问 ⇒ 选 `act=end`「结束回合」= 什么都不做；③ 都没有才下标 0。**不逐席装 decider 的话**，非人类席会走 `CWUIBridge.ask` 的 AI 分支，而 PRD 通用规则 11 写着「无 ai 控制」。

### 4.1 第六关 25 步 · **as-built**（S11，2026-09-19；行号 = PRD `Cell_War_新手引导PRD_hxr.md` 现文）

上表那几行第六关写的是 09-18「第七关」那版的行号（443/445/449/…），**已经作废**；实装以下表为准，
对账闸在 `t_tutor_c3` 判据 ⑩（25 个编号行逐条覆盖 + `prd` 单调不减）。`flow` 共 **37 条**（S11 的 35 条 + 09-24 两条镜头；关首那条钉 441）。

| 步 | PRD | 落法 |
|---|---|---|
| — | 441-457 | 关首一条 `state`：`load: base` + 11 层 UI（侧边栏 / 结束回合开、`round_no` 关、`skill_bar` 关、`move_path` / `cost` 关、`energy: "null"`）+ **镜头 `{anchor: player, align: right}`、不改缩放**（主线程口径 ①） |
| 1 | 463 | `say` `who: narrator`，`lines: ["……"]` |
| 2 | 465 | `point` `hex: ["0,0"]` soft（O-玩家 = 开操作闸那一拍） |
| 3 | 467 | **钩子 `encircle`**：关首那一轮先朝巨噬走一格，再挑它六邻里「还是健康 + 没人站 + 与玩家相邻」的第一格（DIRS 序 ⇒ 正好是 6 步走法），`point` + `allow` 只放它，玩家走上去内核自己【定殖】；重复那几轮（09-24）只围**挨着玩家**的那只、从 (-2,1) 出发绕一圈**回到 (-2,1)**（出发格留到最后一步），没挨着的就不走 |
| 4 | 469/471 | `point` fullscreen + `tip:"点击结算【微环境压迫】"`；`player` `allow: ["k=action\|act=end"]`，**同一条也写 `mode` / `tip`**（见下「改判 ②」） |
| 5 | 473 | `wait 2.0` —— 压迫 / 增生 / 侵蚀走**真 E 阶段**（增生两档已在 S10 拧 0、侵蚀这盘打不到） |
| 6 | 475 | `unlock ["pressure","proliferate","erosion"]` |
| 7 | 477-481 | **钩子 `immune_turn`**：逐只活着的免疫喂一份 `npc.plan`（巨噬 `approach`+`end_turn`；**B / 树突走写死路线** `k=action\|act=move\|to=…`（09-24）：树突第 1 回合四格到 (-2,2)，B 第 1 回合到 (-4,0) + **三条 `k=action\|act=antibody`**、第 2 回合两格进死巨噬那格 (-2,0)，之后 `attack_if_adjacent`；T `end_turn` = 全程不动），再按镜像的**回合号**等免疫回合真的走完（`ctx.until({"delta":"round"})` 在内核同步走完时永远等不到、有掷骰演出时又会提前醒，09-24 下午改）。巨噬净化**一个字都不写**，走内核动画 |
| 8 | 483 | **钩子 `repeat_until_last_t`**：`while ctx.alive() and n < 3 and ctx.read("alive_count","immune") > 1` 里重跑 3、4、7（`encircle` 只围挨着玩家的那只、从 (-2,1) 出发绕回 (-2,1)；没挨着的那一轮只结束回合）。**真收得了口靠数据**（09-24 Kevin「第六关无法结束」）：base 有氧六旋钮 0 + `immune_respawn_delay 99` + 巨噬 1.0 / B 7.5 / 树突 2.5 ⇒ 免疫自己走到身边、围一圈下一次结算压迫 1.5 就死（巨噬第 1 回合、树突第 2、B 第 3；`t_tutor_c3_drive` 整关无头钉着）。收口时玩家就站在 (-2,1)（Kevin 09-24「走完最后一步正好回到起点，然后 T 细胞放大招」；上午版多出的那段「走回起点」删了）。封顶 3 轮仍有免疫 / 玩家不在 (-2,1) **不 fail**，装 `pressed`（knock1 盘面 + 玩家回 (-2,1)）纠偏 |
| 9 | 487/489 | `play beam_hit`，`args.loop: true`、`args.target: 0`（**写席位**，导演的 `seat_at` 解析 ⇒ 随玩家位置更新）。命中不贯穿 = 教程自己的变体，`beam_fx.gd` 一个字不动。**09-24 起导演把 `args.from` / `to` / `target` 也翻成坐标 / 席位**：此前 `from: "-11,1"` 字符串原样到演出库、`_coord` 给盘心 ⇒ 光束画在 (0,0) 长度为零。**09-25 Kevin「由于比例问题看不到屏幕外的 T」⇒ T 从 (-11,1) 挪到 (-6,1)**（第 6 环，关首机位 x≈214 整只在画面里；间章 flip 同挪），光束从 T 本体打到玩家。**09-25 第二条：loop 光束走对局壳的第二支演出库**（单槽的 `begin` 先 `clear`，此前第 11 步击退一开演光束就没了），击退飞行中端点跟替身，第 18 步不 loop 的那一发把它收掉 |
| 10-13 | 491-497 | `player`（`allow` 只放下一格）→ `play knockback` → `state.load: knock1` / `knock2`（两轮「前进 1 击退 2」：(-2,1)→(-3,1)→(-1,1)→(-2,1)→(0,1)）；knock1 烘着第 10 步前的整份盘面（12 格癌组织 + 5 格固化），重装前后逐格相同（09-24）；两次 `knockback` 的 from / to 也经导演翻坐标，并带 `actor: player`（替身飞的时候真身让位；紧接着重装钉真身时对局壳不再演传送，否则替身飞完真身又溶解一次 —— 09-24 复核） |
| 14 | 499 | `say narrator ["……"]` |
| 15 | 501 | `state` `ui: {skill_bar: true}` |
| 16/17 | 503/505 | `point ui:["bar:转移"]` + tip；**一条** `player`，`allow` 放一跳（`k=action\|act=jump\|to=-5,1`，(0,1)→(-5,1) 正好落在 T (-6,1) 面前；09-25 前 T 在 (-11,1) 要两跳 + 09-24 加的一条 `state.ui.camera {player, right}` 才把第二跳落点带进镜头 —— T 挪近之后整关一屏装得下，那条镜头与第二跳都删了）。PRD:507「始终止于癌细胞位置」= 再一条 `play beam_hit` loop + `target: 0`；`t_tutor_c3_ui` 真按栏点格钉着 |
| 18 | 509 | `play beam_hit` **不带 loop** = 「停」（播完即收）。【细胞毒素】见「改判 ③」 |
| 19 | 511/513 | `play glitch` heavy + `shuffle` + `morph_to: SignetRing` + `pool`（免疫 / 癌各几种）→ `state.load: signet` |
| 20/21 | 515/517 | `point ui:["bar:黏液破裂"]` + tip；`player allow: ["k=action\|act=mucus"]`（**走内核真技能**，自毁）+ `play shockwave radius 2` |
| 22 | 519/521 | `player allow: ["k=revive\|to=-5,1"]` —— **就地**复活（09-25 Kevin「把后续传送回原点的动画删了」；此前一条 `state.ui.camera {map, center}` + 复活回 (0,0)）。引擎的复活落点 = 固化格 + 它的 1 环，(-5,1) 旁边本来没有固化格 ⇒ `signet` 把 **(-4,1) 烘成固化**当依托（选项「复活于 (-5,1)（碎掉固化癌组织 (-4,1)）」，`t_tutor_c3` ⑰ 逐字核）+ `unlock ["tissue_solid"]` |
| 23 | 523 | `state.load: revived` —— 再生 T/B/T（复用已死的 1/2/3 席）**并把能量拨回哨兵 99990**。**09-25 起三只摆在终局机位一屏之内**（Kevin「由于比例问题看不到屏幕外的 T」）：T (-1,-3) / B (-9,5) / T (-5,5)，各离玩家 4 格、脚下一环压迫为 0、三只 T 各在玩家的一条六向直线上；黏液破裂之后的 2 环 19 格（标记 + 转化的 10 格，rolls 空 ⇒ 缺省 rng 固定）与碎掉的 (-4,1) 都烘进 `revived`，重装不闪回（`t_tutor_c3_drive` 对账）；T (-6,1) 写 1.0（活局 0.5 + 0.5：它脚下被黏液染成癌组织、一环压迫 0.5，不多给就死在齐射中途）；`seat: 2` 把行动权交给 B；`round: 5` = 活局此刻的回合（黏液那一轮的 E 已翻到 5，写 4 会倒拨、round 4 的结算再跑一遍 —— 09-25 复核） |
| 24 | 525 | `npc` 给 B 三条抗体（4.0 能量正好三发；内核真技能，B 一动手就发 —— **这条排在 `load: revived` 之前**（prd 523）：重装一跑 B 当帧就决策，登记晚一拍读到的还是围杀那份 plan 的尾巴、一发都不出，真机抓到）+ `play beam_hit`（**`await: true`**，09-25：像素错误要等三条光束播完；演出库真机喂时间一帧封顶 1/20 s，那一帧的卡顿吞不掉发射那一相）（`args.from` 写**三只 T 的格**的数组 = 齐射，含原 T (-6,1)；09-24 起演出库逐发点各画一条） |
| 25 | 527 | `play glitch`（像素错误）→ **`play death`**（09-25 Kevin「再加上一个死亡的动画」：演出库第七种，`actor: player`、1.3 s、`await`，闪白 → 抖 → 印戒碎成像素块四散淡没；收尾后真身不还回来，也不装「已死」盘面 —— 那会让内核在停顿里接着跑 E 阶段压死 T）；`on_done: ""` = 全部通关 ⇒ `CWMatch.tutorial_done` → `main._back_to_menu()`（Q-14 的「回主菜单」09-25 才真接上：此前只记一笔进度，画面停在最后一拍 —— Kevin「最后卡在了这里」）。停顿 2 s 的计时随树暂停停（暂停菜单开着到点返场会把菜单淡没、树却停着 = 冻屏），到点核 `_loop_id`（拆局 / 重置）与 `_tutor_done_gen`（目录跳关；承接活局那一支不动 `_loop_id`，停顿里跳去间章不能被拉回主菜单）—— 09-25 复核，`t_tutor_done_menu` 钉三件 |

**S11 的四条改判**（① ② 已由 Kevin 2026-09-19 拍成**定案**：都走演出，T 不给行动回合、癌细胞不真死）

1. **`play` 的键只写数据、不接实现**：`play` 分支的实现是 S9b 的活（方案 §2.6 的 `fx/at/secs/args/seed/await`）。本片写的条目形状对、`fx` 名全在 `cw_tutor_fx.KINDS` 里、`prd` 单调，「真的播了」那一层等 S9b 合并后由主线程补。导演的 `play` 分支一个字没动。
2. **`player` 也许 `mode` / `tip`**（`cw_tutor_beats.VERBS`）。导演的 `_enter_player` 本来就读这两个，只是键白名单里没有 —— 结果紧跟在 `point` 后面的 `player` 会把上一条的提亮**覆写成默认 soft + 空 tip**，第 4 步的全屏提示与按钮上那颗小气泡当场消失（09-19 真机抓到，第 ② 帧）。
3. **第 18 步【细胞毒素】落成演出 + 盘面账**：`CWData.ring` 按本局半径算之后（main 2fc632a）T 站 (-11,1) 取得到目标了，`t_tutor_c3` ⑯ 正面钉住「玩家一跳落到 (-5,1)（09-25 前两跳到 (-10,1)）被【定殖】染成癌组织 ⇒ 那格就是唯一目标」。但**第 18 步仍在玩家的行动回合里**，T 要真放技能得等到它自己的回合 —— 本片按演出落（`play beam_hit` 收尾），真技能留给盘面账（→ 给 Kevin 的问题 ①）。
4. **第 25 步「癌细胞死亡」落成演出**：复活之后玩家能量被拨回哨兵 99990，免疫怎么打都打不死（PRD:455 的 Null 与 PRD:527 的死亡互相打架）。本片按 `play glitch` 收尾 + `on_done: ""`（→ 给 Kevin 的问题 ②）。

**两处引擎侧的小改（都带「正式局一字不变」的判据）**

- `CWUIBridge.hides_dead_acts()`（新虚函数，基类恒 `false`）+ `CWTutorGate` 覆写成「`allow` 非空时为真」：`_ask_action` 里那一行据此**跳过没有选项的行动种类**。不加的话行动栏是从 `mirror.action_kinds_of` 建的整份种类表、缺选项的只**置灰** —— 第六关第 3 步只许【移动】，栏上却同时亮着【突变】【转移】（09-19 真机第一版）。PRD:453 的原话是「仅可点击 UI 提示的部分」。
- `CWBoard.set_active_tiles` 自己先 `ensure_radius(活跃集最大环号)`：`CWMatch._open_tutor_level` 是「`set_active_tiles` 在前、第一次 `_adopt_mirror`（那里才 `ensure_radius`）在后」，第 7 环起的格那一刻还不在 `map` 里、被整批滤掉 ⇒ 第六关 469 格的盘只露出中间 127 格，玩家走到 (-10,1) 时脚下一片黑（09-19 真机第 ④ 帧抓到）。正式局活跃集恒在半径 6 内 ⇒ 第一行就返回。

---

**内核要的钩子：零。** 全部落在（数据 | 旋钮 | 重装 | 演出层 | 钩子）五类里。若 hxr 坚持「击退必须走规则」或「效应应答必须真的连发」，那才需要动 `core/` —— 到时候单列一条评审，不在本方案里。

---

## 5. 表现接口（两版皮都能接）

### 5.1 基类签名（丙的九个方法 + 甲的 `mode` + 一条 `shell`）

```gdscript
## game/scripts/tutor/cw_tutor_view.gd —— 导演 → 皮 的唯一接口。导演只发意图，一个控件名都不认识。
## 基类**给默认实现**：chapter / point / clear_point / block / reset_anim / reveal 六个默认转调
## 两个共用件（cw_tutor_chrome.gd / cw_tutor_spot.gd）。理由：通用规则 1/4/5/7/8/9 与「说话的样子」
## 无关，两皮各抄一份必然漂移。皮通常只覆写 say / hint / codex_unlocked 三个。
class_name CWTutorView          ## 例外：真机截图要 screenshot.gd 的 call:类名:方法 驱动
extends Control

signal advance_pressed          ## 玩家点「继续」（只有 say 且 auto:false 时导演才理）
signal reset_pressed            ## 常驻壳
signal menu_goto(level_id: String)
signal switch_type_pressed

## ① 说台词。who: "player" | "seat:<n>" | "narrator" | "ui:<控件 id>"
##    opts: { beats:int, auto:bool, at:Vector2i }   **协程**：播完才返回（期间导演已把闸关死）
func say(who: String, lines: PackedStringArray, opts: Dictionary) -> void
func busy() -> bool                                  ## 这一段还在念吗

## ② 高亮。targets 每条形如
##    { "kind":"ui",  "id":"bar:迁移" | "panel:end" | "panel:level" | "hand" | "skill:转移" }
##    { "kind":"hex", "at":Vector2i }
##    mode: "soft"（默认 = 通用规则 8 的轻微慢闪）| "arrow" | "fullscreen"（PRD:445 全屏引导指向）
##    tip: 挂在目标上的一句话（PRD:447/479/491），空串 = 不挂
func point(targets: Array, mode := "soft", tip := "") -> void
func clear_point() -> void

func chapter(no: int, title: String) -> void         ## ③ 章节全屏半透明提示（PRD:35）**协程**
func codex_unlocked(ids: PackedStringArray) -> void  ## ④ 图鉴解锁通知（PRD:29 的 12 处）
func block(on: bool) -> void                         ## ⑤ 禁操作层（PRD:51 第 2 层，排在常驻按钮之下）
func reset_anim() -> void                            ## ⑥ 自动重置动画提示（PRD:47）**协程**
func reveal(coords: Array) -> void                   ## ⑦ 地图浮现（PRD:45）按 ring_delays 错峰 **协程**
func hint(text: String) -> void                      ## ⑧ 行动提示行
func urge_reset(on: bool) -> void                    ##    劝重置（§3.5）
func shell(state: Dictionary) -> void                ## ⑨ 常驻壳：{chapter, level, menu:[{id,title,unlocked}], can_reset}
func teardown() -> void
```

### 5.2 四个实现（原三个 + ★占位皮）

| 皮 | 文件 | 说明 |
|---|---|---|
| **A 贴身气泡** | `cw_tutor_view_bubble.gd` | `say` 把气泡挂在说话者那一格上方：`CWView.board_to_screen(m.camera, board.tile_center(c))`（老 `guide_spotlight.gd:149` 的现成取法）。`who == "ui:<id>"` 时挂在那个控件矩形上方 |
| **B 剧场对白** | `cw_tutor_view_theater.gd` | 底部对白条 + 立绘 + 名牌。`who` 决定立绘与名字，`at` 忽略 |
| **T 计数皮** | `cw_tutor_view_tally.gd` | **只记账不画**：九类意图按调用序记进数组。无头跑完整关与数据逐条比 —— **这是全案唯一让「第一关端到端验收」与两版方向稿解耦的机件**（简报② 说方向稿另有两个 agent 在出）。两位评委都点名它是丙最实用的一件 |
| ★ **P 占位皮** | `cw_tutor_view_plain.gd` | **本稿新增**，为的是 Kevin 09-19「两个都不好，重做」：方向稿要第二轮，而 S1/S2 的真机验收不能等。做法是**零美术**：`say` = 棋盘下方一条 `CWStyle` 描边文字行，`point` = 描边 + 慢闪（`mode` 三档都画成同一种），`chapter` / `codex_unlocked` = 纯文字。**S12 定：留作兜底，不删。** 三条理由：① 它零美术零依赖，皮 A 哪天被改坏了、或者美术再推一轮方向稿，一句 `CWSettings.tutor_skin` 就能把六关跑完；② `t_tutor_view` 的「两版皮都实现了九个方法」那条源码闸**要第二个实现才有判别力**，只剩皮 A 的话它退化成自证；③ 它是 `screenshot.gd` 的备用驱动面（`call:CWTutorViewPlain:advance`）。文件头那句「不代表任何美术口径」留着 |

### 5.3 三条接口纪律

1. **只发意图、不发控件**：`point([{kind:"ui", id:"bar:迁移"}])` 里的「迁移」是**按钮标题**不是节点路径，两皮各自用 `action_bar.button_rect("迁移")`（`action_bar.gd:278-284`）或别的办法去找。
2. **所有协程方法在计数皮里立即返回**，并往流水账记一条 `{kind, args}` —— 测试靠它断言顺序。
3. **禁区矩形归皮不归导演**（搬乙）：`toast.keep_out`（`toast.gd`、`match.gd:798`）由皮在 `attach()` 里设。老方案里它是 `CWGuide.ZONE` 那个 600×200 的硬矩形，**两版皮形状肯定不同**。

### 5.4 控件 id 归宿表（护栏扫：剧本用到的每个 id 都指到一支真实分支）

| id | 取法 | 出处 |
|---|---|---|
| `bar:<按钮标题>` | `action_bar.button_rect(title)` | `action_bar.gd:278-284` |
| `bar` | `action_bar.bar_rect()` | `action_bar.gd:288` |
| `panel:round` / `panel:level` / `panel:end` / `row:<pid>` / `pips:<pid>` | `panel.rect_of(what)` | `match_panel.gd:265-289` |
| `hand` | 静态矩形 | 老 `guide_spotlight.gd:211-215` |
| `board` | 全部格顶面中心极值 + 半格 | 老 `guide_spotlight.gd:164-173` |
| `hex:<q,r>` | `board.tile_center` → `CWView.board_to_screen` | |
| `skill:<名>` | 技能栏按钮矩形 | PRD:479/491 |

**老 `FLAGS` 那张「语义 → 目标」映射表作废**（`guide_spotlight.gd:27-60` 的 20 个键）：剧本直接给目标 id 与坐标，不再经一层语义转译 —— 那张表每加一个提亮点就要改代码。

**换皮开关**：`CWSettings` 一个键，`main.gd` 装配时注入对应实例，**可现场 A/B 切**。两版并存不冲突，落选那版留在仓库零成本。

### 5.5 已定的表现层口径（★ Kevin 2026-09-19，做皮的人照这条走）

| # | Kevin 原话 | 皮要怎么做 | 验收 |
|---|---|---|---|
| 1 | 「**迁移按钮改为单线原样，用闪烁来提示用户**」 | 提亮**不换按钮样式**：不加粗描边、不换底色、不套第二层框 —— 按钮保持**单线原样**，只让它按通用规则 8**轻微慢闪**（较慢频次、反差较低）。`point.mode == "soft"` 在皮里就是这一种画法 | 真机截图两帧对拍（未提示 / 提示中），**按钮轮廓线宽与颜色一字不差**，差别只在亮度周期 |
| 2 | 「**两个都不好，重做**」 | 该项的两版候选全否 ⇒ **皮等第二轮方向稿**。在那之前一切真机验收走 **P 占位皮**；导演 / 数据 / 钩子**一行都不用改**（这是表现接口的全部意义） | S3 的前置条件写死「方向稿第二轮定稿」；S1/S2/S4~S12 的判据里**不许出现任何美术口径** |
| 3 | 其余七答（1-1 / 2 / 4 / 5 / 6 / 8）与「2. 要」 | 问题原文不在本工作流的读物里 —— **不替它们编内容**。它们落在皮与流程外的安排上，不改 §1～§4 | 派工时把原问题与答案一起交给做 S3 的 agent；S3 回传里逐条对照「哪一答落在哪一帧截图上」 |
| 4 | 「**整体走 A**」（2026-09-19 第三轮，S3 派工书逐字） | 第 2 行那条「两个都不好」是**误读**：实际只否了自动重置那一帧，方向 A 整体通过 ⇒ **皮 A `cw_tutor_view_bubble.gd` 成为缺省**，占位皮 P 与计数皮 T 留着可切（`CWSettings.tutor_skin`） | `t_tutor_view_bubble` 25 项 + 真机六帧 `截图_2026-09-19_教程v2_S3/` |
| 5 | 「台词 = 贴着说话者那一格上方的像素气泡，尾巴指向细胞、**跟随位置**」 | `say` 每帧重算锚点：`who == "ui:<id>"` 挂控件矩形上方，其余问装配方注入的 `speaker_of`（皮不认识镜像）。**一句一泡**：三句摞一只泡在第一关 4 倍机位下会把主角细胞整个盖住 | 气泡锚点跟细胞 / 控件两条断言；第 ② 帧 |
| 6 | 「**提示行一出现就把台词收掉**」（沿用占位皮那条） | `hint()` 头一行就是 `_clear_say()`，空串也收 —— 说话与催人动手在流程上本来互斥 | 「提示行出现即收台词」断言；第 ⑤ 帧 |
| 7 | 「【迁移】等按钮**保持单线原样、提示只慢闪**，皮别再套气泡在按钮上」 | `point` 覆写把 `tip` 摘给自己画，提亮照旧交回提亮层；**`tip` 空串时皮一个气泡都不挂** ⇒ 控件旁小气泡只给第六关「点击结算【微环境压迫】」那种 | 「tip 空串 ⇒ 不挂」断言；第 ⑤⑥ 帧同一颗按钮的亮相 / 暗相对拍 |
| 8 | 「图鉴解锁 = **右上角滑入的小卡**，连着几条要排队 / 叠放」 | 196×46，滑入 0.25 / 停 2.2 / 滑出 0.22，竖向间距 6，走掉一张下面的往上补位；右缘跟着右栏走（950 / 686） | 「小卡排队」断言；第 ③④ 帧 |
| 9 | S2 留的两问由 S3 定 | ① **横带 + 幕布 0.94**：B 的两道横线没解决「主角细胞从大字底下透出来」，补方向 A 的整幅横带（222 起 960×124、alpha 0.99）并把幕布 0.88→0.94，两条都要；② 副标**照 B 的表落 silkscreen 不动** —— Kevin 拍板时看的就是那张图 | 第 ① 帧与 S2 的 ① 帧对拍：「第一章」三个字不再糊 |
| 10 | 镜头（PRD 04:08 版新增，PRD:9-22 / :65） | `ui.camera = {anchor: map\|player, align: center\|left\|right}`，缺省「地图调中」；zoom 按**活跃格集合**算（整盘 = 对局机位那三个数），看点按 anchor 取地图包围盒中心或玩家那一格，align 把它放在镜头横向的 1/3、1/2、2/3，竖直恒居中；关首直接就位、关内换 step 补间 0.45s。**通用规则 13**：镜头外 / 被框切到的格不许当目标 （`CWView.tile_fully_visible`，高亮与点击共用一支） | `t_tutor_camera` 15 项 + `t_tutor_data` 的第 ⑭ 条判别力；第 ⑦⑧ 帧 |

---

## 6. 测试

口径：全量走 `tools/run_tests.sh`（分片并行 ~85 s），别裸跑再 grep。
**新测试必须手工登记进 `_run_all`**（`headless_test.gd:133-176` 是**手写函数名清单**，不是反射扫描；分片按清单下标分）。不登记就**永远不跑、也不报错**。

### 6.1 新增测试

| 测试 | 盖什么 | 出处 |
|---|---|---|
| `t_tutor_data` | ① schema / 顶层键白名单；② 每个 world 跑 `resolve → load_world → dump_world ≡ minify(resolve)`（含 `from`/`patch`）；③ 席位数 == 细胞数、每席恰好一只、`players[i].seat == i`；④ 活跃格 ⊆ 半径、压到 11 个特殊格的都显式写 `type`；⑤ `{{tune.*}}` 解析得出；⑥ 提到固化的关盘面里有 `state=="solid"` 的格；⑦ `reveal` 的格必须已在某份 world 的盘面上；⑧ **`flow[0].do == "state"` 且带 `load`**；⑨ **`prd` 单调不减且逐关覆盖 PRD 的编号行** | 丙 |
| `t_tutor_beats` | 条目文法纯函数：九个动词全认、表外动词报错；阻塞型判定；`allow` 前缀匹配；三类谓词解析（含 `count`/`arg`）；**计数谓词跨回合自动重取基线** | 丙 |
| `t_tutor_flow`（**桩关卡 + 记录型假皮**） | 一份桩关卡（3 个 step、九个动词各至少一条），断言**意图序列逐条相同**；不碰引擎、毫秒级。断言 `hud`/`reveal` 在第一条 `say` 之前（PRD:39）、`block(true/false)` 成对、`point` 缺省 `mode=="soft"` | **甲**（评委 2：三份里最早把导演本体与引擎解耦测掉的一条） |
| `t_tutor_director`（**假队列喂 `step_end`**） | ① 翻页序列与数据一致；② 装闸只在 `step_end` 与翻页两处、幂等；③ `allow==[]` 时挂起、`answer` 调用数为 0、行动栏没建；④ 全落空时 warning + 挂起；⑤ **换局那一瞬间基线重取**；⑥ **关首装闸在 `run()` 之前** | 丙（测时序，补甲的盲区） |
| `t_tutor_gate` | 三态；**下标只映射一次**；`abort()` 唤醒挂在闸上的那一问；`mutes_result` 仍静掉「无法复活」 | 丙 |
| `t_tutor_view` | **用计数皮跑完每一关**：九类意图调用序列与 `flow` 逐条比；两版皮都实现了九个方法（源码扫 `func say(` 等）；`point` 用到的每个 ui id 都指到真实分支 | 丙 |
| `t_tutor_hooks` | 钩子护栏：`scripts/tutor/**` 零 `CWGame`/`CWWorld`/`CWActions`/`CWSetup`/`game.`；**`ctx.` 后面只许是那九个标识符**；每个 `{"do":"hook","call":"X"}` 点名的 `X` 真实存在；除三个例外文件外零 `class_name`；**钩子文件零成员变量**；**每个 `while` 条件含 `ctx.alive()`**；**【实测改判 S8】**对象账从「20 次重置 `OBJECT_COUNT` 不单调上涨」改成「钩子跑 3 帧与 12 帧两轮 churn 的涨幅一样大」（理由见 §3.7） | 丙 + 本稿的 ctx 纪律 + 乙的 epoch 判据 |
| `t_tutor_fx` | 教程演出全是**时间的纯函数**：同一个 `t` 喂两遍结果一样；同种子逐帧复现、中间搅 64 颗全局随机数不受影响；**整段零内核 rng 消耗（跑完带子 `at == 0`）** | 丙 |
| `t_tutor_c1` / `_c2` | 逐关端到端：带子**双向归零**；活跃格条数与 PRD 对得上；**第三关能量 66 逐项对得上**、三次攻击 10+0+20 刚好打死、`reset_when` 在「能量不足以移动」时触发并回关首；第二关 Step1 净化的两格在 Step2 仍是健康组织 + Step1 期间那只癌细胞节点 `visible == false`；第五关 III 级门槛按 `seats != 4` 回落六人档、全癌死亡时 `until` 命中**且没弹结算屏**；**第一～五关的 `allow` 里没有 `act=end`** | 丙 |
| `t_tutor_c2`（**S5 落地实况**，90 条） | 第四关：整盘 127 格、`attack_max_per_turn == 0`、起手 II/20/∞ 站 `(4,-1)`、11 格特殊组织**不摊平**、净化 10 格记忆 20→30 命中 `level_at_least III`；第五关 Step1：四种分化都选得到（NPC 免疫是未分化的）、真分化一次、图鉴在 O-玩家 之后才解锁、Step2 走的是**关内 `load`**；四份 world 各自过圆环且「抹掉 seat 0 的 `type` 之后逐字相同」；Step2：`ui` 层（`switch_type` / ∞ / 藏回合 / 无结束回合 / 无手牌）、「切换种类」按满一圈回到起点、**同一行动回合里攻击 5 次**、剩三只不翻页 / 四只全灭才命中 `all_dead: cancer`、`winner` 仍是 -1、固化三格都没被免疫占据；∞ 的**带宽**判据（花掉 100 能量仍是 ∞、别的细胞照常写数字）；`level_bottom(9) ≤ 540 < level_bottom(10)`；真起 `Main.tscn`：9 席、**八只非人类席逐席装 `Decider` 且 `plan` 全空**、遮罩真的揭到 127 格、`ui.switch_type` 一非空按钮就出来 | S5 |
| **`t_tutor_energy_formula`** | **用引擎现算**（`pass_through_map` + `immune_move_cancerous`，`cw_actions.gd:547-563`）**复核数据里写死的 66，差一分当场红** | **乙**（两位评委都说「无论最终选谁都收进去」） |
| `t_tutor_interlude`（**S9b 落地实况，38 条**） | 阵营翻转那份 world 装得进（`faction:"cancer"` + `cancer_type:"SmallCellLung"`）；**翻转走的是完整换局：断言 `player_count` / `human_players` / 右栏面板真的重挂过**；三次攻击带子精确用尽；**击退 1 格是重装不是规则**（断言 `cw_actions.gd` 源文件哈希未变）；★ **间章独立成段**：`chapter_kind=="interlude"`、`flow[0].load == null` 且是**显式**写的、进间章前后玩家细胞坐标一致（第一拍不重装）、目录里它与三个主章节同级 | 丙 + **乙的 F5 判据** + ★ Kevin 09-19 |
| `t_tutor_c3`（第七关，最重） | ① 25 步与 PRD:439-503 逐条对账；② 带子双向归零（录制生成）；③ **连跑 N 次 E 阶段都不产 `game_over`**；④ **硬断言：黏液破裂 → 死亡 → 复活这一段跨过的那次 E 也不产 `game_over`**，且死亡窗口内盘上至少一格 `state=="solid"` 且无免疫占据；⑤ 玩家席 `allow` 之外的选项全不出现在行动栏；⑥ 转移落点几何（9 → 11 → 两跳邻接）；⑦ `overload_div == 0`；⑧ 世界回合 ≤ 5 | 丙 |
| `t_tutor_progress` | 写入 / 读回；**`opening_seen` 不被覆盖**（两边各自 `ConfigFile.load` + `set_value`，正面比一次）；旧档只有 `done` 时的行为 | 丙 + 甲 |

### 6.2 护栏（结构闸）

- **`t_no_engine_in_ui`**：扫描目录从 `res://scripts/ui` 扩到 `+ res://scripts/tutor`，并**改成递归**（今天是 `DirAccess.get_files_at` **单层不递归**，`headless_test.gd:20055` 一带；`scripts/tutor/levels/` 是子目录）。白名单 `UI_ENGINE_OK` 仍只有一条 `ui_bridge.gd`，**条数硬断言 `UI_ENGINE_OK.size() == 1`（`:20108`）不变**。把「递归了」写进那条 check 的文案。
- **`t_font_coverage`（三家的修法都不完整，本稿给完整版）**：
  现状是它**今天就已经递归扫 `res://data/tutorial/**/*.json`**（`headless_test.gd:12925-12950`），上屏键表 `GUIDE_TEXT_KEYS := ["title","chapter_title","subtitle","t","b","advise"]`（`:12951`），并**硬断言 `jfiles.size() >= 4 and lines.size() > 20`**；`.gd` 那一半扫的是 `res://scripts` **整棵树**（`:12913` 的 `_collect_files("res://scripts", files)`）。
  ⇒ 改三处，**三处都已落地**：① `GUIDE_TEXT_KEYS` 扩成 `["title","chapter_title","subtitle","lines","hint","advise","tip"]`（**老键 `t`/`b` 随 cwtut/1 一起没了，新键叫 `lines`**）；② 关卡 JSON 至少 4 份、上屏行 > 20 —— S1 那一刻只有一关，临时降到 `1 / 5`，**S12 收口已抬回 `4 / 20`**（实测 10 份 JSON 远超阈值）；③ `.gd` 那一半本来就罩住了 `scripts/tutor`（整棵树），没改，钩子里的兜底文案走 `ctx.beat({"do":"say"…})` 的字面量、扫得到。
- **★ `∞` 字形那一条（S13，已落地：走的是终态 ①，`tools/add_infinity_glyph.py` 手补了 U+221E）**：Kevin 09-19「补字形，没有相似字形就用 INF」。两种合法终态：
  ① 字库补上 U+221E ⇒ 显示串常量是 `"∞"`，闸自然放行；② 补不出 ⇒ 常量是 `"INF"`。
  **两种终态都要有一条正面断言**：`cw_tutor_layers.energy_text(INFINITE_AT, "infinite")` 的返回串**逐字符都在字库覆盖集里** —— **S12 补上了**（别只靠扫文件：这个串是代码常量，扫 JSON 扫不到它；扫 `.gd` 字面量也抓不住「拼出来的串」那一种）。
- **闸三（xcheck `total_sites`）每片都会抬**（2026-09-20 闸三整个退役，此条作废）：新增断言全落新档，`core` 分子分母不许动。每片 `--write` 一次并在回传写清涨在哪个档。**S12 收口值 `total_sites` 3797 → 3799**（+2，`core_sites` 1082 / `covered_sites` 423 一个数没动）。

### 6.3 剧本 12 条通用规则 → 哪条测试（**实测表**，S2 落地当天按仓库里真有的断言重写）

> 原表是开工前的**计划**；S2 交付第 4 条要求把它改成实测值。下表每一格都是**今天仓库里真跑着的断言**；
> 还没有归宿的写「待 S4 / S6」，**不写计划中的测试名**（写了就分不清「测过」与「打算测」）。
> 真机帧在 `截图_2026-09-19_教程v2_S2/`（六帧）。

| 通用规则 | 今天谁盖 | 断言（摘要） |
|---|---|---|
| 1 章节提示（PRD:35） | `t_tutor_flow` + `t_tutor_view` + **`t_tutor_chrome`** + 真机 ① | 意图序列第一条就是 `chapter`、章号与章名从数据来；`chapter_text()` 两行字逐字对（`第一章  Cell` / `CHAPTER I - CELL`）；`chapter_alpha()` 淡入 / 停 / 淡出且总长仍是 1.8 秒；播完自己收；这一屏排在最顶（连常驻两颗一起罩住） |
| 2 关间静默（PRD:37） | `t_tutor_director` | 同章换关**一条 `chapter` 意图都不发**；章号相同但 `chapter_kind` 变了照样算换章 |
| 3 先状态后文本（PRD:39） | `t_tutor_data` ⑧ + `t_tutor_flow` | `flow[0].do == "state"` 且带 `load`；`reveal` / `shell` 都排在第一条 `say` 之前 |
| 4 常驻重置（PRD:41） | **`t_tutor_chrome`** + **`t_tutor_c1`**（S4）+ 真机 ②⑤ | 「重置」那颗排在全屏 STOP 层**之上**、遮挡期照样收得到点击；`can_reset=false` 时整颗不出；劝重置时只推拉亮度。**回关首那份 world 已实测**：`flow[0].load` 那一份 `dump_world ≡ minify`、人回 `(0,-1)`、能量回 6.6，装配侧走 `_tutor_load_world(_tutor_entry_world(), true)`（顺带把 `reveal` 加进来的活跃格收回去） |
| 5 常驻目录（PRD:43） | **`t_tutor_chrome`** + 真机 ⑤ | 点目录开出面板、关表照 `shell()` 那份列、未解锁的灰着点不动、点已解锁的发 `menu_goto` 并收面板。**真面板（章-关两级 / 间章平级单列 / 焦点菱形）与进度存档在 S6 的 `t_tutor_progress`** |
| 6 地图浮现（PRD:45） | `t_tutor_flow` / `t_tutor_view` + 现成的 `t_board_active_tiles` | `reveal` 意图带着那组坐标、排在第一条 `say` 之前；棋盘按环错峰的活跃集淡入 |
| 7 重置有动画（PRD:47） | **`t_tutor_spot`** + **`t_tutor_c1`**（S4）+ 真机 ⑥ | `reset_anim()` 真的转调 `cw_tutor_fx` 的 `reset_hint`、候选是 Kevin 拍的「倒带」rewind。**次序已实测**：`reset_when: stuck` 命中之后皮的流水账里 `reset_anim` 排在 `want_reset` 之前，重置完游标回 0、代际 +1 |
| 8 轻微慢闪（PRD:49） | `t_tutor_flow` + **`t_tutor_spot`** + 真机 ③④ 对拍 | `point` 缺省 `mode == "soft"`；亮度曲线周期 = `CWStyle.HALO_PERIOD` 3.2 秒、幅度只在 [0.35, 1.0]（较慢频次、反差较低）；★ **拿得到本体的目标一笔都不画**，提亮前后按钮的描边线宽 / 描边色 / 底色 / 字色一字不差 |
| 9 提示期禁操作（PRD:51） | `t_tutor_gate` + `t_tutor_flow` + **`t_tutor_chrome`** | 非 `player` 条目 `allow == []`；`block(true/false)` 成对；全屏 STOP 层是**真·全屏**锚点 + `MOUSE_FILTER_STOP`，排在「重置 / 目录」之下 |
| 10 癌种作者期定死（PRD:53） | `t_tutor_data` | 每个癌席 `cancer_type` 必填，装载器拒缺省 |
| 11 NPC 无 AI（PRD:55） | `t_tutorial_npc` | 纯 decider 三段。**「非人类席都有 decider」在 S5 的 `t_tutor_c2`** |
| 12 地图预设计（PRD:57） | `t_tutor_data` | 盘面全在 JSON，零运行期随机 |

**两支新测试**：`t_tutor_chrome`（23 项）/ `t_tutor_spot`（20 项），已登记进 `headless_test.gd::_run_all` 那份手写清单。

### 6.4 老测试：作废 / 改判

> ⚠ 仓库纪律是「老 `check()` 一条不删」。这次 Kevin 明确推倒重来，**断言对象整体消失**，纪律要显式破例 → **Q-07 请示**。纪律：**一条不删着走，逐条写「原断言 → 新断言 / 迁到哪 → 依据」**。
> **执行情况（S12 收口复核）**：下面「整份删」的 18 支**在 S1 就已全部删净**（今天仓库里 `grep` 一个都找不到），
> 「判据形状能迁的」**逐条迁完**，「改判」4 支**逐条改到位**，「原样通过」5 支**一个字没动、仍绿**。
> 破例本身与逐条去向记在 `docs/开发日志.md` 2026-09-19 · S12 那条。

**整份删（断言对象不存在了）**：`t_guide_director`（`:10919`）、`t_guide_data`（`:10805`）、`t_guide_bridge`（`:11583`）、`t_guide_spotlight`（`:11720`）、`t_guide_watch`（`:9939`）、`t_guide_quiet`（`:10041`）、`t_guide_no_win`（`:9641`）、`t_guide_progress`（`:11195`）、`t_tutorial`（`:10553`）、`t_tutorial_data`（`:20837`）、`t_tutorial_stage`（`:20378`）、`t_tutorial_shell`（`:20913`）、`t_tutorial_c1`（`:21206`）、`t_tutorial_c2`（`:21730`）、`t_tutorial_auto_advance`（`:11110`）、`t_tutorial_chapter_swap`（`:12309`）、`t_tutorial_mechanism_trials`（`:1853`）、`t_tutorial_pick`（`:13077`，今天已停用）。
**判据形状能迁的逐条迁（✅ 已迁）**：`t_guide_no_win` 的「不产 game_over」→ `t_tutor_c1`（第三关全癌死亡后 `winner == -1` 且没 aborted，**S12 补**）+ `t_tutor_c3` ⑱（【黏液破裂】真技能跨一次 E 仍不终局，S11 落）；`t_guide_quiet` 的 `mutes_result` → `t_tutor_gate`；`t_guide_progress` → `t_tutor_progress`；`t_tutorial_chapter_swap` 的「跨章桥也换句柄」→ `t_tutor_director`；老闸三态 / NPC 兜底 → `t_tutor_gate` / `t_tutorial_npc`。

**改判（✅ 已改）**：`t_no_engine_in_ui`（扫描目录扩到 `scripts/tutor` + 改成递归，S1）、`t_codex`（去掉 `_gate` 相关的 7 条，`_mark_locked` 的纯函数判据保留，S6）、`t_entry_smoke_tutorial`（按新第一关盘面改判，`board.map.size() == 127` 不变；入口那一条 S1 是「灰着」、**S12 翻成「已恢复」**）、`t_font_coverage`（阈值 S1 降 `1/5`、**S12 抬回 `4/20`** + 补 ∞ 串正面断言，见 §6.2）。

**原样通过（一个字不动）**：`t_tutorial_opening`（`:21520`，开场保留）、`t_tutorial_npc`（`:21958`）、`t_board_small`（`:7711`）、`t_board_active_tiles`（`:20302`）、`t_kernel_loader_moved`（`:20249`），以及与教程无关的全部。

---

## 7. 拆片（**全部做完**，2026-09-19；下表保留是为了留下依赖与工期的实绩）

> 口径：一人日 = 熟悉这套代码的人做一天，含写测试、跑 `tools/run_tests.sh`、真机截图核对。**不含美术新资产**。
> **拆片形状照甲**（简报第 7 条是硬要求）：第一片是「删老教程 + 新骨架 + 第一关端到端」的**原子片**，**允许它超尺寸（约 1.75 人日）** —— 两位评委的同一条建议，理由是中间状态「教程是空壳」在真机上验收不了。片内分两次提交（commit A = 拆除 + 空壳入口，commit B = 骨架 + 第一关），保住丙「可独立回滚」的好处。

> **★ 本轮按 Kevin 09-19 的追加回答重排过三处**：① 方向稿「两个都不好，重做」⇒ 皮那一片（S3）**阻塞在第二轮方向稿上**，从关键路径里摘出去，S1 起用**占位皮 P**（§5.2）顶真机验收；② `∞` 字形「补字形 / 否则 INF」独立成 **S13**，与主线并行；③ 间章独立成段（不是第五关的附属）落在 **S9** 的判据里。

| 片 | 标题 | 依赖 | 人时 |
|---|---|---|---|
| **S1** ✅ | **删老教程 + 新骨架 + 第一关端到端**（★原子片，超尺寸；含计数皮 + 占位皮） | — | 14 |
| **S2** ✅ | 常驻壳 + 提亮 + 通用规则验收表（占位皮上验收） | S1 | 8 |
| **S3** ✅ | 表现层皮实装 —— **实际走「整体取方向 A」，没有第二轮**（皮 A 贴身气泡成缺省）+ 教程镜头 | S2 | 8 |
| **S4** ✅ | 第二关 + 第三关 + 自动重置 / 劝重置 + 能量公式复核 | S2 | 8 |
| **S5** ✅ | 第四关 + 第五关 + NPC 席位 + 切换种类 + 关内换盘（**2026-09-19 落地**，见开发日志同日那条） | S4 | 8 |
| **S6** ✅ | 图鉴解锁通知 + 进度存档 + 目录面板（**间章平级单列**） | S2 | 6 |
| **S7** ✅ | 教程演出库 `cw_tutor_fx`（纯函数 `apply(t)`） | S1 | 8 |
| **S8** ✅ | **钩子层：`ctx` 九方法 + epoch 取消 + `t_tutor_hooks` 护栏** | S1 | 6 |
| **S9** ✅ | 间章 癌变（**独立一段** + **阵营翻转走完整换局** + 第一拍不重装）—— 实际拆成 S9a 地基 / S9b 本体 | S7, S8, S5 | 8 |
| **S10** | 第六关 a：盘面 / 几何 / 席位 / 带子录制 / 三条胜负护栏（**2026-09-19 已落地**，关 id `c3_l6`；席位恒 5、第 23 步复用已死的 1/2/3 席） | S9 | 8 |
| **S11** ✅ | 第六关 b：25 条流程 + 三个钩子 + 五段演出 | S10 | 8 |
| **S12** ✅ | 收口：入口恢复、老测试删改复核、字形闸阈值抬回、`dump_guide` / `screenshot` 按新壳重写、三份文档、真机通关 | 全部 | 6 |
| **S13** ✅ | ★ `∞` 字形：给缝合像素 10px 补了 U+221E（`tools/add_infinity_glyph.py`），没用 `INF` 兜底 | S1 | 4 |

**依赖图与并行度**：
```
S1 ─┬─ S2 ─┬─ S4 ── S5 ──┐
    │      ├─ S6         │
    │      └─ S3（阻塞：等第二轮方向稿，不在关键路径上）
    ├─ S7 ─┐             │
    ├─ S8 ─┴───── S9 ── S10 ── S11 ──┴─ S12
    └─ S13（并行，4 人时）
```
S1 之后**最多五个 worktree-agent 同时开工**（S2 线、S7、S8、S13，随后 S4 / S6）。
**关键路径** S1(14) → S2(8) → S4(8) → S5(8) → S9(8) → S10(8) → S11(8) → S12(6) = **68 人时 ≈ 8.5 人日**（S9 现在要等第五关的活局面 ⇒ 挂在 S5 后面，这是间章「第一拍不重装」换来的代价，写明）。
**合计** S1~S13 不含皮 = **92 人时 ≈ 11.5 人日**（14+8+8+8+6+8+6+8+8+8+6+4）；每做一版皮 +8 人时。另计缓冲 2.0 人日：① 示意图 / 方向稿往返 1.0；② Q 未答期间的阻塞 1.0（S10/S11 最容易堵）。
Kevin 原定 09-20 早 7 点只够交到 **S1 + S2**（第一关真机可玩，占位皮）；按既定口径「间章 + 第三章一起交、期限顺延」。
**实绩（2026-09-19 当天）**：S1～S13 全部落地，真机从主菜单一路打到第六关通关一次。皮那一片没有等到第二轮方向稿 —— Kevin 的「两个都不好」被复核为误读（只否了自动重置那一帧），整体走方向 A。

（各片的删 / 建 / 判据逐条见 `tut_v2_slices.json`。）

---

## 8. 风险与要问的

### 8.1 开工前必须先落地的两件（评委 2 的前提条件，本稿已补）

1. **`ctx` 九个方法的完整签名 + 取消语义** —— §3.7 已给；它是 S8 的全部内容，且 `t_tutor_hooks` 的判据依赖它。**签名定下来之前那条闸写不出来。**
2. **拆片按甲的形状重排** —— §7 已做：S1 是端到端原子片，关键路径从丙的 8.75 人日压回 6.5 人日。

### 8.2 无论谁做都要带走的三条硬账（三份方案都有人漏）

- `immune_move_healthy` / `immune_move_cancerous` 是 **tier C**，「迁移不消耗能量」**只能走大能量**，别再试旋钮。
- 凡跑 E 阶段的关（只有第七关）**必写 `overload_div: 0`**（tier A），否则 99990 每个世界回合被【能量过载】啃一笔**并写日志到左侧出牌列 CWFeed**。
- `t_font_coverage` **今天就在扫 `data/tutorial/**/*.json`** 且有 `jfiles.size() >= 4 and lines.size() > 20` 的硬断言（`headless_test.gd:12925-12951`）—— 第一片只有一关时这条会判红，修法见 §6.2。

### 8.3 要 Kevin / hxr 答的（每条带我方默认；★ = 挡住开工）

| # | 问题 | 出处 | 我方默认（不答就这么做） |
|---|---|---|---|
| **Q-01** | **第六关是不是有意跳号？**（第二章只有四、五关，间章后直接第七关） | PRD:287/329/415 | **有意跳号**，按 6 关做（一/二/三/四/五/七）。关号只是 `title` 的字 |
| **Q-02** | 主菜单「看完引导再进、先挑对手癌种」那套留不留？剧本没写 | `main_menu.gd:118/136/459-471` | 三家分歧（甲删、乙留、丙留）。**默认留**（Kevin 09-05 拍板过的不因剧本没写就废），但入口信号简化成**不带参数** —— 癌种改由每关 JSON 的 `players[].cancer_type` 定死（通用规则 10 + 带子可复现），玩家挑了会把盘面与带子全搅了。**09-25 Kevin 改判：删**。第六关能通关之后这个选单第一次真的弹了出来（「为什么点新手教程会弹出选择对手癌种」），选了也不起作用，`main_menu._open_tutorial` 改成直接发信号 |
| **★Q-03** | 第七关第 8 步「重复 3-5」还是「3-7」？**重复几轮？** | PRD:459 | **按 3-7 实现**（3-5 里没有免疫行动，T 细胞永远不会变少）；**轮数 2~3**（世界回合 ≤ 5，保住癌 I 期，分档下标不漂）。**轮数直接决定带子录制，这条不答 S10/S11 会堵** |
| **★Q-04** | 第七关第 18 步「释放细胞毒素」（:485）与【黏液破裂】（:491）走**真技能**还是**纯演出**？ | PRD:485/491 | **都走真技能 + 钉带子**（结局画面要可预期）。真技能会造坏死格 `NECROSIS_TOXIN`，**影响其后每一份重装盘面** —— 若 hxr 只要画面，改纯演出更省，但要一起说清后面几份重装照哪一版写 |
| **★Q-05** | 第七关整张地图与 T 细胞站位要**具体格子**；第二、三关的「凸的癌组织连通块」「向前 / 向周围延伸」也要圈定 | PRD:229/291/461 | 我方出一版示意图给 hxr 圈（设计改动先出示意图是既定流程）。默认：第一～三章走 `r=-1` / `r=-2` 两排零特殊格；第七关直线放 `r=-1` 排、**起点距离 9**（玩家 `(-3,-1)`、T `(6,-1)`） |
| **Q-06** | 间章「等待几秒」是几秒？四处「……」的文案是什么？ | PRD:395/397/405/439/475 | 等待 **2.0 秒**；「……」**就是留白本身**（沉默几拍，皮上不出字），作占位并在流水账标 TODO |
| **Q-07** | **老测试「一条不删」的纪律这次破例吗？** 18 个测试的断言对象整体消失 | §6.4 | **破例**：逐条列表 + 每条写理由 + 能迁的迁进新测试，破例本身在开发日志记一条 |
| ~~Q-08~~ **已答** | 两版皮什么时候定？ | 简报② | **Kevin 09-19：「两个都不好，重做」** ⇒ 方向稿第二轮；期间用占位皮 P，S3 从关键路径摘出（§5.5 / §7）。**接口一字不改**，换皮仍是换一个实例 |
| ~~Q-09~~ **已答** | 「显示 ∞」字库里没有 U+221E | PRD:301/369/431 | **Kevin 09-19：「补字形，如果没有相似字形，就用 INF」** ⇒ 先补 U+221E（或改一个形近字形），补不出就把常量改 `INF`。独立一片 S13（§3.2b / §6.2） |
| **Q-09b** | 间章要不要弹一屏章节提示？（Kevin 已定「间章不是主章节的附属」，目录平级单列没有疑问；**提示屏**是另一件事） | PRD:35/385/393 | **不弹**：PRD:393 要冲击波在上一关最后一击处**原地**起，中间插一屏大字会打断连贯。要弹是数据一行（§3.6）。**请一句话确认** |
| **Q-10** | 「继续」代做（老 `guide_bridge.take_offer`）还要吗？PRD 没写 | `guide_bridge.gd:184-202` | **不要**。每步 `allow` 已把选项收到一两个，代做没价值；而它是老方案里最容易**静默错到底**的一处（下标映射两次，不崩） |
| **Q-11** | 进度续读到「步」还是「关」？ | PRD:41/43 | **到关**。续到步要连带定义「重进时局面怎么摆」，是行为改动不是存档改动 |
| **Q-12** | 【黏液破裂】自毁后复活，引擎给 2.0 能量并把那格固化降级 —— 与「能量保持 Null」冲突 | PRD:431/495 | 复活那一步**紧跟一份重装 world**：能量拨回哨兵、依托格按碎掉之后的样子写（`worlds.revived`；09-25 起就地复活、依托 (-4,1)） |
| **Q-13** | **像素错误**（间章两次 + 第七关一次）与暗黑像素冲击波的美术口径 | PRD:393/399/403/487 | 请 hxr 给一句话（**抖动 / 色块错位 / 扫描线**三选一），我方各出一版预览图再实现 |
| **Q-14** | 第七关「癌细胞死亡」之后接什么？第四章「跟回合有关的」还没写 | PRD:503/505-508 | **回主菜单 + 落一笔「全部通关」**，**不弹结算屏**（09-25 才接上：`CWMatch.tutorial_done` 停 2 s → `main._back_to_menu()`） |
| **Q-15** | 自动重置的范围：剧本只有第三关 Step1 写了，其余关有没有？ | PRD:47/251 | **其余关无自动重置**（`allow` 白名单本来就走不歪；第七关强制演出更不需要） |
| **Q-16** | 第四关起手免疫等级 / 记忆（PRD 没写）；19 格盘面从 I 级 0 点起凑不出 30 | PRD:307 | **起手 II 级 20 记忆**（要升到 30，本关可得 24，富余 14）。改就改数据一行 |
| **Q-17** | 第二关 Step2：癌细胞 1.0 能量 + 一次成功 1.0 伤害 = **一击必杀**，而文案写「攻击癌细胞直到其死亡」 | PRD:193/203 | **改文案**为「击杀它」（乙建议改数据抬到 2.0 能量 + 两颗骰，也可；请 hxr 选一个） |
| **Q-18** | 教程里**卡牌 /【基因表达】整个关掉吗**？ | PRD 全文没提 | **整个关掉**（`ui.hand=false`、盘面 `hand: []`） |
| **Q-19** | 「粘液破裂」还是「黏液破裂」？通用规则 11「如特殊说明均为 npc」是不是漏了「无」字？ | PRD:55/491 vs `cw_actions.gd:1462` | 统一写**「黏液破裂」**（以仓库为准）；规则 11 **补「无」字** |
| **Q-20** | 12 个解锁点 ↔ 今天 58 条图鉴条目**不是一一对应**（三处共用、一处一开两条） | PRD:29 等 12 处 | **照实登记，不为了凑一一对应去拆图鉴条目**；`codex_map.json` 留着做归宿表 |
| **Q-21** | 开场动画「按任意键跳过」提示留不留？目录要不要「重看开场」？ | PRD:43/59-87 | 跳过**留**（文案不变）；「重看开场」**加**（`clear_seen()` 已备好，`tutorial_opening.gd:142`，目录面板多一行） |
| **Q-22** | **「2. 要」是答哪一问？**（本工作流的读物里没有那一问的原文；界面八问里的 1-1/2/4/6/8 同） | Kevin 09-19 原话 | **不替它编内容**。可确定的是它们落在表现层与流程外的安排上，不改 §1～§4 ⇒ **派工时把原问题连同答案交给做 S3 的 agent**；若其实是冲着架构来的，回头补一条改动记录即可（§0′） |

### 8.4 还没解掉的技术账（不是问题，是风险登记）

1. **第七关是全案 60% 的风险**：十来次重装 + 录制带子 + 五段演出。拆成 S10 / S11 两片，S10 先把「盘面 + 几何 + 带子 + 不弹结算」四条硬护栏做绿，再做演出 —— **演出返工不影响盘面**（甲的理由，采纳）。若 `game/tests/record_level_rolls.gd` 本身出问题，S11 会整片堵住（**S10 已落地并录过 c3_l6/base，零消耗**）。
2. **遮罩外的 127 格是真实的**：半径恒 6，第七关的增生 / 侵蚀 / 压迫会在看不见的地方发生。处置已在 §4（增生拧 0、侵蚀这盘打不到、压迫真结算），但**日志会跑进左侧出牌列 CWFeed** —— S10 要**真机看一眼左列有没有一堆看不懂的行**。
3. **右栏 9 席已经到顶**（让掉回合块那 62px 之后底边 532 / 面板高 540），10 席放不下。第五关 Step2 与第七关的席位数**必须先算清楚再摆盘面**，否则免疫等级块整块掉出屏幕。这是 S10 的第一件事，不是最后一件；PRD:499 的边缘再生细胞**复用已有席位**（预置 + reveal），不新增席位。
4. **钩子的 `ctx` 权限边界是纸面纪律**（丙自认的最大风险，评委 1 的致命伤）：九个方法写死 + `t_tutor_hooks` 的文本扫描能挡住直连引擎，挡不住「钩子经 `ctx` 自己编排一切」。本稿多压两条：**钩子零成员变量**（状态只能进 `ctx.state()`）、**每个 `while` 条件含 `ctx.alive()`**。仍建议 S11 完工后**人工过一遍两个钩子文件的行数**，超过 300 行就当成设计信号回头切。
5. **`cw_kernel_inproc.gd` 的三行行号三家不一致**（393/395/399 vs 399/401/406）：S1 开工第一件事按文件核一次，把准确值写进新文件注释。
6. **进度存档与开场共用一份 cfg**：写盘必须 load-then-set，否则开场每次重播 —— 进 `t_tutor_progress` 的硬断言。
7. **闸三每片都会抬**，每片 `--write` 一次并在回传写清涨在哪个档。

---

## 附 · 本稿相对三份原稿的净改动清单（评委可快速对账）

| # | 改的是什么 | 相对谁 |
|---|---|---|
| 1 | 给出 `ctx` 九个方法的完整签名 + epoch 取消语义 + 「钩子零成员变量 / while 含 `alive()`」两条新护栏 | 补**丙**的承重件图纸（评委 2 的开工前提 1） |
| 2 | 拆片重排成「S1 端到端原子片（允许超尺寸）+ S7/S8 提前开叉」，关键路径 8.75 → 6.5 人日 | 采**甲**的形状，改**丙**（评委 1、2 同一建议） |
| 3 | `point()` 补 `mode`（soft / arrow / fullscreen）与 `tip` | 采**甲**，补**丙**（通用规则 8 落地） |
| 4 | 加 §6.3「12 条通用规则 → 哪条测试」覆盖率账 | 采**甲**，补**丙** |
| 5 | 加 `t_tutor_flow`（桩关卡 + 记录型假皮，测意图序列），与丙的 `t_tutor_director`（假队列，测时序）并存 | 采**甲**，补**丙**的盲区 |
| 6 | 间章阵营翻转**必须走完整换局、不是 `reload_world`**，并加三条断言 | 采**乙**的 F5，补**甲**与**丙** |
| 7 | 加 `t_tutor_energy_formula`（引擎现算复核 66） | 采**乙**（两位评委都要求收进去） |
| 8 | 删 `guide_layers.gd` 的**五个破口逐行清单**写进 S1 判据 | 采**乙**（三家里只有它列全） |
| 9 | `toast.keep_out` 禁区矩形归皮不归导演 | 采**乙**的接口纪律第 3 条 |
| 10 | `t_font_coverage` 的完整修法（现状判断 + 新键 `lines` + **第一片阈值临时下调、S12 抬回**） | 三家修法都不完整，本稿补全 |
| 11 | 效应应答「命中不贯穿」**不动公共 `beam_fx.gd`**，走教程自己的 fx 变体 | 采**丙**，否掉**乙**（回归面溢出教程之外） |
| 12 | 标注 `cw_kernel_inproc.gd` 三行行号三家不一致，开工先核 | 本稿新增 |
| 13 | **∞ 改为「补字形，补不出用 `INF`」**，独立成片 S13（三份原稿一致退成「无限」） | ★ Kevin 09-19，否掉三份的默认 |
| 14 | **间章独立成段**（顶层加 `chapter_kind`、目录平级单列、`flow[0].load` 可显式 `null`、S9 挂到 S5 之后） | ★ Kevin 09-19，改**甲**（挂第五关尾）与**丙 / 乙**（当普通一关） |
| 15 | **加占位皮 P + 皮那一片从关键路径摘出**（方向稿两版都被否、要第二轮） | ★ Kevin 09-19，改三份原稿的「两版皮并行做」 |
| 16 | 提亮口径钉死：**按钮单线原样 + 慢闪**，不换样式 | ★ Kevin 09-19，写进 §5.5 与皮的验收 |
