﻿# 新手引导重做 · 实现方案

> 本文是 `docs/新手引导_实现方案.md` 的定稿，对应 hxr 的 `Cell_War_新手引导PRD_hxr.md`（09-18 重拉，508 行）。
> 仓库根 `D:/Projects/SpringSense/2026-2027/Cell War/Cell-War/`（分支 `csharp-core`），下文路径一律相对它；
> `PRD:n` = 那份 PRD 的第 n 行。写稿期只读仓库，未改一个文件。**每条事实带出处**。
>
> **第四章 Game（PRD:505-508，正文只有「跟回合有关的」一句）不在本方案范围内**
> —— Kevin 09-18 原话「第四章还没有完成，暂时不用管」。全文不为它做任何设计，末尾只留一句衔接。

> **修订记录（复核后逐条改；改动点在正文里都标了「初稿…是错的」）**
> ① **Step ≠ 关**：一关一份 JSON、Step 落成 `steps[]` 分段，关内优先「预置 + 遮罩揭示」，`CHAPTER_COUNT` 9 → **6**（§1.1 / §1.2 / §1.4）；
> ② **S0 要连 C# 一起提**：`KeyTableTests.cs:111` 按路径读 `cw_case_loader.gd`，不改就当场打红 11 条（§2.2 / ③ S0）；
> ③ **第七关是多回合多次 E**，且黏液破裂→复活那一窗口免疫胜利只剩固化格兜底（§2.3 / ③ S10）；
> ④ **`step_begin` 在作答之后**，装闸一律在 `step_end`（§1.10）；
> ⑤ **`allow` 三态 + 下标只映射一次 + 全屏 STOP 层**（§1.5 / §1.12）；
> ⑥ **第七关几何起点距离 9 不是 11**（Q-07 / 附 A）；
> ⑦ 多席位、`overload_div`、抽取点补全、`state:"solid"`、测试登记、工期 33 → **37**（纪律 8/9、§1.6、§1.7、④、附 C）。

---

## 0. 一句话与三条硬边界

把「教程」从**代码**变成**数据**：一关一份 JSON，`world` 段逐字就是 `cwxworld/2`
（`game/tests/cw_case_loader.gd:32-45` 的 15 / 5 / 12 / 33 键表），规则改动只写 `tuning`（白名单
`game/tests/contract_tune.json`，65 条），预设结果只写 `rolls`（`[[from,to,value]…]`），
小棋盘只写 `active_tiles`（格集合），提示 / 禁用 / 演出只写 `steps[]`。

代码侧只剩四件：
1. **一个装载器搬家**（`game/tests/cw_case_loader.gd` → `game/scripts/kernel/cw_world_loader.gd`，带子 `RollTape` 一起上提）；
2. **一个舞台** `scripts/kernel/cw_tutorial_stage.gd`（读数据 → 装世界 → 挂带子 → `kernel.open` → **返回 `CWKernel`**）；
3. **一个数据门面**（今天的 `guide_data.gd` 退成读 JSON 的门面，`guide.gd` 的步进器一行不改）；
4. **一个脚本 decider**（NPC 按语义键作答）。

`guide_director.gd` 整份删掉，结构闸 `t_no_engine_in_ui` 的白名单从两条降到一条。

**三条硬边界（Kevin 09-18 / 09-19 拍板，本方案逐条守住）**

| 边界 | 本方案怎么守 | 见 |
|---|---|---|
| 教程不依赖 GD 内核；C# 要提供「直接灌一个盘面」的入口 | 开局一律走 `cwxworld/2` 装载器（两侧同一份键表、闸二 2b 证过逐字段相同）；教程**不再需要任何「不在 cwxworld/2 里」的引擎字段**（`win_checks` 整条消掉） | §2.3 / §2.4 |
| UI 只读 `CWMirror`、只经 `CWKernel` 句柄作答、演出走 `CWPlayQueue` | 舞台住 `scripts/kernel/`，`open_level()` 返回类型写 `CWKernel`；`match.gd` 整份不出现 `CWGame` | §2.1 |
| 规则代码不许为教程改行为；老 `check()` 一条不删 | 落不到旋钮的一律落到「数据（盘面 / 能量 / 重装）」或「纯演出层」；每一片自带老测试的改判清单，附 B 逐条列 | §1.6 / 附 B |

数据驱动在这个仓库里有一份别处拿不到的红利：关卡的 `world` 段既是教程数据、又是一条合法的 L0 用例，
`dump_world(load_world(spec)) ≡ minify(spec)`（闸二 2a 的比法，`cw_case_loader.gd:12-14`）当场就能当
「教程盘面写错了没有」的护栏，一行测试口径都不用新写。

---

## ① 架构

### 1.1 三级结构落在**今天的两级步进器**上（不新建第二套步游标）

PRD 是三级：章（第一 / 二 / 三章，PRD:89 / 285 / 413）→ 关（第一~第七关）→ 步（流程 1. 2. 3. …，PRD:19-29）。
今天 `CWGuide` 是两级：`_chapter` / `_step`（`guide.gd:65-66`），而**今天的一「章」就是一关**
（`CWGuideData.CHAPTER_COUNT := 16`，`guide_data.gd:8`）。

映射（这是本方案省下最多改动的一条）：

| PRD 的层 | 落在哪 | 出处 |
|---|---|---|
| 章 | 关卡数据的 `chapter` / `chapter_title` 字段；**值变了就弹全屏章节提示** | PRD:35 / 89 / 285 / 413 |
| 关 | 一条 `CWGuide` 的「章」（`_chapter`）= **一份关卡 JSON = 一次换局** | PRD:91 / 141 / 223 / 287 / 329 / 415 |
| Step | **同一份 JSON 里 `steps[]` 的一个分段**（`steps[].step_of: "Step1"`），**不换局** | PRD:141 / 183 / 245 / 263 / 331 / 353 |
| 步（流程序号） | `steps[]`（`_step`） | PRD:19-29 |

**「Step ≠ 关」是修订版改掉的第一条**（初稿把每个 Step 各算一关、各装一次盘面，切断了 PRD 的关内连续性）：

- **第三关**（PRD:223-283）：`界面变化` / `游戏状态变化` 写在**关级**（PRD:225-243），能量
  `迁移最少能量 + 三次攻击 + 一次失效自损 + 0.1`（PRD:241-243）是**整关一个预算**；
  Step1 的任务是「用**最少**能量迁移」、自动重置条件判的是「移动到癌细胞相邻格所剩的能量小于预期」（PRD:247-251）。
  Step2 一重装，Step1 的整堂课与重置判据当场作废。⇒ **第三关 Step1 → Step2 不 `load`**。
- **第二关**（PRD:141-221）：Step1 玩家亲手净化两格（PRD:155-171），Step2 才「右侧延伸出一格癌组织 +
  生成剩余 1 点能量的癌细胞」（PRD:187-193）。重装就得把「玩家净化过哪两格、人站哪」重新写死。
  ⇒ **第二关 Step2 也不 `load`**，改用「预置 + 遮罩揭示」（下一条）。
- **第五关 Step2**（PRD:359-367）的「使已有癌组织连通块扩大」是把**已经露出来的健康格**改成癌组织，
  遮罩揭示不了 ⇒ 这一段**确实要 `load`**，是全案仅有的两处关内重装之一（另一处是第七关，§1.4）。

**关内状态变化的落点优先级（定死一条，`t_tutorial_data` 核）**：
1. **能预置的一律预置 + 遮罩揭示**（零重装，玩家做过的事全留住）——
   新细胞 / 新癌组织只要在**活跃格之外**就看不见也点不到（`hex_at` 只扫活跃集，§1.9），
   到该露的那一步把坐标加进 `active_tiles` + 浮现动画（PRD:45）即可，**细胞贴图跟着遮罩走**（§1.9 那条 `match.gd:1622`）。
   **第一 ~ 五关从不结束回合**（§2.3）⇒ 预置的对手席永远轮不到、不会自己动；
   **第七关会结束回合**，所以那一关预置的 T / B 细胞（PRD:499）必须是**脚本 decider 管的席位**（§1.8）：
   脚本没给这一席写键 ⇒ 走「停手」兜底（`data.stop` / `data.skip` 那条选项），露之前不会自己乱走。
2. 预置不了的（把已露出的格改性质、换阵营 / 癌种、击退、复活后拨能量）→ `steps[].load` 重装（§1.4）。
3. 两条都落不到 → 纯演出层。

于是：
- `guide.gd` 的两级步进器**一行不用改**。它有 16 行引用 `CWGuideData`
  （`guide.gd:104 / 251 / 257 / 274 / 303 / 334 / 351 / 367 / 369 / 387 / 414 / 420 / 421 / 429 / 431 / 446`），
  这些调用**全部原样保留**，只是 `guide_data.gd` 的实现从 16 个硬编码的 `_stage_*()`（`guide_data.gd:79-277`）
  换成读 `game/data/tutorial/*.json`。
- 跨关换局照走今天的 `on_chapter_done → _advance_tutorial_chapter`（`guide.gd:266-267`、`match.gd:520-554`）。
- 关与关「静默切换」（PRD:37）= `chapter` 字段没变就不弹提示，其余原样。

**不新建 `guide_engine.gd`**。两版候选稿里那条「新解释器 + 老 `guide_data` 并存」的路子会造出**两套步游标**，
直接废掉。解释职责分给两处：数据门面（`guide_data.gd`，纯静态读 JSON）+ 舞台（`cw_tutorial_stage.gd`，装世界 / 重装）。

**`guide_data.gd` 的去向（逐条）**：退成门面，公开面**签名全保留**，实现换数据源：

| 今天 | 退成门面之后 | 调用方 |
|---|---|---|
| `CHAPTER_COUNT := 16`（`:8`） | `CHAPTER_COUNT` = `index.json` 的**关**数（本 PRD 是 **6**：一 / 二 / 三 / 四 / 五 / 七关；Step 不算关，见上） | `guide.gd` 7 处、`match.gd:468/491/534`、`cw_guide_progress.gd:43/48` |
| `CODEX_PAGE`（`:11`） | 每关 JSON 的 `codex_page` 汇总 | `guide.gd:303` |
| `UI_STAGE`（`:17`）/ `ui_stage()`（`:46`） | 每关 JSON 的 `ui_stage`（0~3，语义不变） | `guide.gd:351`、`match.gd:1412`（`ui_stage() >= 1` 才提亮） |
| `chapter_titles()` / `chapter_subtitles()`（`:20/29`） | JSON 的 `title` / `subtitle` | `guide.gd:421` |
| `steps()` / `chapter_step_count()` / `total_steps()`（`:51/42/72`） | JSON 的 `steps[]` | `guide.gd:251/334/414` |
| `act_of()` / `watch_of()`（`:278/286`） | `steps[].act` / `steps[].watch` | `guide.gd:387`、`guide_bridge.gd:112/131` |
| `graduation_assist()`（`:294`） | **返回 `{}`** —— PRD 没有毕业战。`guide.gd:367-369` 已经用 `_chapter != CHAPTER_COUNT - 1` 挡住，行为退化成「不给辅助」 | `guide.gd:369/431` |

**步的切法（定死一条规则）**：PRD 流程里每出现一个 `【O-玩家】`（PRD:21）就切一个 step 边界。
一个 step = 「若干句文本提示 + UI 提示 + 一段可操作窗口 + 一个完成判据」；纯文本的连续序号合并进同一个 step 的 `b[]`。
例：第二关 Step1 的流程 7 条（PRD:161-177）里有两个 `O-玩家`（PRD:169 / 177）⇒ 切成 **2 个 step**。
这条规则让「PRD 序号 ↔ 数据 step」可逐条对账，复核者拿 PRD 就能数。
PRD 的 Step 只是给这些 step 打一个 `step_of` 标签（对账用），**不切关、不换局**。

### 1.2 关卡数据 `cwtut/1`：一关一份 JSON

放 `game/data/tutorial/`，**不是 `game/tests/`**：`game/export_presets.cfg` 四个预设**全部**写着
`exclude_filter="tests/*"`（`:11` Windows / `:56` macOS / `:127` Android / `:155` Web），住 `tests/` 的东西不进导出包。

```
game/data/tutorial/
  index.json                ## 关表：[{id, chapter, chapter_title, title, ...}] → 目录按钮（PRD:43）与全屏章节提示（PRD:35）读它
  levels/c1_l1.json         ## 第一关 免疫        PRD:91-137
  levels/c1_l2.json         ## 第二关（Step1 + Step2 同一份，零重装） PRD:141-221
  levels/c1_l3.json         ## 第三关 ATP（Step1 + Step2 同一份，能量一个预算） PRD:223-283
  levels/c2_l4.json         ## 第四关 抗原记忆     PRD:287-327
  levels/c2_l5.json         ## 第五关 分化（Step2 一次关内 load）  PRD:329-383
  levels/c3_l7.json         ## 第七关              PRD:415-503
  cutscenes/opening.json    ## 开场动画（PRD:59-87）：纯演出，不建内核
  cutscenes/interlude.json  ## 间章「癌变」（PRD:385-411）：演出 + 若干次重装
  codex_map.json            ## 图鉴解锁点 → 知识之书条目 id（PRD 里 12 处「图鉴解锁」）
```

PRD 的「关卡通用设计模板」（PRD:5-30）五段，逐段落成数据字段：

| PRD 模板段 | 出处 | 数据字段 |
|---|---|---|
| 1. 界面变化 | PRD:11 | `steps[].ui_layers`（增量覆写，关首在 step0 给全量）+ `steps[].reveal`（活跃格增量 + 浮现） |
| 2. 游戏状态变化 | PRD:13 | **优先预置进 `worlds.base` + `reveal` 揭示**；预置不了的才 `worlds{}` + `steps[].load`（§1.1 / §1.4） |
| 3. 玩家任务 | PRD:15 | `steps[].watch`（完成判据，只读 `CWMirror`；查 `CWGuideWatch.KEYS`，`guide_watch.gd:27`） |
| 4. 自动重置条件 | PRD:17 | `steps[].reset_when`（重置目标 = **关首**那一份 world） |
| 5. 流程（序号 + 「操作」分隔） | PRD:19-29 | `steps[]` 本身；`step_of` / `t` / `b` / `flag` / `hex` / `act` / `watch` / `allow` / `unlock` / `fx` / `load` / `reveal` / `ui_layers` / `reset_when` |

**骨架（真样例：第二关整关，Step1 + Step2 同一份、零重装，PRD:141-221）**

```jsonc
{
  "schema": "cwtut/1",
  "id": "c1_l2",
  "chapter": 1, "chapter_title": "Cell", "title": "第二关 癌",
  "codex_page": 1, "ui_stage": 0,
  "seats": 2, "human_seat": 0,          // 纪律 8：席位数与人类席，match.gd 据此设 player_count / human_players

  // ---- 开局 = cwxworld/2，顶层 15 键一个不多（cw_case_loader.gd:32-35）----
  "worlds": {
    "base": {
      "radius": 6,                      // 全程 6，理由与后果见 §1.3
      "round": 1,
      "phase": "PlayerAction",          // 不是 round_start：从行动回合中途开局，S 阶段一条都不跑 ⇒ 零 rng 消耗
      "seat": 0,
      "players": [
        { "seat": 0, "faction": "immune", "level": "I", "memory": 0 },
        { "seat": 1, "faction": "cancer", "cancer_type": "Melanoma" }   // 癌席 cancer_type 必填、无 "none"（cw_case_loader.gd:322-327）
      ],
      "tiles": [
        { "at": "3,-1", "state": "cancer" },   // Step1 要玩家亲手净化的两格（PRD:155）
        { "at": "4,-1", "state": "cancer" },
        { "at": "5,-1", "state": "cancer" }    // Step2 才揭示（PRD:187）：先摆在活跃格之外
      ],
      "cells": [
        { "seat": 0, "type": "ImmuneBasic", "at": "0,-1", "energy": 99990 },  // 向右移动四格 = (1..4,-1)
        { "seat": 1, "type": "Melanoma",    "at": "5,-1", "energy": 10 }      // 1.0 能量；同样先在遮罩外
      ]
      // "tuning" 省略 ⇒ _load_tuning 在 tuning 为空时直接返回（cw_case_loader.gd:438-440），整关零旋钮
    }
  },

  // ---- 活跃格集合：小棋盘的唯一口径（不是半径）。关首 = Step1 的六格（PRD:143）----
  "active_tiles": ["-1,-1","0,-1","1,-1","2,-1","3,-1","4,-1"],

  // ---- 预设骰子：与 cwxcase/2 的 rolls 同形（[[from, to, value] …]）----
  "rolls": [[1, 6, 3]],                 // 整关一次攻击、结果成功。次序论证见 §1.7

  "steps": [
    {
      "step_of": "Step1",
      "load": "base",                   // **关首唯一一次装 world**；后续 step 不出现 load ⇒ 全关零重装
      "ui_layers": { "action_bar": ["move"], "sidebar": [], "hand": false,
                     "end_turn": false, "round_no": false,
                     "move_path": false, "cost": false, "energy_display": "plain" },
      "t": "！！！", "b": ["发现**癌组织**，立即执行清除程序！",
                          "使用【迁移】移动到**癌组织**，将其【净化】"],   // PRD:161-167
      "unlock": ["tissue_cancer"],                                        // PRD:165
      "flag": "move", "hex": ["1,-1","2,-1","3,-1"], "player": true,
      "allow": ["k=action|act=move"],                                     // 语义键前缀，见 §1.5
      "watch": "tile_healthy:3,-1"                                        // PRD:169 的 O-玩家 到此为止
    },
    {
      "step_of": "Step1",
      "t": "当迁移到癌组织上时，会自动将癌组织转为健康组织",               // PRD:173
      "unlock": ["purify"],                                               // PRD:175
      "flag": "move", "hex": ["4,-1"], "player": true,
      "allow": ["k=action|act=move|to=4,-1"],
      "watch": "tile_healthy:4,-1"                                        // PRD:177
    },
    {
      "step_of": "Step2",
      "reveal": ["5,-1"],               // 浮现一格（PRD:187/45）——**不是重装**：格与癌细胞本来就在盘上，只是先被遮罩挡着
      "t": "！！！", "b": ["发现敌人**癌细胞**", "发起攻击"]                // PRD:209-213
    },
    {
      "step_of": "Step2",
      "t": "试图【迁移】到癌细胞所在组织可以发起攻击",                      // PRD:215
      "flag": "move", "hex": ["5,-1"], "player": true,                     // PRD:221
      "allow": ["k=action|act=move|to=5,-1"],
      "watch": "cancer_dead"                                               // PRD:203
    }
  ],

  "on_done": "c1_l3"                    // 静默切下一关（PRD:37）
}
```

**九条数据纪律**（写在 `index.json` 的文件头注释里，`t_tutorial_data` 逐条核）：

1. `worlds.*` 的键**只许**是 `cw_case_loader.gd:32-35` 的 15 个；每一份都要能过 `load_world`
   且 `dump_world ≡ minify`（闸二 2a 的比法）。
2. **省略 `type` = 棋盘本来的特殊组织**（`cw_case_loader.gd:11-12`、`CWData.special_of`，`cw_data.gd:968-975`）。
   特殊格坐标清单（`cw_data.gd:529-534`）：核心 `(0,-3)` `(3,0)` `(-3,3)`；骨髓 `(3,-3)` `(0,3)` `(-3,0)` `(6,-3)` `(-3,6)` `(-3,-3)`；
   血管 `(6,0)` `(-6,0)`。**凡活跃格里压到这 11 格的，逐格显式写 `"type": "normal"`**，否则白送一个收入格。
   （反过来看：这 11 格的 `r` 只取 `-3 / 0 / 3 / 6` 四个值 ⇒ **`r = -1` 与 `r = -2` 两整排零特殊格**，见附 A。）
3. 能量一律写**十分位整数**（`INIT_ENERGY := 30` = 3.0，`cw_data.gd:76`）。
4. **一格一细胞**（`cw_case_loader.gd:274-281` 装载期拦，**连 `alive:false` 的死细胞一起数**），
   **一席一细胞**（`:303-308` 按 pid 重绑 `cell_id`，同席写两只**后写的静默盖掉**）
   ⇒ PRD 的「若干癌细胞」「一圈免疫细胞」逐只展开成席位。`players[i].seat` 必须等于 i（`:310-312`）。
5. 多个免疫席的 `level` / `memory` 必须一致（GD 是阵营共享量，`cw_case_loader.gd:196-208` 的 `_load_immune_globals`，不一致当场 UNLOADABLE）。
6. 数字**不写死在文案里**：正文里要出现数值就写 `{{tune.attack_dmg_success}}` 这类占位，渲染期从 `CWMirror.tune` 现取
   （沿用今天 `guide_data.gd` 的纪律与 `dump_guide.gd:27-28` 的导出口径）。
7. **不许绕过 `_load_tuning` 直接 `g.tune.set(...)`**，也**不用 `cfg["rules"]` 那条路**
   （`cw_kernel_inproc.gd:66-67 → restore_rules_state` 是无校验裸 set，且只在**非 adopt** 路生效，教程走 adopt 本来也用不上）。
   绕过去就等于把四档白名单（`cw_case_loader.gd:459-468`）绕过去了。
8. **席位数是设计量，不是副产品**。`players[]` 的条数 = 引擎的 `order.size()`，而**一串按人数分档的表**直接读它：
   记忆门槛 `CWData.level_min_memory(order.size())`（`cw_game.gd:997` → `cw_data.gd:277`）——
   表里**只有 4 人一档** `{4: [0,10,20,50]}`（`cw_data.gd:272`），**其余人数一律回落六人档** `[0,10,30,70]`（`:260`）；
   有氧基数 `AEROBIC_LEVEL_BASE_BY_PLAYERS`（`cw_data.gd:216`）、无氧系数（`:126`）同理。
   ⇒ 每关 JSON **显式写 `seats` / `human_seat`**，且门槛类数值（如第四关的「升到 III 级」）**逐关标定后写进验收**，
   不许照抄别关的数。`match.gd` 的 `player_count` / `human_players` 也从这两个字段来（§2.3 第 5 条）。
9. **固化癌组织写 `state: "solid"`，不是 `solid`**。`tiles[].solid` 是**固化计数**（`cw_case_loader.gd:182`），
   真正的固化组织是 `_tissue("solid")`（`:887-893`）。两种写法都合法 ⇒ `dump ≡ minify` 圆环测试**抓不到**这个错，
   所以要单列一条断言：凡剧本文案/复活点提到固化的关，盘面里必须有 `state == "solid"` 的格。
   第七关更要命 —— 复活点（PRD:495）与免疫胜利兜底（§2.3）都押在这一格上。

### 1.3 世界半径：**全程 `radius: 6`**（含理由与后果登记）

先把事实摆正：**`radius` 是 `cwxworld/2` 的顶层可写键，不是常量**——
它是 `WORLD_KEYS` 的第一个键（`cw_case_loader.gd:32`），装载器按它建盘
（`:139-140` `g.board_radius = int(spec.get("radius", CWData.BOARD_RADIUS))` → `g.setup.build_board(...)`），
`dump_world` 在 `!= 6` 时写回（`:507-508`），C# 侧同有 `spec.Radius`
（`core/CellWar.Core.Tests/L0/WorldLoader.cs:32 / :38 / :167 / :400`，默认值在 `L0/CaseModel.cs:101`）。
`cw_data.gd:16` 的 `const BOARD_RADIUS := 6` 只是**默认值**。今天的教程正是每关自选半径
（`guide_director.gd:35` 用 `CWGuideLevels.radius(level)`，老半径表被 `headless_test.gd:10959` 钉成
`[1,2,2,2,3,3,3,3,4,4,4,4,4,4,4,6]`）。

**本方案选「全程 6」，理由三条（都不是「半径不可变」）：**

1. **关内长地图靠遮罩、不靠重装**。PRD 有四处关内 / 关间长地图：第二关 Step1 右侧延伸两格健康两格癌（PRD:143）、
   Step2 再延伸一格癌（PRD:189）、第三关自免疫细胞向前方延伸（PRD:227）、第四关向周围延伸（PRD:291）。
   半径固定 ⇒ 长地图只是 `set_active_tiles` 加几个坐标 + 浮现动画（PRD:45），**零重装**；
   半径随关变 ⇒ 每次长地图都要 `build_board`，就得跑一遍拆装序列（`match.gd:527-534`），
   而 PRD:45 要的是「浮现」，不是「整盘重来」。
2. **第七关必须半径 6**。【转移】固定跃进 5 格（`METASTASIS_RANGE := 5`，`cw_data.gd:341`）⇒ PRD:481
   「点击若干次转移正好到 T 细胞相邻格」要求距离 = 5k+1；k=2 即距离 11。
   半径 6 的盘上第 `r` 排长度 = `13 − |r|`（由 `is_on_board`，`cw_data.gd:876-878` 推），
   `r = -1` 排正好 12 格（q ∈ [-5, 6]）⇒ 端到端距离恰好 **11**。统一半径 6 就不用为一关单开一套几何。
3. **一条教学带贯穿三章**。`r = -1` / `r = -2` 两整排零特殊格（纪律 2 的推论），
   第一 ~ 三章的教学直线与第七关的 5k+1 直线可以是**同一排**（附 A 给逐关坐标提案）。

**后果登记（一条不许漏）**。修订版把这张表**整体**挂在 **S3**：它们全都要等「新第一关的盘面」
与 `CWMatch.tutorial_active_tiles()` 真的存在，而那是 S2（数据）+ S3（接线）的产物 ——
S1 只动 `board.gd`，改不动这些（见 ③ S1）。

| 老断言 | 出处 | 改成 |
|---|---|---|
| `m.mirror.tiles.size() == 7` | `headless_test.gd:20613` | `== 127`（世界半径 6） |
| `m.mirror.board_radius == 1` | 同上 | `== 6` |
| `m.board.active_radius == 1` | 同上 | 换成「活跃格集合 == 第一关那两格」 |
| `m.board.map.size() == 127` | 同上 | **不变**（格网常驻，Kevin 09-11 口径） |
| `m.board.active_radius == 1 && tile_shown((1,-1)) && !tile_shown((2,0)) && hex_at(center(1,-1)) == (1,-1)` | `headless_test.gd:10679-10682` | 按新第一关的两格盘面改判 |
| `CWMatch.tutorial_board_radius() == CWGuideLevels.radius(...)` | `headless_test.gd:10683` | 改判为 `tutorial_active_tiles()` |
| `main.gd` 源码含 `set_active_radius(CWMatch.tutorial_board_radius(` | `headless_test.gd:10686` | 串换成 `set_active_tiles(CWMatch.tutorial_active_tiles(` |
| 老半径表 `[1,2,2,2,3,3,3,3,4,4,4,4,4,4,4,6]` | `headless_test.gd:10959` | 随 `t_guide_director` 整体改判（S3） |

`t_board_small`（`headless_test.gd:7794-7822`）**不受影响**：`set_active_radius` 保留成薄壳（§1.9）。
`t_snapshot` 里「棋盘半径要跟着存档走」那两条（`headless_test.gd:12375-12385`）与教程无关，一字不动。

**代价（老实写）**：遮罩外的 127 格是真实的。任何会跑 E 阶段的关（本方案里只有第七关）
的增生 / 侵蚀 / 压迫都会在玩家看不见的地方发生 —— 处置见 §1.6 与 Q-04。

### 1.4 同一关多份 world：`resolve` + `reload_world`

PRD 里「规则根本没有的状态改动」逐条过一遍 `预置 + 遮罩` 这把筛子（§1.1 的优先级 1）：

| PRD 要的改动 | 出处 | 落点 |
|---|---|---|
| 第二关 Step2 延伸一格癌组织 + 生成 1 能量癌细胞 | 187-193 | **预置 + `reveal`**（零重装，玩家净化过的两格留住） |
| 第七关末尾地图边缘再生成若干 T / B 细胞 | 499 | **预置 + `reveal`**（席位一开始就在，细胞停在活跃格外） |
| 第五关 Step2 使**已露出**的癌组织连通块扩大 | 361 | ✗ 改的是已经看得见的格 ⇒ **`load`** |
| 击退 2 格（两次） | 469 / 473 | ✗ **`load`** |
| 癌种切换为印戒细胞癌 | 489 | ✗ **`load`**（癌种在 `players[]` 上，`g.init` 时定死） |
| 间章脚下生成固化癌组织 + 一环击退 1 格 | 411 | ✗ **`load`** |
| 间章阵营翻转（免疫 → 小细胞肺癌） | 403 | ✗ **`load`**（阵营同上） |
| 分化种类来回切 | 355 | ✗ **`load`**（规则里分化是一次性的） |
| 复活后把能量从 2.0 拨回 Null 大数 | 431 / 495 | ✗ **`load`**（Q-11） |

席位表、阵营、癌种**都不是可增量改的字段**（席位 order 在 `g.init(order, 1)` 时就定死，
`cw_case_loader.gd:131-138`），落到 ✗ 的只有一条路：**同一关多份完整 world，step 指名换一份**。
**全案关内重装只剩两处：第五关 Step2 一次、第七关十来次**（第七关本来就是强制演出，PRD:429）。
第五关 Step2 的重装会把玩家在 Step1 选的分化种类冲掉 —— 可接受：**同一步就出现「切换种类」按钮**
（PRD:355「允许免疫细胞玩家自由选择分化类型」），玩家立刻能改回来，所以不做「带着当前种类重装」那套机关。

数据里允许继承，省得 25 步写 25 份完整盘面：

```jsonc
"worlds": {
  "base":   { /* 完整 cwxworld/2 */ },
  "knock1": { "from": "base",   "patch": { "cells": [ { "seat": 4, "at": "1,-2" } ] } },
  "signet": { "from": "knock1", "patch": {
      "players": [ { "seat": 4, "cancer_type": "SignetRing" } ],
      "cells":   [ { "seat": 4, "type": "SignetRing" } ] } }
}
```

**继承在教程侧的纯函数 `resolve(level, world_id) -> Dictionary` 里做完，装载器拿到的永远是一份完整 spec**
—— `cw_case_loader.gd` 文件头第 2 条「loader 不编数据」一个字都不动。
`patch` 的语义只定四条：`tiles` 按 `at`、`cells` / `players` 按 `seat` 做 upsert；值写 `null` = 删这一条；
顶层标量直接盖；数组不合并。测试对每个 `world_id` 跑一遍
`resolve → load_world → dump_world ≡ minify(resolve)`，写错当场红。

**`reload_world(world_id)` = 拆装序列的短路版**：复用 `_advance_tutorial_chapter`（`match.gd:520-554`）
的拆装序列，**跳过「算关 / 换席位 / 重挂面板」三段**：

```
kernel.abort() → queue.stop() → kernel.close() → stage.dispose()
  → resolve/load_world → kernel.open({adopt, consumer:true, observe_viewer:OMNISCIENT, autorun:false, decider/deciders})
  → _start_queue() → kernel.run() → _observe_now()
```

- **`abort` 永远排在 `stop` 之前**（`match.gd:524-527` 注释原文：只有 `abort()` 里的 `_barrier_seq = 0`
  能放掉正在等 ack 的那条 roll；先停队列就没人 ack，5 秒后内核报 barrier timeout，`tools/run_tests.sh` 当场判红）。
- **adopt 模式的 `close()` 不 dispose**（`cw_kernel_inproc.gd:102-114`「谁装配谁收摊」，`match.gd:531-533` 正是照这条写的）。
- **换局会新建一个桥**（`_wire_bridge`）⇒ **必须把同一个 `_guide` 重挂上去**
  （`match.gd:539-546` 的注释原文：不重挂新桥的 `guide` 是空的，`CWGuideBridge` 每处判空于是不崩，
  但从第 2 关起提示、演示、「继续」代做**全部静默失效**；PR 原样就是漏的）。
  `reload_world` 跳过的是「重建面板」，**不是「重挂」** —— 这条一定要抄过来。

重装之后的「细胞从 A 挪到 B」不需要任何新信号：`CWTeleportFx` 早就是**靠 UI 自己做状态差分**认出来的
（`teleport_fx.gd:8-9`「引擎零改动、不加信号」，判定在 `CWMatch._sync_cells()`）。
击退 2 格、癌种切换照这条办：数据换一份，UI 差出来自己演。（边缘新增 T / B 细胞走的是**预置 + reveal**，见上表。）

### 1.5 允许的决策：**过滤视图**（不是协议里的 `blocked`）

每步一个 `allow`，**三态**（初稿写成两态，「空集 = 不过滤」与「空集 = 全禁」撞了）：

| `allow` | 语义 | 用在哪 |
|---|---|---|
| 缺省（`null`） | 不管，引擎给什么就是什么 | 自由游玩段 |
| `[]`（空数组） | **全禁**：这一问挂起不作答，直到闸放开 | 提示 / 对话播放期（PRD:51） |
| 非空 | 只留命中的选项（前缀匹配语义键） | 每一个可操作 step |
| 非空但**一条都没命中** | = 剧本写错：**打 warning + 挂起**（同全禁），出路是常驻「重置 / 目录」按钮 | —— 初稿在这儿回落成「不过滤」，等于剧本一错就全开，改掉 |

判法住在教程桥里（与 `mutes_result` 同一条隔离纪律，`guide_bridge.gd:57-64`）：

```gdscript
## guide_bridge.gd（今天 ask 已经是覆写点，:68-75）
## _allow: Variant —— null / [] / [前缀…]；由 on_step(step_end) 装（§1.10）
func ask(req: Dictionary) -> int:
    if _allow == null or not (req["pid"] in human_pids):
        return await super.ask(req)
    ## ★ 必须先等队列播到这一步：_allow 是 on_step 收到 step_end 才装的，
    ##   而 CWUIBridge 的 _await_playback() 在 super.ask 内部（ui_bridge.gd:199-205 → :236-240），
    ##   不自己先等一次，这里读到的还是上一步的闸。
    await _await_playback()
    while _allow != null and _allow.is_empty():        ## [] = 全禁：挂起，连行动栏都不建
        await _allow_changed                           ## 提示播完、step 的真 allow 装上来
    if _allow == null:
        return await super.ask(req)
    var keep := []                                     ## view 下标 → 原表下标
    for i in req["options"].size():
        if _hit(CWSemKey.key(req, req["options"][i]["data"]), _allow):
            keep.append(i)
    if keep.is_empty():
        push_warning("剧本 allow 在这一问里一条都没命中：%s" % str(_allow))
        while true:                                    ## 打日志 + **挂起**，绝不回落成全开、也不替玩家乱答
            await _allow_changed                       ## 出路是常驻「重置 / 目录」按钮（PRD:41/43，提示期也可点）
            if _allow == null or not _allow.is_empty():
                return await ask(req)                  ## 闸换了就重来一遍
    var view := req.duplicate()
    view["options"] = keep.map(func(i): return req["options"][i])
    _view_map = keep                                   ## 「继续」代做要用（见下面「继续」那一条）
    return keep[await super.ask(view)]                 ## 下标映射回原表
```

- 每条选项在观测协议里**已经带着语义键**（`cw_obs_codec.gd:308` 写 `"key": CWSemKey.key(req, data)`），
  `CWSemKey` 的文法 `k=<kind>[|g=<tag>]|<field>=<v>|…`、字段固定顺序（`cw_semkey.gd:20-21` 的 `KEY_FIELDS` 13 个）
  与 C# 的 `core/CellWar.Core/SemanticKey.cs` **逐字相同**（`cw_semkey.gd:5`）。
- 行动栏就是从 `req["options"]` 建的（`ui_bridge.gd:247-262` 的 `_ask_action`）⇒ 过滤掉的按钮**根本不出现**。
- **「继续」代做要跟着走 view，不然下标映射两次**：`_cur_req` 今天存的是**原始 req**（`guide_bridge.gd:70`），
  `_demo_index()`（`:109-115`）→ `_pick()`（`:146-172`）算的是原表下标，`take_offer()`（`:97-105`）
  直接 `p.fire(idx)` 唤醒挂在 `super.ask(view)` 上的那一问 —— 返回值再被 `keep[...]` 映一次 = 选错或越界。
  **定死**：`ask()` 里 `_cur_req` 存**过滤后的 view**，`_pick` / `_guide_key` / `current_hint` 一律在 view 上算
  （玩家看见的就是 view，提示也该按 view 说）。`t_guide_gate` 加一条断言：
  「`allow` 生效时按『继续』，落到的是被点名的那个选项」。
- **不走协议里的 `blocked` 槽**：`cw_obs_codec.gd:312` 恒写 `"blocked": null`，而
  `game/scripts/ui/` 里**没有任何一处读 `option.blocked`** —— `ui_bridge.gd:627 / 782-826` 的 `blocked`
  是「点了不在选项里的格子时问一句为什么」的 `Callable`，另一回事。走那条路要顺带新写行动栏的置灰渲染，不划算。
  （将来若要「灰显而非隐藏」，再补 `ui_bridge.gd` 的渲染端，协议侧已有槽，届时是加法。）

这一条同时解掉四件 PRD 要求：PRD:429「仅可点击 UI 提示的部分」、PRD:433「六向仅允许 UI 提示的方向」、
PRD:51「提示 / 对话开始后所有操作禁用」，以及**把「结束回合」关在门外**
（第一 ~ 五关；第七关要真点，见 §2.3）—— 后者是 §2.3 里 `win_checks` 那条能整个绕开的关键。

**PRD:51 的「全部操作禁用」要两层，缺一不可**：

1. **闸这一层**：`allow = []` ⇒ 这一问挂起、行动栏根本不建（上面的 `while`）。
2. **点击这一层**：另起一个**真·全屏 `Control`**（`MOUSE_FILTER_STOP`），z 序盖在棋盘与行动栏之上、
   排在引导浮层与常驻「重置 / 目录」按钮**之下**（那两个按钮提示期照常可点，PRD:41/43）。
   **不能指望引导面板自己那层**：`CWGuide.ZONE := Rect2(88, 16, 600, 200)`（`guide.gd:26`，
   `_build()` 在 `:108-110` 把 position/size 设成它）—— 棋盘、行动栏、右栏全在这个矩形之外，
   把它的 `mouse_filter` 从 `IGNORE`（`guide.gd:110`）改成 `STOP` 只挡住浮层自己那 600×200，挡不住别的。

### 1.6 规则改动：逐条落到旋钮名，落不到的落到「数据」或「纯演出」

`contract_tune.json` 65 条，**实测分档 A 35 / A′ 3 / B 6 / C 21**。装载器只收 A 与 A′
（`cw_case_loader.gd:459-467`：B「C# 无对应物」拒、C「不在白名单」拒），分档表旋钮必须写 1 基下标 `name[1]`（`:472-488`）。

| PRD 要的改动 | 出处 | 落点 | 依据 |
|---|---|---|---|
| 本关【迁移】不消耗能量 | 105 / 149 / 195（**只有第一关、第二关两个 Step**） | ✗ 旋钮 → **大能量 `99990` + `ui_layers.cost=false`** | `immune_move_healthy` / `immune_move_cancerous` 都是 **tier C**，装载器双重拒 |
| 迁移不显示路径 / 消耗 | 107 / 151 / 197 | `ui_layers.move_path=false` / `cost=false` | 纯 UI |
| 第三关能量精确 | 241-243 | **数据 `energy: 51`**（= 5n + 30 + 5 + 1，n=3） | 迁移→健康 0.5（`cw_data.gd:181`）、攻击 = 迁移→癌性 I 级 1.0（`:190`）×3、失效自损 0.5（`COUNTER_DMG_ON_FAIL := 5`，`:382`）、+0.1。**第三关没有「迁移不消耗」那句**，公式与自动重置（PRD:251）才成立 |
| 第三关攻击次数 | 265 | **用默认 `attack_max_per_turn = 3`，不显式写 0** | `ATTACK_MAX_PER_TURN := 3`（`cw_data.gd:376`）正好把带子长度锁死：打不出第四次 ⇒ 带子永不 overrun 回落真 rng（`l0_runner.gd:80-82`）。代价是误点会看到「次数已用尽」通报（`cw_actions.gd:801-807`），教程里可接受 |
| 不设攻击次数上限 | 303 | ✓ **`attack_max_per_turn: 0`** | tier A；`cw_actions.gd:801-802` 是 `if cap > 0`，0 = 不限 |
| 无限能量、显示 ∞ | 301 / 369 | **大能量 + `ui_layers.energy_display:"infinity"`** | `energy_cap` 默认 0 = 不封（tier A，不需要拧）。**渲染点三处**：`match_panel.gd:325` / `tile_info.gd:144` / `ui_bridge.gd:624`，都是 `CWData.fmt(...)`，三处一起改才不会漏。**只核 `energy_cap` 不够** → 见下一行 |
| 大能量别被【能量过载】啃掉（**凡跑 E 阶段的关必写**） | — | ✓ **`overload_div: 0`** | `cw_world.gd:468-478` 的 `overload_loss`：能量超过 `overload_threshold`（默认 100 = 10.0）就按 `((x−10)/div)^1.18` 扣、单次封顶 `overload_cap`（150 = 15.0），**`overload_div <= 0` 才整条关掉**（`:469-470`）。四个旋钮 `overload_threshold` / `overload_div` / `overload_exp` / `overload_cap` **全是 tier A**（`contract_tune.json:26-29`），默认值在 `cw_data.gd:173-176`。不拧的话第七关每个世界回合都给 99990 那只默默扣 15.0 并写一行日志（数值无所谓，日志会跑进 CWFeed） |
| 癌细胞能量 Null、内部无限 | 431 | **大能量 + `energy_display:"null"`**（同上三处） | 复活后引擎给 2.0（`REVIVE_ENERGY := 20`，`cw_data.gd:368`）⇒ 复活那一步 `load` 一份新 world 把能量拨回（Q-11） |
| B 细胞抗体次数 | 455 | ✓ `antibody_max_per_round`（tier A，默认 0 = 不限） | 「恰好三次」靠脚本 decider 点三次 |
| 抗体无视「邻接健康组织」 | 455 | ✗ 无旋钮 → **盘面保证邻接** | 目标集合写死（`cw_actions.gd:1244-1249`）→ Q-06 |
| 【转移】次数 / 费用 | 481 | ✓ `metastasis_max_per_round` / `metastasis_cost`（都 tier A） | 费用已被大能量盖住，写不写都行 |
| 【增生】可复现 | 449 | ✓ **`proliferate_per_adjacent[1]: 0` + `proliferate_per_solid[1]: 0`**（tier A′） | `cw_world.gd:666-667` `if rate <= 0 and per_solid <= 0: return` **在掷骰之前** ⇒ 零 rng 消耗。半径 6 下「真结算」要对全盘每个合格健康格各掷一次（`cw_world.gd:670-681`），带子上百条且多数发生在玩家看不见的格上 → Q-04 |
| 【侵蚀】可复现 | 449 | ✗ `erosion_tiles` 是 tier C → **靠盘面**（这盘一格都侵蚀不到） | `cw_world.gd:596-606` 只吃「不与外缘连通的健康连通块」且跳过免疫所在格；`:617-618` `if eligible.is_empty(): return` 在 `roll_d3()`（`:626`）之前 → Q-04 |
| 世界事件不插进来 | — | ✓ `world_events_on: 0`（tier A） | 默认已是 false，显式写上防回归 |
| 癌方加权胜利不要在第七关弹 | 449 | ✓ `cancer_win_hold_rounds: 99`（tier A） | 要连续达标 N 个回合才判（`cw_game.gd:1119-1125`） |
| 免疫等级门槛 | 307 | ✗ `LEVEL_MIN_MEMORY` 不在 65 条里 → **靠席位数 + 起始 `memory`** | 4 席走 `[0,10,20,50]`，其余回落 `[0,10,30,70]`（`cw_data.gd:260/272/277`） |
| 不判胜负（教学摆拍局） | — | **靠数据，不用 `win_checks`** | 见 §2.3 |
| 反复切换分化种类 | 355 | ✗ 规则里分化是一次性的 → **每次切换 `load` 一份新 world** | 只差玩家那只的 `type`；四种各一份 |
| 击退 2 格 / 癌种切换 / 脚下生固化 | 411 / 469 / 473 / 489 | ✗ 规则没有这条 → **`load` 新 world + 受击特效** | 差分演出走 `CWTeleportFx` 那条先例；逐条落点见 §1.4 的筛子表 |
| 边缘新增 T / B 细胞 | 499 | **预置 + `reveal`**（不是重装） | 席位与细胞一开始就在盘上、停在活跃格外；`hex_at` 只扫活跃集（§1.9）⇒ 看不见也点不到 |
| 效应应答「一直持续」/ 多只齐发 | 463 / 501 | ✗ 无旋钮 → **纯演出** | 每细胞每局 1 次 + 免疫方每世界回合 1 次（`cw_game.gd:1014-1021`） |

**一条纪律**：以上没有一条要求改规则代码。凡是落不到旋钮的，落点只有两种 —— 数据（盘面 / 能量 / 重装）或纯演出层。

### 1.7 预设骰子 `rolls`：抽取点与逐关带子

**抽取点（逐处核过）**

| 时机 | 抽取语句 | 出处 |
|---|---|---|
| 攻击判定 | `rng.randi_range(1, 6)`，**一次攻击恰好一次** | `cw_actions.gd:829` → `cw_game.gd:710-711`（`roll_shown`） |
| 攻击重掷（仅【补体调理】） | 同上 | `cw_actions.gd:832-836`；另【高亲和力克隆】不掷骰直接大成功（`:825-827`）。教程盘面 `mods` / `equipped` 全空 ⇒ 永远一次一抽 |
| 抗体 | `roll_shown(3, "抗体")` | `cw_actions.gd:1275` |
| E-增生 | `rng.randi_range(1, 1000)`，**每个合格健康格一次** | `cw_world.gd:681`（`chance > 0 and …` 短路） |
| E-侵蚀 | `roll_d3()` 一次 + `pick_random` 若干次 | `cw_world.gd:626`；`pick_random` = `pop_at(rng.randi_range(0, n-1))`（`cw_game.gd:841-846`） |
| **E-固化扩散（根深蒂固）** | `pick_random(targets, n)` —— **每个有癌邻格的固化格各抽若干次** | `cw_world.gd:920` |
| 黏液破裂选格 | `pick_random(healthy, MUCUS_MAX_CONVERT)` | `cw_actions.gd:1462` |
| 补体级联选格 | `pick_random(cands, CASCADE_MAX_TILES)` | `cw_actions.gd:986` |
| 突变 | `roll_shown(3, "突变")` | `cw_actions.gd:1375` |
| 血行转移扩散 | `pick_random(spread, HOMING_SPREAD)` | `cw_actions.gd:1432` |
| Excalibur 溅射 | `rng.randi_range(1, 100)` | `cw_actions.gd:1650` |
| 抽卡权重 | `rng.randi_range(1, total)` | `cw_cards.gd:99` |

（初稿这张表只有前六行就写了「逐处核过」，被复核抓住。后七行里，教程真会碰到的是
**E-固化扩散** —— 第七关一定有固化癌组织（复活点，PRD:495），E 阶段必抽。所以
**「增生拧 0 之后第七关的带子只剩攻击 / 抗体」这句话不成立**，第七关的带子只能录制生成，见下表。
补体级联 / 突变 / 血行转移 / Excalibur / 抽卡在教程盘面里 `mods` / `equipped` / `hand` 全空、
卡牌整个关掉（Q-13），抽不到。）

**判定档**（`base_verdict`，`cw_actions.gd:726-730`）：`r == 6` → 大成功；`r <= 2` → 失效；其余（3/4/5）→ 成功。
伤害：成功 `ATTACK_DMG_SUCCESS := 10`、大成功 `ATTACK_DMG_CRIT := 20`、失效自损 `COUNTER_DMG_ON_FAIL := 5`
（`cw_data.gd:377/378/382`）。

**带子实现（指名）**：上提 `l0_runner.gd:61-91` 的内部类 `RollTape` 成
`game/scripts/kernel/cw_roll_tape.gd`，runner 改 preload 它。
**不用 `rig_rng.gd`**：那只吃点数队列；`RollTape` 吃的就是 `cwxcase/2` 的 `[[from,to,value]]` 三元组，
且自带 `overrun` / `bad_range` 两个记账（`l0_runner.gd:65-66`），
退化区间 `randi_range(n,n)` 消耗 0 的口径两侧已对齐（`:78-79`），教程自检直接用。
`rig_rng.gd` / `xcheck_tape.gd` 留在 `tests/` 不动。

**逐关的 `rolls`**

| 关 | PRD | `rolls` | 说明 |
|---|---|---|---|
| 第一关 | 91-137 | `[]` | 全关零抽取。`rolls: []` = **断言这一关一次 rng 都不消耗**（`l0_runner.gd:228-229`） |
| 第二关（S1 + S2） | 141-221 | `[[1,6,3]]` | S1 的净化是「迁移进癌格」的副作用、不掷骰；S2 一次攻击 → 成功。癌细胞 1.0 能量、成功伤害 1.0 ⇒ 一击死（文案与「直到其死亡」的落差 → Q-13） |
| 第三关（S1 + S2） | 239 | `[[1,6,3],[1,6,1],[1,6,6]]` | 成功 / 失效 / 大成功，按玩家三次攻击的先后。伤害 10 + 0 + 20 = 30 = 癌细胞 3.0 能量 ⇒ 第三次刚好死。**整关一条带子**（Step 不换局，所以带子也不断） |
| 第四 / 五关 | 287-383 | **省略** | 玩家自由攻击，带子长度配不准。**不写 `rolls` ≠ 随机**：装载器种子恒为 1（`cw_case_loader.gd:138` `g.init(order, 1)`），同一份 world 每次开局的 rng 序列是同一条。第五关 Step2 的 `load` 会**重开一条 rng**（新 `g.init`），这是重装的固有后果，登记在此 |
| 间章 IN-10 | 409 | `[[1,6,3],[1,6,3],[1,6,3]]` | NPC 免疫攻击玩家三次，全钉「成功」；玩家能量是大数 ⇒ 打不死 |
| 第七关 | 437-503 | **录制生成（每份 world 一条）** | 新增 `game/tests/record_level_rolls.gd`：无头跑完这一关的脚本序列，把抽取序列 dump 成 `rolls`，数据里钉住。**验收 = `_check_tape`（`l0_runner.gd:259-265`）双向归零**（少给了报错、剩下没用掉也报错），**不是**「长度可控」—— 多回合 E 阶段的固化扩散（`cw_world.gd:920`）抽多少次不是人能手算的 |

### 1.8 NPC 脚本 decider：一个纯函数 + 两个 adapter

```gdscript
## game/scripts/kernel/cw_tutorial_npc.gd（不带 class_name，用 preload —— 同 guide.gd:60-62 的热更理由）
## 纯函数：只看「这一问的选项表」与镜像，返回要选的**语义键**；选不出返回 ""
## 兜底**定死三级**：① 选项里 data.stop / data.skip 的第一条（判法同 cw_obs_codec.gd:298-300）；
## ② 顶层 action 问（这一层没有 stop 选项，实测只有卡牌与连续吞噬才有）⇒ 选 `act=end`「结束回合」= 什么都不做；
## ③ 都没有才回落下标 0（基类默认，scripts/core/cw_bridge.gd:17-18）。
## 不这么定的话，一个没写到的席位会在第七关的 E 阶段里按下标 0 自己走一步，把摆拍演出走歪。
static func decide(ask_view: Dictionary, mirror: CWMirror, script: Array, memo: Dictionary) -> String
```

- `script` 从数据来：`"npc": { "2": [ {"policy": "approach", "target_seat": 4},
  {"key": "k=action|act=attack|to=1,-2"} ] }`。两种写法：**直给语义键**（钉死的演出步），
  或**给一条小策略**（`approach` / `attack_if_adjacent` / `end_turn` / `pass` —— PRD:453
  「向任意靠近癌细胞的方向移动一格，如果已经邻接就发动攻击」正好是前两条）。
  策略在教程侧现算目标格再拼成语义键；**不读 `CWGame`**（护栏：`cw_tutorial_npc.gd` 里零 `game.`）。
- **adapter A（InProc，今天）**：一只 `CWBridge` 子类，`ask(req)` 里用 `CWSemKey.key(req, data)`
  逐条算键、返回匹配的下标（基类默认恒选第 0 项，`scripts/core/cw_bridge.gd:17-18`）。
  接线 = `cfg["decider"] = ui_bridge`（所有席位）后再 `cfg["deciders"] = {2: npc, 3: npc, …}` 逐席覆盖
  （`cw_kernel_inproc.gd:70-74`，`deciders.merge(…, true)`）。
- **adapter B（流式，sidecar / Remote 那天）**：`queue.on_ask` 里对 `entry.req.options[].key` 做同样的匹配，
  然后 `kernel.answer(ask_id, {"key": k})`。**同一个 `decide()`，换一层壳；现在就可以写、现在就能测。**

形制事实（写进文件头）：**InProc 下有 decider 的席位不产 `ask` 条目**（`cw_kernel_inproc.gd:399-400`），
且那一问的 `kernel.answer()` 会被拒。两条 adapter 天然互斥、不会打架。

### 1.9 活跃格集合与浮现

`board.gd` 改两处、加一处，**老签名与老字段全保留**：

```gdscript
var _active_set := {}                                                    ## 新增：真正的口径
func set_active_tiles(tiles: Array, seconds := ACTIVE_FADE) -> void      ## 新增
func set_active_radius(r: int, seconds := ACTIVE_FADE) -> void           ## 保留：转调 set_active_tiles(CWData.all_coords(r))
```

- `active_radius`（`board.gd:644`）继续存在，由 `set_active_tiles` 置成集合里最大的环号 ——
  `t_board_small`（`headless_test.gd:7794-7822`）与拆局兜底（`match.gd:1140 / 1236`）一行不用改。
- **`hex_at` 必须同改**：`board.gd:132` 的 `for c in CWData.all_coords(active_radius)` 换成 `for c in _active_set`
  —— 不同改就点击与显示脱节。集合外仍返回 `NO_TILE`（`board.gd:115/130`）。
- **细胞贴图也要跟着遮罩**（这条是「预置 + 遮罩揭示」能不能成立的前提）：
  `_sync_cells` 今天只按存活画 —— `node.visible = c["alive"] and not (…)`（`match.gd:1622`），
  **活跃格外的活细胞照样画出来**。所以要加一条 `and board.is_active(c["pos"])`
  （`is_active` 是新增的**即时**谓词、读 `_active_set`；`tile_shown`（`board.gd:669-672`）判的是补间后的 alpha，
  用它会在浮现的那半秒里闪一下）。`reveal` 时细胞随格一起淡入，走已有的 `_pop_in`（`match.gd:1628`）。
  不加这一条，第二关 Step1 就会提前看见右边那只癌细胞、第七关末尾会提前看见边缘的 T/B 细胞。
- `tile_shown`（`board.gd:669-672`）判的是补间后的 alpha，口径不动。
- **浮现动画**（PRD:45）：新增格按 `CWBoard.ring_delays(coords, step)`（`board.gd:320`，静态、可直接测；
  传送演出 `CWTeleportFx.RING_STEP` 就是用它错峰的，`teleport_fx.gd:26`）排队入场，
  一格一条 tween，与今天的 `_active_tws` 换向杀补间同一套（`board.gd:654-658`）。
- `_adopt_mirror` 里 `board.set_active_radius(m.board_radius)`（`match.gd:1062-1063`）加一个
  「教程局已声明活跃集就别覆盖」的闸 —— 半径现在恒为 6，不挡住就会每次 sync 把整盘露出来。
- `main.gd:115` 的 `set_active_radius(CWMatch.tutorial_board_radius(), T_ENTER * 0.5)`
  改成 `set_active_tiles(CWMatch.tutorial_active_tiles(), T_ENTER * 0.5)`（仍在推镜头**之前**，Kevin 09-11）。
- **机位不动**：`CWView.GAME_ZOOM 1.27` / `GAME_ANCHOR (388,270)`（`cw_view.gd:28-30`）与 `PANEL_WIDTH`
  是一起算出来的三个数，活跃格与机位彼此独立。**Kevin 09-12「推近镜头不做」说的是对局机位**；
  PRD:85「随着跌落过程镜头逐渐放大」是**开场演出内部的相机**（走开场场景自己的相机，`CWView.apply/blend`，
  `cw_view.gd:69-89`），两者不是一回事，各自实现、互不影响。

### 1.10 演出编排：三类演出，一条时间轴

| 类 | 谁产 | 怎么播 |
|---|---|---|
| ① 内核演出（roll / result / fx / beam / erosion / card_*） | 内核 | **照旧** `CWPlayQueue.pump()` → `CWUIBridge.show_*`。教程一行不改 |
| ② 教程脚本演出（击退受击、像素错误、冲击波、同心圆、浮现） | 数据 `steps[].fx[]` | 舞台的协程 `CWTutorialFx.play(list)`；**绝不入内核队列** |
| ③ 开场 / 间章动画 | `cutscenes/*.json` | 独立场景，压根不建内核 |

**两者怎么不打架** —— 用条目流自带的行动边界：`CWPlayQueue` 已经有 `on_step` 回调
（`cw_play_queue.gd:26`、分支在 `:130-132`），收 `step_begin{ask_id, seat}` 与 `step_end{rev}` 两种条目
（`cw_play_queue.gd:14`）。

**时序按源码钉死（初稿在这儿错了一拍）**，`cw_kernel_inproc.gd:_on_ask` 的 decider 路逐行是：

```
397  _close_step()                                  ## 推 step_end + sync —— **在问人之前**
398  if deciders.has(pid):
399      var picked = await deciders[pid].ask(req)   ## ← 玩家在这儿作答（一直挂到答完）
405      _open_step(ask_id, pid)                     ## 推 step_begin —— **作答之后**
```

所以 `step_begin` 标的是「这一问已经答了、这一步的动作开始演」，**不是「这一问要问了」**。于是：

- 收到 **`step_end`** → **这是装闸的唯一正确时机**：装这一步的 `allow`（§1.5）与 `ui_layers` / 提示 / 提亮；
  同时判上一步的 `watch` / `reset_when`、播 `fx[]`、`load` 新 world、翻到下一步。
- 收到 **`step_begin`** → 只做「演出分组」标记（快进 / 跳过用），**不装任何闸**。
- **关首**（`open_level` 返回后、`kernel.run()` 之前）再装一次：不是因为第一问没有 `step_end` ——
  `var _step_open := true`（`cw_kernel_inproc.gd:26`，注释原文「开局那段也算一步，第一问之前先 step_end 收掉」）
  保证第一问之前照样推 —— 而是因为**关的第一帧在队列泵到那条 `step_end` 之前就画出来了**，
  `ui_layers` 不提前装，玩家会先看见一瞬间的全套界面。

`queue.on_step` **今天在 `match.gd` 里没有接**（`_start_queue`，`match.gd:1010-1026` 只接了
`on_sync:1021` / `on_log:1022` / `on_ask:1023` / `on_game_over:1024`）—— **接上它是本方案唯一要在 `match.gd` 新加的回调**。

备用口径（脚本演出插在非行动边界时）：照 `CWUIBridge._await_playback()` 的写法
（`ui_bridge.gd:236-240`，`while queue.since < kernel.entry_seq()`）先等内核演出排空，
否则会出现「行动栏已经是新的一问、棋盘还停在上一步」那个老问题。

### 1.11 图鉴解锁与进度存档

- 知识之书今天**零 id、零状态**：`CWCodex.chapters()` 是纯函数每次现建（`cw_codex.gd:168`，13 章，数据在 `:289` 起），
  正文按旋钮现算、条目会整句消失 ⇒ **下标不能当 id**。改法：给每条加 `id`（`{t, b, id}`），13 章一次补齐；
  `chapters()` 仍是纯函数。`search(query)`（`cw_codex.gd:563`）要跟着按解锁集过滤 —— 不过滤的话没解锁的能被搜出来。
- 解锁集合存 `CWGuideProgress`：今天只有一个 `done` int（`cw_guide_progress.gd:12-18`）。
  扩成 `{done（旧，保留做迁移）, unlocked:[id…], at:{chapter, level, step}}`，
  **`done` 原样保留**（主菜单与 `match.gd:468/491/534` 还在读它）。
- PRD 的 12 个解锁点与今天的条目**不是一一对应** → Q-08。
- 新增 `game/data/tutorial/codex_map.json`：解锁点 → 条目 id。**不加载 = 全解锁**，退化成今天的行为（回滚友好）。

### 1.12 常驻壳：章节提示 / 重置 / 目录 / 禁用 / 慢闪

| 通用规则 | 出处 | 落点 |
|---|---|---|
| 1 章节全屏半透明提示 | PRD:35 | 新控件，复用 `guide.gd` 的 `_soft_tex` / 白雾那套（`guide.gd:169-194`）。`chapter` 字段变了才弹 |
| 2 关与关静默切换 | PRD:37 | `chapter` 没变就不弹，其余照 `_advance_tutorial_chapter` |
| 3 先结算界面 / 状态，再显示文本 | PRD:39 | step 的执行序：`load` → `ui_layers` → 浮现 → `hint` |
| 4 常驻重置按钮 | PRD:41 | `reload_world(本步入口 world_id)`；验收照闸二 2a：`dump_world(当前) ≡ minify(入口 spec)` |
| 5 常驻目录按钮 | PRD:43 | 后端今天就有 —— `CWGuide.goto_chapter(idx)`（`guide.gd:273-284`）**全仓零调用方**，前端从没做。目录 UI 调它即可 → Q-14（未通关的关怎么显示 / 能不能跳） |
| 7 自动重置有动画 | PRD:47 | `reset_when` 命中 → 播一段重置演出 → `reload_world` |
| 8 轻微慢闪 | PRD:49 | 09-10 沉浸式浮层已有白色柔光慢闪（`HALO_PERIOD 3.2`，`guide.gd:39-41`），闪烁参数收敛到一处 |
| 9 提示期间全部操作禁用 | PRD:51 | 两层：`allow = []`（三态里的「全禁」，这一问挂起、行动栏不建）+ **新起一层全屏 `STOP` 的 `Control`**。**不是**把 `CWGuide` 自己的 `mouse_filter` 切 `STOP` —— `ZONE` 只有 600×200（`guide.gd:26/108-110`），盖不住棋盘与行动栏。见 §1.5 |
| — UI 层清单 | PRD:93 / 143 / 229 / 289 / 355 / 417-423 | `ui_layers` 白名单（`action_bar` / `sidebar` / `hand` / `end_turn` / `round_no` / `move_path` / `cost` / `energy_display` / `skill_bar` / `switch_type`），逐层显隐。今天的 `ui_stage()` 0~3 四档（`guide_data.gd:46`）**保留不动**（`match.gd:1412` 还在用），与 `ui_layers` 并存 |
| — 提亮 | PRD:137 / 181 / 221 / 317 / 341 | `guide_spotlight.gd` 的 `FLAGS` 表（`:27`）加一支 `hex`（剧本直接给坐标集） |

---

## ② 与内核的边界

### 2.1 只经句柄：一条依赖线

```
数据 (JSON)
   ↓  resolve()                       纯函数，无引擎
scripts/kernel/cw_tutorial_stage.gd   ← 唯一持 CWGame 的产品文件
   · preload cw_world_loader.gd → load_world(spec) → CWGame
   · 挂带子：g.rng = CWRollTape.new(rolls)          ← 必须在 open() 之前
   · kernel.open({ adopt: g, consumer: true, observe_viewer: OMNISCIENT, autorun: false,
                   decider: ui_bridge, deciders: {npc 席位…} })
   · 返回 **CWKernel**，不返回 CWGame
   ↓
scripts/ui/guide*.gd / match.gd（导演 / 面板 / 提亮）
   · 只有 CWKernel + CWMirror + CWPlayQueue 三样
   · 作答只走 ui_bridge（人）/ npc decider（NPC）
```

`cw_tutorial_stage.gd` 住 `scripts/kernel/` 而不是 `scripts/ui/`：结构闸 `t_no_engine_in_ui` 只扫
`res://scripts/ui` 这一层目录（`headless_test.gd:20343-20345` 的 `DirAccess.get_files_at`，不递归），
`scripts/kernel/` 本来就允许碰引擎。

**关键的一条**：`stage.open_level()` 的返回类型写 `CWKernel`，**不是 `CWGame`**。
这样 `match.gd` 整份不会出现 `CWGame` 字样，闸自然过；换 sidecar 那天，`open_level` 内部从 `adopt`
换成 sidecar 的建局，**UI 侧一个字都不改**。
（对照：把 `assemble()` 仍返回 `CWGame` 交 `match.gd` 的 `cfg["adopt"]`，虽然过得了闸的文本扫描
—— `_adopted` 刻意不写类型标注，`match.gd:56-59` —— 但不满足「UI 只经句柄」的口径，本方案不取。）

### 2.2 装载器与带子搬家：**分两步**

今天 `cw_case_loader.gd` 住 `game/tests/`，不带 `class_name`（`:23`），
唯一的 `res://` 依赖是 `TUNE_PATH := "res://tests/contract_tune.json"`（`:26`）。

**判据（硬事实）**：`game/export_presets.cfg` 四个预设**全部** `exclude_filter="tests/*"`（`:11/56/127/155`）
⇒ 产品代码 `preload("res://tests/cw_case_loader.gd")` 在导出包里会加载失败（无头测试跑的是项目目录，看不出来；一导出就白屏）。
这条直接枪毙「零搬运、产品侧引用 tests/」。

**第一步（S0）：只搬 `.gd`，`contract_tune.json` 留在 `tests/` 不动。GD 与 C# 同一次提交。**

> **⚠ 初稿写「S0 ~ S5 完全不碰跨语言契约，零风险」是错的**，复核当场打红：
> `core/CellWar.Core.Tests/L0/KeyTableTests.cs:111` 的 `GdConst()` 是**按路径**读 GD 文件的 ——
> `Path.Combine(L0RunnerTests.GameTestsDir(), "cw_case_loader.gd")`（`GameTestsDir()` 在
> `L0RunnerTests.cs:186`，注释把「`game/tests` = 两侧共用契约文件的目录」写成了约定），
> 再用正则 `const\s+{name}\s*:=\s*\[(.*?)\]` 抓键表，`KeyTables()`（`:20-32`）**11 个 theory case**。
> 薄委托里不许再抄一份 `const *_KEYS`（那就成了第三份键表，违反规格 §0.6.1「仓库里只许这两份」），
> 于是 11 条全报「找不到 {name}」；直接删旧文件则 `:112` 的 `File.Exists` 当场红。
> **先例就在隔壁**：`L1/SemanticKeyTests.cs:222` 当初正是把路径改成了
> `game/scripts/kernel/cw_semkey.gd`。照它办。

- `game/tests/cw_case_loader.gd` → `game/scripts/kernel/cw_world_loader.gd`（内容一字不动，只改位置）。
- **4 处 preload 站点逐条改**（逐条核过）：
  `headless_test.gd:19132`、`l0_pre_dump.gd:11`、`l0_runner.gd:24`、`game/tests/rec/cw_recorder.gd:22`。
- **C# 一处路径常量同改**：`KeyTableTests.GdConst`（`KeyTableTests.cs:111`）指向新家；
  顺带改该文件 `:8-10` 的文档注释（「`game/tests/cw_case_loader.gd`」两处）。
  跨语言只动**路径**，键表内容一个字不变 ⇒ 11 条 theory 照旧比同一组常量。
- `l0_runner.gd:61-91` 的内部类 `RollTape` 上提成 `game/scripts/kernel/cw_roll_tape.gd`，runner 改 preload。
- 规格里两句路径跟着改：`docs/口径二_测试迁移规格.md:133`（§0.6.1「仓库里只许这两份」）与 `:258`（落点表）。
- **先例照抄**：`cw_semkey.gd:12-13` 写得清清楚楚 ——「此前它住在 `game/tests/xcheck_bridge.gd`，
  产品代码要用它，所以上提到 `scripts/kernel/`；`xcheck_bridge.gd` 改为委托，**不许出现第三份**」。
  同样处置：`game/tests/cw_case_loader.gd` 留一个**薄委托**（`preload` 新家、保留旧文件名不动调用方），或直接删并改全部站点；
  本方案取「薄委托」，回滚成本最低。
- **不给新家加 `class_name`**：`guide.gd:60-62` 已有先例并写明理由（补丁里新增的 `class_name` 认不出来、
  preload 走得了热更），且仓库另有一条老账「新增 `class_name` 要先 `--import` 才进无头测试」。
  产品侧一律 `preload("res://scripts/kernel/cw_world_loader.gd")`。

**这一步为什么不动 json**：`_load_tuning` 在 `tuning` 段为空时**直接返回**（`cw_case_loader.gd:438-440`），
而**第一章三关一个旋钮都不用**（§1.6 逐条核过）⇒ 跨语言契约在 S0 ~ S5 **只被动到一处：
`KeyTableTests` 的那个路径常量**（S0 里连 C# 一起提），旋钮白名单与键表内容一个字不改。
——「零风险」这个说法作废；准确说法是「跨语言只动一处路径常量，且 GD + C# 同一次提交」。

**第二步（S8，第一次真拧旋钮时）：`contract_tune.json` 搬到 `res://data/contract_tune.json`，GD + C# 一次提交。**

「C# 侧改一行」是低估。真实清单：
- GD：`cw_world_loader.gd` 的 `TUNE_PATH`（一行）。
- C#：`core/CellWar.Core.Tests/L0/ContractGateTests.cs:174` 的 `Path.Combine(TestsDir(), "contract_tune.json")`，
  而 `TestsDir()`（`:168`）与 `L0RunnerTests.cs:185-186` 的 `GameTestsDir()` 一起把
  **「`game/tests` = 两侧共用契约文件的目录」写成了约定** —— 搬 json = 改这条目录约定。
- 另有四处注释要同步：`WorldLoader.cs:17 / 566 / 588 / 592 / 595`、`CaseModel.cs:140`（都只是文字，但留着会误导）。
- 验收：`dotnet test` 全绿 + 新增两侧各一条 `t_contract_tune_path`「GD 与 C# 读的是同一个文件」。
- **GD 与 C# 必须同一次提交**（分开提会红一边）。

### 2.3 `guide_director.gd` 摘出白名单 + `win_checks` 整条消掉

今天的白名单（`headless_test.gd:21-24` 的 `UI_ENGINE_OK`）两条：`guide_director.gd` 整份豁免（`:22`，
注释原文「批 3 随教程内核化一起收」）+ `ui_bridge.gd` 的 `attach_engine` 那一行（带 `## KERNEL-ENGINE-OK` 标记）。
断言把条数写死（`headless_test.gd:20393-20394` `size() == 2`）并逐条核文件还在（`:20395-20396`）。

改法（在 S3 一个切片里原子完成）：
1. **删** `game/scripts/ui/guide_director.gd` 整份（117 行；唯一的 `CWGame.new()` 在 `:32`，直写内部状态在 `:48-61` / `:67-117`）。
2. **删** `game/scripts/ui/guide_levels.gd`（被数据替掉）。
3. **新增** `game/scripts/kernel/cw_tutorial_stage.gd`、`cw_tutorial_npc.gd`。
4. **改** `headless_test.gd:21-24` 的 `UI_ENGINE_OK` 只留 `ui_bridge.gd`；`:20393-20394` 的断言改成
   `size() == 1 and has("ui_bridge.gd")`，文案里的「白名单两条」→「一条」。
5. **改** `match.gd` —— **逐行清单**（初稿漏了 4 行 `CWGuideLevels`，一删就编译不过）：

   | 行 | 今天 | 换成 |
   |---|---|---|
   | `:467-469` | `tutorial_board_radius()` → `CWGuideLevels.radius(ch)` | `tutorial_active_tiles()` → 读关卡 JSON 的 `active_tiles` |
   | `:492` | `player_count = 4 if CWGuideLevels.formal(...) else 2` | `player_count = 关卡 JSON 的 seats`（纪律 8） |
   | `:493` | `human_players = [1 if CWGuideLevels.player_faction(...) == CANCER else 0]` | `human_players = [关卡 JSON 的 human_seat]` |
   | `:496` | `_adopted = CWGuideDirector.assemble(ch, 0)` | `_stage = CWTutorialStage.open_level(spec)` |
   | `:532` / `:1215` | `_adopted.dispose()` | `_stage.dispose()` |
   | `:535` / `:536` | 跨章那一份 `player_count` / `human_players` | 同 `:492` / `:493` |
   | `:537` | 跨章那一份 `assemble` | 同 `:496` |
   | `_start_queue`（`:1010-1026`） | 只接 4 个回调 | 加 `queue.on_step`（§1.10） |
   | `:1062-1063` | `board.set_active_radius(m.board_radius)` | 加一个「教程局已声明活跃集就别覆盖」的闸（§1.9） |
   | `:1622` | `node.visible = c["alive"] and not (…)` | 加 `and board.is_active(c["pos"])` —— 活跃格外的活细胞不画（§1.9，「预置 + 遮罩揭示」的前提） |

   `player_count` / `human_players` 在教程路**不进 `cfg`**（走 `adopt`，`cfg["factions"]` 只在非教程分支设，`:499`），
   它们只喂 UI：热座判定（`:868`）、日志视角（`:1395/1399`）、手牌席位（`:1776`）。
   从数据取的先例就在同一文件里 —— 回放与联机路本来就写 `player_count = mirror.players.size()`（`:576` / `:723`）。
6. **改** `game/tests/dump_guide.gd:47-49`（3 处 `CWGuideLevels.radius / player_faction / zones`）。
   它不进测试套件（是导出剧本的工具脚本），删类之后**静默坏掉**、要到 S11 才会有人发现 ——
   所以提前到 S3 一起改（先改成读数据的桩也行）。

**`win_checks` 这条表达不了项怎么办** —— 今天靠 `g.win_checks = false`（`guide_director.gd:39`，
字段在 `cw_game.gd:99`，**全仓只被 `cw_world.gd:77` 读**），它不在 `cwxworld/2` 的 15 键里，也没有 C# 对应物。
**本方案不再用它**，改成三条数据：

- **第一 ~ 五关**：`allow` 里**不放**「结束回合」⇒ 永远进不了 E 阶段 ⇒ 胜负判定压根不跑
  （只在 E 阶段末判，`cw_world.gd:74-79`）。
- **第七关：多回合、多次 E 阶段**（初稿写「唯一一次结束回合」是错的）。PRD:459「重复 3-5 直到剩余
  最后一个 T 细胞」里的第 4 步就是「点击结束回合」（PRD:445）⇒ 结束回合会点若干次，E 阶段跑若干遍。
  两条护栏逐次都要成立：
  - **免疫胜利**：场上有活癌细胞（玩家自己）⇒ `check_immune_win` 第一行就 return（`cw_game.gd:1098`）。
  - **癌方加权胜利**：`cancer_win_hold_rounds: 99`（tier A）—— 要连续 N 个回合达标才判（`cw_game.gd:1122-1128`）。
- **第七关有一个窗口第一道闸失效，必须用数据兜住**：PRD:491-495 玩家【黏液破裂】自毁、**下一个 S 阶段**
  才在固化癌组织上复活 —— 中间隔着一次 E 阶段，那一刻 `living_cells(CANCER)` 为空，
  `cw_game.gd:1098` 那道闸过不住，**只剩 `:1104-1110` 的兜底**：存在一格 `Tissue.SOLID` 且**不被免疫细胞占据**
  就不判免疫胜利。这正好就是 PRD:495 的复活点，但**必须在数据里保证**：
  死亡窗口内至少有一格 `state: "solid"`（纪律 9）且那一格上没有免疫细胞。S10 加硬断言（见 ③）。
  （这条不是假想：Kevin 09-12 截图报过的「教程过完直接弹结算」就是同一条路径。）
- **兜底**：`limit_round` 是 15，且 `cw_world.gd:80-83` 明写这条**故意不跟着 `win_checks` 关**
  （关掉之后无头里的教程局会一路空转、`t_tutorial_chapter_swap` 当场挂死）。
  第一 ~ 五关**零个**世界回合；第七关按 PRD:459 的「重复」估 **3~5 个**，离 15 还远。
  注意 `limit_round` 是 **tier C**，想拧也拧不动 —— 正好不需要。

这样一来，教程**不再需要任何「不在 `cwxworld/2` 里」的引擎字段** —— 这是 §2.4 论证成立的前提。
连带 `t_entry_smoke_tutorial:20612`（`check(not k.game.win_checks, …)`）改判：改成
「第一 ~ 五关的 `allow` 里没有结束回合」+「第七关连跑 N 次 E 阶段（含黏液破裂→复活那一段）不产 `game_over` 条目」。

### 2.4 换 C# sidecar 那天零改动：逐条论证

教程与内核的接触面只有五处：

| 接触面 | 今天（GD InProc） | sidecar 那天 | 要改的教程代码 |
|---|---|---|---|
| ① 开局盘面 | `cwxworld/2` → `cw_world_loader.load_world` | 同一份 JSON → C# `L0/WorldLoader.Load`。闸二 2b 已证两侧装出的世界逐字段相同；仓库里只许两份键表、逐键相同（`cw_case_loader.gd:3-4`） | **0**（数据不动） |
| ② 规则改动 | `world.tuning` → A/A′ 档白名单 | C# `WorldLoader.WithKnob` 读**同一份** `contract_tune.json`，按 tier 分桶、拒绝的集合必须一样（`WorldLoader.cs:588/592/595`） | **0** |
| ③ 预设结果 | `rolls` → `CWRollTape` | C# `TapeRng`，同一套语义；`randi_range(n,n)` 消耗 0 两侧同口径（`l0_runner.gd:78-79`） | **0** |
| ④ 作答 | 语义键 | `CWSemKey` 文法与 `core/CellWar.Core/SemanticKey.cs` 逐字相同，C# 侧有护栏读 GD 这个文件比 `KEY_FIELDS`（`cw_semkey.gd:5`） | **0** |
| ⑤ 演出 / 观测 | 条目流 + `CWMirror` | `CWKernel` 抽象基类的形制就是照联机路反推的，sidecar 走 `/pull` `/observe` `/submit` | **0** |

**⚠ 一条前置没写全（复核补的）**：①③ 两行里 C# 侧的对应物 ——
`core/CellWar.Core.Tests/L0/WorldLoader.cs` 与 `core/CellWar.Core.Tests/L1/TapeRng.cs` ——
**都住在测试程序集 `CellWar.Core.Tests` 里，产品程序集 `CellWar.Core` 没有对应物**（实测目录清单）。
这与 GD 侧「装载器住 `tests/`、导出包排除 `tests/*`」是**同一性质**的问题，只是那边是导出过滤、这边是程序集边界。
所以准确说法是：**「教程代码改动 = 0」成立，但 C# 那侧要先把这两件上提到 `CellWar.Core`**
（口径一批 1 之后的事，不影响本方案排期）。列为 Q-19 报 Kevin。

剩两处是 InProc 专有的，方案里**已经各自隔离**：

- **`adopt`**（`cw_kernel_inproc.gd:52-57`）：只出现在 `cw_tutorial_stage.gd` 一个文件里。
  sidecar 那天改成 `world_state` / `/restore`，UI 侧看不见（`open_level` 返回的是 `CWKernel`）。
  今天的 `cfg` 里确实没有 `world` / `rolls` 两个键（`cw_kernel_inproc.gd:43-91` 逐条核过）——
  那天要么在句柄 cfg 上加这两个键，要么在 `open_level` 里翻译，**两种都只动这一个文件**。
- **`decider` 直答**（`:399-400`）：NPC 逻辑写成纯函数 `decide()` + 两个 adapter（§1.8），
  流式那一只**现在就可以写、现在就能测**。

**唯一的「不零改动」项**是玩家自己作答那条路：今天 `CWUIBridge` 是 `decider`、靠 `ask()` 返回下标；
sidecar 下要改成 `queue.on_ask → kernel.answer(ask_id, {key})`。
但这是**所有本地对局共有的**改动（不是教程引进来的），到时候改 `ui_bridge.gd` 一处，教程跟着白拿。

---

## ③ 切片计划

原则：每片**可独立提交、可独立回滚**、自带 headless 测试、**老 `check()` 一条不删**（改判据的逐条列出来、写明理由）。
**第四章不做。**

### S0 · 装载器与带子上提（纯搬家，零行为变化）—— **GD + C# 同一次提交**
- **改**：`game/tests/cw_case_loader.gd`（改成薄委托，**不许再抄一份键表**）、4 处 preload（`headless_test.gd:19132` /
  `l0_pre_dump.gd:11` / `l0_runner.gd:24` / `tests/rec/cw_recorder.gd:22`）、`l0_runner.gd:61-91`（`RollTape` 改 preload 新家）、
  **`core/CellWar.Core.Tests/L0/KeyTableTests.cs:111` 的路径 + `:8-10` 的注释**（§2.2 的 ⚠）、
  `docs/口径二_测试迁移规格.md:133` 与 `:258`
- **新增**：`game/scripts/kernel/cw_world_loader.gd`、`game/scripts/kernel/cw_roll_tape.gd`
- **不动**：`contract_tune.json`（留 `tests/`，理由见 §2.2）
- **测试**：`tools/run_tests.sh` 全绿 + `tools/run_l0.sh` 全绿 + **`dotnet test` 全绿（11 条键表 theory 是这一片的主验收）**；
  闸二 2a/2b 逐字不变 = 搬对了；新增 `t_kernel_loader_moved`：① 新家在、旧名是委托且**不含 `const *_KEYS`**；
  ② 扫 `res://scripts/**` 里 `preload("res://tests/` **零命中**
- **回滚**：一条 revert（GD 与 C# 在同一个 commit 里，分开回会红一边）

### S1 · 活跃格集合与浮现（**只动 `board.gd`**）
> **为什么缩到只剩一个文件**：初稿让 S1 顺手改 `main.gd:115` 与三条 `t_tutorial` 断言，
> 但 `CWMatch.tutorial_active_tiles()` 要吐的格集合来自关卡 JSON（S2 才有）、接线在 S3，
> 「新第一关的两格盘面」也要等 S3 —— S1 阶段跑的还是老导演的 7 格（`headless_test.gd:20613`）。
> 初稿自己在附 B 里把 `t_tutorial` 的去向写成「S1 / S3」，等于承认分不干净。**API 改名与三条改判整体挪 S3。**

- **改**：`board.gd`（新增 `_active_set` / `set_active_tiles` / **`is_active(c)` 即时谓词**，
  `set_active_radius` 转调，`hex_at:132` 换集合，浮现补间）
- **不改**：`main.gd`、`match.gd`（它们跟着 S3 走 —— 含 `:1622` 的细胞遮罩）
- **测试**：`t_board_active_tiles`（新）—— ① 集合内 `tile_shown` 真、集合外假；② `hex_at` 集合外返回 `NO_TILE`；
  ③ 格网仍 127 格、`_grid()` 没被重跑；④ `ring_delays` 单调递增。
  `t_board_small`（`:7794`）**原样通过**（薄壳）
- **改判**：**无**（这一片一条老 check 都不动）
- **回滚**：独立

### S2 · 数据格式 `cwtut/1` 与校验（还不接线）
- **新增**：`game/scripts/kernel/cw_tutorial_data.gd`（读 JSON、`resolve(level, world_id)`、校验）、
  `game/data/tutorial/index.json` + 第一关一份样例
- **改**：无
- **测试**：`t_tutorial_data`（新）—— ① schema 键合法（15/5/12/33 键表）；
  ② 每个 `world_id` 跑 `resolve → load_world → dump_world ≡ minify(resolve)`；
  ③ **席位数 == 细胞数、每席恰好一只**（装载器只拦同格不拦同席，`cw_case_loader.gd:303-308`）；
  ④ 活跃格 ⊆ 世界半径；⑤ 活跃格里压到 11 个特殊格的都显式写了 `"type"`；
  ⑥ `watch` / `reset_when` 的键都在 `CWGuideWatch.KEYS` 里；⑦ 文案占位 `{{tune.*}}` 都解析得出；
  ⑧ **纪律 8**：`seats == players.size()`、`human_seat < seats`，且**按人数分档的数值逐关标定过**
  （关卡 JSON 写 `expect_level_tiers`，与 `CWData.level_min_memory(seats)` 当场比）；
  ⑨ **纪律 9**：文案/复活点提到固化的关，盘面里有 `state == "solid"` 的格（`tiles[].solid` 计数不算）；
  ⑩ `reveal` 的格必须已经在某份 world 的盘面上（预置 + 遮罩，不是凭空造格）
- **回滚**：删新文件

### S3 · 舞台 + 删老导演 / 老关卡表 + 数据门面 + 第一关（**原子片，全案最大的一片**）
> **为什么不能再拆**：`guide_director.gd` 与 `guide_levels.gd` 一删，`headless_test.gd` 里
> **`CWGuideDirector.` 41 处 + `CWGuideLevels.` 19 处 = 60 处、落在 54 行**（实测 `grep -o`；初稿只数了 41）
> 当场红；`guide_data.gd` 一退成门面，`CHAPTER_COUNT` 从 16 变 6，`t_guide_data` 整份红。
> 这三件互相咬死（导演调关卡表、`guide.gd` 调剧本、剧本关数与关卡表关数互校，
> `headless_test.gd:10957`），拆开提交就是「中间那一版必然红」。所以删类、接线、第一关数据、
> 老测试改判**必须同一次提交**。S1 挪过来的那三条（`main.gd` 的 API 改名与 `t_tutorial` 的盘面改判）也在这儿。

- **新增**：`game/scripts/kernel/cw_tutorial_stage.gd`、`cw_tutorial_npc.gd`、`game/data/tutorial/levels/c1_l1.json`
- **删**：`game/scripts/ui/guide_director.gd`、`game/scripts/ui/guide_levels.gd`
- **改**：`game/scripts/ui/guide_data.gd`（退成 JSON 门面，公开面签名全保留，见 §1.1 表）、
  `match.gd`（**逐行清单见 §2.3 第 5 条**：`:467-469` / `:492` / `:493` / `:496` / `:532` / `:535` / `:536` /
  `:537` / `:1215`，外加 `queue.on_step` 接线、`:1062-1063` 的活跃集闸、`:1622` 的细胞遮罩）、
  `main.gd:115`（`set_active_radius(...)` → `set_active_tiles(CWMatch.tutorial_active_tiles(), T_ENTER * 0.5)`，仍在推镜头之前）、
  `game/tests/dump_guide.gd:47-49`（3 处 `CWGuideLevels`，**不进套件、不改就静默坏掉**）、
  `headless_test.gd:21-24` 与 `:20393-20394`（白名单两条 → 一条）
- **测试（新）**：`t_tutorial_stage` —— ① `open_level` 返回 `CWKernel` 且不泄露 `CWGame`；
  ② 重装次序 `abort → stop → close → dispose`；③ 带子在 `open()` 之前挂上；④ 第一关
  `dump_world(load) ≡ minify(spec)`、免疫细胞在起点、癌席无细胞（`cell_id == -1`）
- **测试（改判，逐条写理由）**：
  `t_no_engine_in_ui`（`:20365` 一带，白名单一条）、
  `t_guide_director`（`:10947-11345`，**断言对象整体消失** → 改判为「数据版的逐关开局」，check 条数不减）、
  `t_guide_data`（`:10854-10946`，`CHAPTER_COUNT == 6`、`CODEX_PAGE` / `UI_STAGE` / 标题表跟着关数走，判据**形状**不变）、
  `t_guide_no_win`（`:9789-9823`，`:9792/9803/9810/9811` 调 `CWGuideDirector.assemble` 与 `CWGuideLevels.count/formal`
  → 改判为「第一 ~ 五关的 `allow` 里没有结束回合 + 跑一次 E 阶段不产 `game_over`」，§2.3）、
  `t_tutorial_mechanism_trials`（`:1817`，`:1819/1826/1834` 调 `assemble(11, 0/1/2)`；PRD 没有「机制试炼」
  → 保留 check 条数，断言对象换成第七关的三条 E 阶段结算，或整体并入 Q-17 一起问）、
  `t_guide_bridge`（`:11556`，`:11592-11598` 的 `ui_stage(0)/(6)/(15)`、`:11599` 的 `assemble(15)`、
  `:11601` 的 `graduation_assist` → 按新关数与「无毕业战」改判）、
  `t_tutorial`（`:10651`，**含从 S1 挪来的三条**：`:10679-10682` 盘面、`:10683` 半径 API、`:10686` `main.gd` 源码串）、
  `t_tutorial_auto_advance`（`:11346`）、`t_tutorial_pick`（`:12978`）、
  `t_tutorial_chapter_swap`（`:12256`）、`t_entry_smoke_tutorial`（`:20600-20633`，三条断言见 §1.3 后果表 + `:20612`）
- **回滚**：一次 revert（这一片必须原子）

### S4 · 常驻壳 + 决策闸（通用规则 1/2/3/4/5/7/8/9）
- **改**：`guide.gd`（全屏章节提示、重置 / 目录按钮接线、提示期 `mouse_filter` 切 `STOP`）、
  `guide_bridge.gd`（`allow` 过滤视图 + 下标映射，§1.5）、
  `guide_spotlight.gd`（`FLAGS` 加 `hex` 一项 + 一支 `sync` 分支）、`guide_watch.gd`（`KEYS` 加条目）
- **新增**：全屏章节提示控件、**全屏 `STOP` 遮挡层**（§1.5 的第 2 层）、目录页（`goto_chapter` 终于有调用方，`guide.gd:273`）、
  `CWTutorialStage.reload_world`
- **测试**：`t_guide_gate`（新）—— ① `allow` 非空时行动栏只出现被点名的选项；② **下标映射回原表**；
  ③ **`allow = []`（全禁）时这一问挂起、`answer` 调用数为 0、行动栏没建**；
  ④ **全落空时打一条 warning 并挂起（`answer` 调用数为 0），不回落成全开、也不替玩家乱答**；
  ⑤ **「继续」代做在 `allow` 生效时落到被点名的那个选项**（P-08 那条二次映射的回归闸）；
  `t_guide_reset`（新）—— 重置后 `dump_world ≡ minify(入口 spec)`；
  `t_guide_shell`（新）—— 目录列出全部章与关
- **改判**：`t_guide_spotlight`（`:11674`，`FLAGS` 扩表，判据形状不变）
- **回滚**：独立

### S5 · 第一章其余两关（PRD:141-283）—— **里程碑：第一章真机可玩**
- **新增**：`c1_l2.json` / `c1_l3.json`（**纯数据，零代码**；各自一份，Step1/Step2 在 `steps[]` 里分段）
- **测试**：`t_tutorial_c1`（新）—— ① `rolls` 精确用尽（`_check_tape` 双向核对）；
  ② 第二关 Step2 一击死（10 伤害 vs 10 能量），且 **Step1 → Step2 全程 `load` 只出现过一次**（关首那一次）；
  ③ 第二关 Step2 揭示 `(5,-1)` 走的是 `reveal`，**玩家在 Step1 净化过的两格在 Step2 仍是健康组织**（关内连续性的回归闸），
  且 **Step1 期间那只癌细胞的节点 `visible == false`**（`match.gd:1622` 的遮罩，§1.9）；
  ④ 第三关三次攻击 10+0+20 = 30 刚好打死、能量 `51 = 5×3+30+5+1` 对得上，且 **Step2 不重装**
  （否则 PRD:241-251 的整关能量预算与自动重置判据无从成立）；
  ⑤ 第三关 `reset_when` 在「能量不足以移动」时触发，重置回**关首**那一份 world；
  ⑥ 每关活跃格条数与 PRD 对得上（第一关 2 / 第二关 6 → 7 / 第三关待 Q-02）
- **回滚**：删数据文件

### S6 · 图鉴解锁与进度存档
- **改**：`cw_codex.gd`（13 章逐条补稳定 id、按解锁集过滤、`search()` 同步过滤、解锁动效）、
  `cw_guide_progress.gd`（扩 `unlocked` / `at`，`done` 保留做迁移）
- **新增**：`game/data/tutorial/codex_map.json`
- **测试**：`t_codex`（`:11416`，**加判据**：每条有 id、id 唯一、未解锁的搜不出来也不出现在页面）；
  `t_guide_progress`（新：写入 / 读回 / 旧档只有 `done` 时的迁移）
- **回滚**：独立（`codex_map.json` 不加载 = 全解锁，退化成今天的行为）

### S7 · 开场动画（PRD:59-87）
- **新增**：`game/scenes/tutorial_opening.tscn` + `opening.json`（分镜时间轴）、
  三段新演出（文字变细胞 / 同心圆净化 + 反向侵蚀 / 组织跌落）、开场场景自己的相机
- **改**：无（**不建内核**）
- **测试**：`t_tutorial_opening`（新）—— ① 整段**零 rng 消耗**（跌落的 0~1 秒随机走演出层自己的
  `RandomNumberGenerator`，绝不碰内核 rng，碰了带子就错位）；② 分镜条数与 PRD:63-87 对得上；
  ③ 结束后直接接章节提示（PRD:87）
- **回滚**：独立（与对局完全解耦，可与 S5 / S6 并行）

### S8 · 第二章两关 + `contract_tune.json` 搬家 + NPC decider（PRD:285-383）
- **改**：`contract_tune.json` → `res://data/`（GD `TUNE_PATH` + C# `ContractGateTests.cs:174` /
  `L0RunnerTests.cs:185-186` 的目录约定 + 四处注释，**GD 与 C# 同一次提交**，§2.2 第二步）；
  `guide_data.gd` 门面补两个 `watch` 键（`level_at_least` / `all_dead`）；`ui_layers` 补 `switch_type`（PRD:355）
- **新增**：`c2_l4.json` / `c2_l5.json`（第五关 Step2 一次关内 `load` + 分化四种各一份 world）；`cw_tutorial_npc.gd` 的策略实现
- **测试**：`t_contract_tune_path`（新，两侧各一条）；`dotnet test` 全绿；`t_tutorial_npc`（新：按语义键逐问作答、
  找不到就回落、零 `game.` 访问）；`t_tutorial_c2`（新）—— ① **第四关按 `seats` 标定 III 级门槛**：
  `seats == 4` 才是 20 点（`cw_data.gd:272/277`），**多一席就回落六人档 30**（纪律 8）——
  断言写成「起始 memory + 本关可得记忆 ≥ `CWData.level_min_memory(seats)[2]`」，不写死数字；
  ② 第五关 Step2 全部癌细胞死亡时 `watch` 触发**且没有弹结算屏**；
  ③ 切换分化种类走 `load`，四份 world 各自 `dump ≡ minify`；
  ④ 第五关 Step2 的席位数（5 种免疫各一 + 玩家 + 若干癌 ⇒ 8~12 席，`cw_case_loader.gd:939-945`）
  与 `expect_level_tiers` 对得上
- **真机**：右栏一行一席（`match_panel.gd:318-330` 一带），**8~12 行的排版从来没验过** ⇒ 截一次图核对（PRD:417 要求全显示）
- **回滚**：独立，但 json 搬家要连 C# 一起回

### S9 · 间章动画 癌变（PRD:385-411）
- **新增**：`interlude.json`（演出 + 4 份重装 world）、「像素错误」与暗黑像素冲击波两个新演出
- **改**：无
- **测试**：`t_tutorial_interlude`（新）—— ① 阵营翻转那一份 world（玩家席 `faction:"cancer"` +
  `cancer_type:"SmallCellLung"`）装得进（阵营必须整份重装：席位 order 在 `g.init` 时定死，`cw_case_loader.gd:131-138`）；
  ② IN-10 三次攻击的带子精确用尽；③ IN-11 的「击退 1 格」是重装不是规则（断言 `cw_actions.gd` 源文件哈希未变）
- **回滚**：独立

### S10 · 第三章 第七关（PRD:413-503）
- **新增**：`c3_l7.json`（25 步、十来份 world、`npc` 脚本、录制出来的 `rolls`）、`game/tests/record_level_rolls.gd`
- **改**：`cw_tutorial_npc.gd` 补策略（`approach` / `attack_if_adjacent` / `antibody×3`）；
  效应应答特效的**教程变体**（PRD:465「命中于癌细胞上而非贯穿」，**不动公共特效**）
- **前置**：Q-04 / Q-06 / Q-07 / Q-09 / Q-15 / Q-16 / Q-18 必须先有答复，否则做不下去
- **测试**：`t_tutorial_c3`（新）—— ① 25 步与 PRD:439-503 逐条对账；
  ② 带子 `_check_tape` **双向归零**（每份 world 一条；固化扩散 `cw_world.gd:920` 每次 E 都抽，手算不出来 ⇒ 只能录）；
  ③ **连跑 N 次 E 阶段（PRD:459 的「重复」）都不产 `game_over` 条目**，`cancer_win_hold_rounds: 99` 生效；
  ④ **硬断言：黏液破裂 → 死亡 → 下一个 S 阶段复活这一段跨过的那次 E 也不产 `game_over`**，
  且死亡窗口内盘上至少一格 `state == "solid"` 且**无免疫细胞占据**（§2.3 的兜底，`cw_game.gd:1104-1110`）；
  ⑤ 玩家席 `allow` 之外的选项全部不出现在行动栏；
  ⑥【转移】落点几何：**起点距离 9 → 两轮「前进 1 + 击退 2」后 11 → 两次转移正好邻接**（Q-07 改后的数）；
  ⑦ `overload_div == 0`（否则 99990 每回合被啃 15.0 并写日志，§1.6）；
  ⑧ 世界回合数 ≤ 5 ⇒ `tumor_stage` 停在 I 期（`cw_card_data.gd:182-184`，分档下标不漂）
- **真机**：右栏席位排版再截一次（第七关席位最多，PRD:417）
- **回滚**：独立（这一关是最后一关，删了前面照跑）

### S11 · 收口
- **改**：`game/tests/dump_guide.gd`（改成从数据导出剧本；8 处 `CWGuideData.*` 调用随门面走，
  存档规矩不变：`docs/教程剧本_<YYYY-MM-DD>.md`、**不覆盖同名**，`dump_guide.gd:13-15`）
- **文档**：`docs/新手引导_实现方案.md` 与开发日志同提交（与代码同一次提交，不等提醒）
- **回滚**：独立

**顺序依赖**：S0 → S2 → S3 → S4 → S5 → S8 → S9 → S10 → S11；
S1 可与 S2 并行（不同文件），但必须早于 S3；S6 / S7 可与 S5 并行。

---

## ④ 工期（人日）

口径：一人日 = 一个熟悉这套代码的人做一天，含写测试、跑 `tools/run_tests.sh`（分片并行 ~85 s）与真机截图核对。
**不含**美术新资产（像素错误 / 暗黑冲击波 / 文字变细胞的贴图），**不含**第四章。

| 片 | 内容 | 人日 | 备注 |
|---|---|---|---|
| S0 | 装载器与带子上提 | 1.5 | 纯搬家，但 **GD + C# 同一次提交**（`KeyTableTests` 路径）＋三套套件各跑一遍 |
| S1 | 活跃格集合与浮现 | 1.0 | 缩到只动 `board.gd`；`hex_at` 同改是关键，别漏 |
| S2 | 数据格式与校验 | 2.0 | `resolve` + 九条纪律的逐条测试 |
| S3 | 舞台 + 删老导演 / 老关卡表 + 数据门面 + 第一关（原子） | **5.5** | **60 处**调用点（不是 41）、`match.gd` 九处、12 条老测试逐条改判＋从 S1 挪来的三条；全案最大的一片 |
| S4 | 常驻壳 + 决策闸 | 3.5 | 章节提示 / 目录 / 重置三个新控件＋**全屏 STOP 层**＋三态闸与下标映射；提亮要重画一版（09-12 那次「重影」回滚的账） |
| S5 | 第一章其余两关（纯数据） | 2.5 | 两份 JSON；含第三关能量标定与自动重置 |
| — | **小计：第一章真机可玩** | **16.0** | |
| S6 | 图鉴解锁与进度存档 | 2.5 | 大头是给 13 章所有条目补 id 并与解锁点对表 |
| S7 | 开场动画 | 3.5 | 三段新演出从零写 |
| S8 | 第二章两关 + json 搬家 + NPC decider | 4.5 | 含 C# 目录约定与 `dotnet test`；多席位标定与右栏真机截图 |
| S9 | 间章动画 | 2.5 | 含「像素错误」新特效 |
| S10 | 第七关 | **7.0** | 25 步 + ~10 席 NPC 脚本 + 多回合 E 的带子录制 + 两个新特效 + 复活窗口的胜负兜底 + 七个前置 Q |
| S11 | 收口（剧本导出 / 文档） | 1.0 | `dump_guide.gd` 已在 S3 改过，这里只剩数据化导出与文档 |
| — | **合计** | **37.0** | |

**另计缓冲 3.0**：① UI / 设计改动先出示意图给 hxr 圈（既定流程）的往返 **2.0**；
② Q 未答期间的阻塞 **1.0**（S10 的七个前置问题最容易堵）。
**不确定度**：S7 与 S10 各 ±1.5，取决于 Q-09 的表现口径。

（沿革：初稿 33.0 → 本版 37.0。逐条：S0 +0.5（C# 同改）、S1 −0.5（缩到一个文件）、S3 +1.5（60 处而非 41 处，
＋接下 S1 的改判）、S4 +0.5（三态闸 / 全屏层 / 下标映射）、S8 +0.5（多席位标定与截图）、S10 +1.5
（多回合 E、复活窗口断言、~10 席脚本 —— 复核按仓库过往节奏估到 8，这里取 7.0 并把差额压进缓冲）。）

---

## ⑤ 要 Kevin / hxr 拍的问题

按拦路程度排，共 19 条，每条带推荐。**第四章不在其中。**

| # | 问题 | 推荐 | 出处 |
|---|---|---|---|
| **Q-01** | 通用规则 10「未指定种类的癌细胞在所有种类中任选」：**作者期定死**还是**运行期随机**？ | **作者期定死**（每关数据写明癌种）。`cwxworld/2` 的癌席 `cancer_type` 必填、没有 `"none"` 哨兵（`cw_case_loader.gd:322-327`），运行期随机会让带子、自动重置、headless 断言全部不可复现 | PRD:53 |
| **Q-02** | 第三关「凸的癌组织连通块」、第三 / 四关「向前方 / 向周围延伸开来」、第七关整张地图：要**具体格子** | 由我方出一版示意图给 hxr 圈（设计改动先出示意图是既定流程）。默认提案见附 A：第一 ~ 三章走 `r = -1` / `r = -2` 两排（零特殊格），第七关直线放在 `r = -1` 排 | PRD:227/229/291/461 |
| **Q-03** | 「本关【迁移】不消耗能量」是否**包含攻击费**？（攻击 = 迁移到癌细胞格：`_do_move` 先 `cost.commit` 扣费再判出攻击，`cw_actions.gd:750-757` → `:783-792`） | **包含**。`immune_move_healthy` / `immune_move_cancerous` 都是 tier C（数组型、下标语法未定）⇒ 走「大能量 99990 + 隐藏费用显示」，攻击费自然被盖住。**不建议**为教程把这两条升 A 档 —— 那要先定数组下标语法，是跨语言契约的改动 | PRD:105/149/195 |
| **Q-04** | 第七关 PRD:449「正常结算【微环境压迫】、【增生】、【侵蚀】」三条都有坑：① 侵蚀只吃「不与外缘连通的健康连通块」（`cw_world.gd:596-606`）⇒ 半径 6 全健康的盘**一格都侵蚀不到**；② 增生每个合格健康格掷一次骰（`cw_world.gd:681`）⇒ 半径 6 下**每一次** E 阶段上百次抽取（PRD:459 还要重复若干轮），且多数发生在遮罩外玩家看不见的格上；③ 固化扩散（根深蒂固）每次 E 都 `pick_random`（`cw_world.gd:920`），这条**拧不掉**（第七关必须有固化格），带子只能录 | **压迫真结算**（它不掷骰、必然生效：6 癌邻 0 健康 ⇒ 加权 6 × 10 ÷ 4 = 1.5 能量，`cw_data.gd:456-462`）；**增生把 `proliferate_per_adjacent[1]` / `proliferate_per_solid[1]` 拧 0**（tier A′，`cw_world.gd:666-667` 在掷骰之前早退）**再用脚本演出补可见范围内的转化**；**侵蚀承认打不到**，图鉴解锁照给、用脚本演出补。三条的图鉴解锁（PRD:451）都不受影响 | PRD:449/451 |
| **Q-05** | 第四 / 五关玩家自由攻击、间章 IN-10 三次攻击、第七关 NPC 每次攻击 —— **骰子钉不钉？钉成什么？** | 第四 / 五关**不钉**（装载器种子恒为 1，序列本来就确定；无限能量 + 不限次数 ⇒ 失败只是慢，不会卡关）。间章与第七关的**每一次都钉「成功」`[[1,6,3]]`**（演出要可预期）。**最糟的是钉一半** —— 带子会错位 | PRD:373/409/453 |
| **Q-06** | 第七关 B 细胞「无视邻接健康组织的限制」（PRD:455）—— 目标集合写死在规则里，没有旋钮（`cw_actions.gd:1244-1249`） | **盘面保证玩家癌细胞邻接至少一格健康组织**（数据一句话的事），规则一行不改 | PRD:455 |
| **Q-07** | 第七关 T 细胞「离癌细胞比较远且在一条直线上」+「点击**若干次**转移正好到相邻格」：【转移】固定跃进 5 格（`cw_data.gd:341`，落点算式 `cw_actions.gd:1505-1509`）⇒ **转移那一刻**的距离必须是 5k+1。**关键在「击退发生在转移之前」**：PRD:467-481 的步序是「移动 1 → 击退 2」两轮，每轮净 **+1**，所以起点距离要按 `D + 2 = 5k + 1` 倒推 | **起点距离取 9**：玩家癌细胞 `(-3,-1)`、T 细胞 `(6,-1)`（`r = -1` 排，零特殊格）。两轮击退后玩家落 `(-5,-1)`、距离 11 = 5×2+1 ⇒ 两次【转移】落 `(0,-1)` → `(5,-1)`，正好邻接 T 细胞。**初稿的 `(-5,-1)` 起点是错的**：`r = -1` 排 q ∈ [-5, 6]（`cw_data.gd:876-878`），`(-5,-1)` 就是左端点，击退 2 格会落到 `(-6,-1)`（`|q+r| = 7`）出盘，装载器当场拒（`cw_case_loader.gd:173-175`）；且那样转移前距离是 13，`13 − 5k = 1` 无整数解。**被【微环境压迫】围的是免疫细胞、不是玩家**（`cw_world.gd:1099-1104`），把被围的免疫细胞放在内圈（离边 ≥1 格）即可 | PRD:461/467-481 |
| **Q-08** | 图鉴解锁的 12 个点与知识之书现有条目**不是一一对应**（净化 / 抗原记忆共用一条；攻击对两条；压迫 / 增生 / 侵蚀挤在 E 阶段一两条里）。**拆条目**还是**解锁整章**？未解锁的**隐藏**还是**灰显**？ | **拆条目 + 灰显**。灰显能让玩家看见「还有东西没解锁」；隐藏会让书看起来是残的。拆条目的账已在 S6 的工期里 | PRD:125-497；`cw_codex.gd:168/289` |
| **Q-09** | 「像素错误效果」（间章两次 + 第七关一次）具体表现？暗黑像素冲击波、文字变细胞的美术口径？四处 `……` 的文案是什么？间章「等待几秒」是几秒？ | 表现由 hxr 给一句话口径（抖动 / 色块错位 / 扫描线三选一，我方各出一版预览图再实现）；`……` 建议就是**留白本身**（沉默几拍）；等待 **2.0 秒** | PRD:393/395/397/399/403/405/439/475/487 |
| **Q-10** | 第七关第 8 步「重复 3-5」（PRD:459）—— 3-5 里没有免疫行动，是不是应为「重复 3-7」？另：**重复几轮**（「直到剩余最后一个 T 细胞」意味着轮数由免疫细胞个数决定） | **按「重复 3-7」实现**，请 hxr 确认。**注意这条不只是文字**：3-5 与 3-7 都含第 4 步「点击结束回合」（PRD:445）⇒ 第七关必然是**多个世界回合、多次 E 阶段**，§2.3 的胜负论证与 S10 的验收都按这个写。轮数建议 **2~3 轮**（世界回合数 ≤ 5，保住 I 期，Q-16） | PRD:445/459 |
| **Q-11** | 第七关玩家【黏液破裂】自毁后复活，引擎给 2.0 能量（`REVIVE_ENERGY := 20`，`cw_data.gd:368`）并把那格固化组织降级为癌组织（`cw_world.gd:169-215`）—— 与 PRD:431「能量保持为 Null」冲突 | 复活那一步**紧跟一份重装 world**：能量拨回大数、固化格按演出需要写回 `solid`。数据格式里已经留好（`worlds.revived`） | PRD:431/495 |
| **Q-12** | 装载器上提到 `scripts/kernel/cw_world_loader.gd`（规格 `docs/口径二_测试迁移规格.md:133` / `:258` 那两句路径跟着改）、`RollTape` 上提、新家**不加 `class_name`**（preload 取）—— 都同意吗？`contract_tune.json` 到 S8 才搬、GD + C# 一次提交，可以吗？ | 推荐全同意。判据：`export_presets.cfg` 四个预设全部 `exclude_filter="tests/*"`（`:11/56/127/155`），不搬就是导出包里加载失败；先例：`cw_semkey.gd:12-13`（上提 + 测试侧委托 + 不许出现第三份） | `export_presets.cfg`；`cw_semkey.gd:12-13` |
| **Q-13** | 全程没有提到卡牌 /【基因表达】。教程里**卡牌系统是整个关掉吗**？（决定 `ui_layers` 清单与盘面 `hand` 段）另：第二关 Step2 癌细胞 1 能量 + 一次成功 1.0 伤害 = 一击必杀，而文案写「攻击癌细胞直到其死亡」（PRD:203），是有意的吗？ | 卡牌**整个关掉**（`ui_layers.hand = false`，盘面 `hand: []`）；「直到其死亡」建议改成「击杀它」，免得玩家以为要打好几次 | PRD 全文；PRD:193/203 |
| **Q-14** | 常驻目录按钮（PRD:43）里**未通关的关怎么显示？能不能直接跳？** | 未通关**灰显不可点**（与图鉴同一条口径）；后端 `CWGuide.goto_chapter` 已经在（`guide.gd:273`），做不做「跳关」只是前端一个开关 | PRD:43 |
| **Q-15** | 第七关第 18 步 T 细胞「释放细胞毒素」（PRD:485）走**真技能**还是**纯演出**？（真技能会造坏死格，`NECROSIS_TOXIN := 2`，`cw_data.gd:465`，影响后面每一份重装数据）另：【黏液破裂】随机转化最多 10 格（`cw_actions.gd:1462` 的 `pick_random`）要不要钉带子？（决定复活点与结局画面） | 两条都**走真技能 + 钉带子**（结局画面要可预期，且带子是现成机制）；若 hxr 只要画面效果，改纯演出更省，但要一起说清后面那几份重装盘面照哪一版写 | PRD:485/491 |
| **Q-16** | 第七关「上方不显示第 X 回合」（PRD:421）是**只隐藏**还是**不许推进**？推进会改 `tumor_stage`（= `CWCardData.cancer_phase(round_no)`，`cw_game.gd:619-620`），进而改增生 / 侵蚀 / 固化旋钮的**分档下标** | **只隐藏，照常推进**（PRD:445 要真的点结束回合、PRD:449 要真结算 E 阶段、PRD:459 还要重复若干轮）。**留够余量**：I 期 = 第 1~5 回合（`cw_card_data.gd:182-184`）⇒ 数据里 `round: 1` 起、世界回合数 ≤ 5 就停在 I 期，分档下标不漂；这条写进 S10 验收（⑧） | PRD:421/449/459 |
| **Q-18** | **每关坐几席？** 第五关 Step2 要「各个种类免疫细胞各有一个」（PRD:367）—— 免疫有 5 种（`cw_case_loader.gd:939-945`），加玩家 + 若干癌细胞 ⇒ **8~12 席**；第七关「围一圈免疫 + T + B」同量级。后果有三：① **按人数分档的门槛跟着变** —— `level_min_memory(order.size())` 表里只有 4 人一档，其余**一律回落六人档**（III 级 30 而不是 20，`cw_data.gd:260/272/277`）；② 有氧基数 / 无氧系数同理（`cw_data.gd:216/126`）；③ 右栏一行一席（`match_panel.gd:318-330`），10 行排版没人验过 | **两条**：(a) 第五关 Step2「各种类各一个」是否真要 5 席，还是「能看到几种技能就行」（少席位 = 门槛可控、排版稳）；(b) 认下纪律 8「席位数是设计量，门槛逐关标定」。我方默认：**按 PRD 字面做 5 席**，第四关**钉死 4 席**（保住 20 点门槛），其余关的门槛数不写死、从 `seats` 现算 | PRD:367/417；`cw_data.gd:277` |
| **Q-19** | 换 C# sidecar 那天「教程代码零改动」的**C# 侧前置**没登记：`WorldLoader.cs` 与 `TapeRng.cs` 都住在 `CellWar.Core.Tests`，产品程序集 `CellWar.Core` 里没有对应物 —— 与 GD 侧「装载器住 tests/、导出包排除 tests/*」同性质 | 认下这条前置：口径一批 1 之后把这两件上提到 `CellWar.Core`。**不影响本方案排期**（GD 侧 S0 已经把自己那半做了） | `core/CellWar.Core.Tests/L0/WorldLoader.cs`；`L1/TapeRng.cs` |
| **Q-17** | **PRD 里没有「第六关」**：第二章只有第四关（PRD:287）与第五关（PRD:329），间章之后直接跳第七关（PRD:415）。是编号有意跳过，还是漏了一关？另：通用规则 11「生成的免疫/癌细胞如特殊说明均为 npc，无 ai 控制等」（PRD:55）是不是漏了个「无」字（应为「如**无**特殊说明」）？另：PRD 写「粘液破裂」（PRD:491），引擎与玩法 PRD 正本写「黏液破裂」（`cw_actions.gd:1442`），统一用哪个字？另：自动重置条件只有第三关 Step1 写了（PRD:251），其余关（尤其第七关强制演出）有没有？ | 四条都请 hxr 一句话定。我方默认：第六关**是有意跳号**（按现有 **6 关**做：一 / 二 / 三 / 四 / 五 / 七）；规则 11 **补「无」字**；统一写**「黏液破裂」**；其余关**无自动重置**（第七关靠 `allow` 白名单本来就走不歪） | PRD:55/287/329/415/491；PRD:47/251 |

---

## 附 A · 特殊格与「教学带」（逐关坐标提案，等 Q-02 圈定）

**硬事实**：11 个特殊格（`cw_data.gd:529-534`）的 `r` 只取 `-3 / 0 / 3 / 6` 四个值 ——
核心 `(0,-3)` `(3,0)` `(-3,3)`；骨髓 `(3,-3)` `(0,3)` `(-3,0)` `(6,-3)` `(-3,6)` `(-3,-3)`；血管 `(6,0)` `(-6,0)`。
⇒ **`r = -1` 与 `r = -2` 两整排零特殊格**，整章不用写一个 `"type"`。
排长度 = `13 − |r|`（由 `is_on_board`，`cw_data.gd:876-878`）⇒ `r = -1` 排 12 格（q ∈ [-5, 6]），`r = -2` 排 11 格（q ∈ [-4, 6]）。

| 关 | PRD | 活跃格提案 | 说明 |
|---|---|---|---|
| 第一关 | 93-95 | `(-1,-1) (0,-1)` | 两个横向连接的健康组织；免疫细胞起在 `(-1,-1)` |
| 第二关 Step1 | 143 | 关首活跃集 `(-1,-1)`…`(4,-1)` 六格；`(3,-1) (4,-1)` 为癌 | 2 健康 + 2 癌 = 右侧延伸两格健康两格癌；玩家从 `(0,-1)` 右移**四格**恰好净化两格（PRD:155） |
| 第二关 Step2 | 187-193 | `reveal: ["5,-1"]`（癌组织 + 1.0 能量癌细胞**开局就在盘上、先在遮罩外**） | **零重装**：玩家在 `(4,-1)`，迁移进 `(5,-1)` = 攻击。Step1 净化过的两格原样留着 |
| 第三关 | 227-229 | `r = -1` 往右铺满到 `(6,-1)`，癌组织凸块用 `r = -2` 的两三格做「凸」 | 「凸」= 不在一条直线上 ⇒ 必须借 `r = -2`（同样零特殊格）。**路径必须全程健康组织**，否则 PRD:243 的能量公式不成立（踩癌格是 1.0 不是 0.5，`cw_data.gd:181/190`）。Step1 → Step2 **不换盘**（整关一个能量预算）→ 已并入 Q-02 |
| 第四关 | 291 | 自免疫细胞向四周扩到半径 2~3 的一片 | 会压到核心 `(0,-3)`（与 `(0,-1)` 距离 2）⇒ **那格必须显式写 `"type": "normal"`**，否则白送一个收入格。**席位钉死 4**（保住 III 级 = 20 点，Q-18） |
| 第五关 Step2 | 361-367 | 在第四关基础上扩大癌块 + 加固化格 + 每种免疫各一只（各占一席） | 固化格写 **`state: "solid"`**（纪律 9）—— `tiles[].solid` 是**固化计数**，写错了圆环测试抓不到。这一段是全案仅有的两处关内 `load` 之一（§1.4） |
| 第七关 | 461/467-481 | 玩家癌细胞起在 `(-3,-1)`、T 细胞 `(6,-1)`（起点距离 **9**，一条直线，零特殊格）；被围的免疫细胞放内圈；复活用的固化格放在免疫够不到的一格 | 两轮「前进 1 + 击退 2」后玩家落 `(-5,-1)`、距离 11 = 5×2+1 ⇒ 两次转移 `(0,-1)` → `(5,-1)` 邻接。**别用 `(-5,-1)` 当起点**：击退会落到盘外的 `(-6,-1)`。见 Q-07 |

## 附 B · 老测试逐条去向（纪律：一条不删）

| 测试 | 行 | 去向 | 落在哪一片 |
|---|---|---|---|
| `t_board_small` | 7794 | **原样**（`set_active_radius` 保留成薄壳） | S1 |
| `t_tutorial`（`:10679-10682` / `:10683` / `:10686` 三条） | 10651 | **改判**（盘面 / 半径 API / `main.gd` 源码串）—— **整体在 S3**，不再拆给 S1 | S3 |
| `t_guide_watch` | 10073 | **原样**（纯函数、只读 `CWMirror`；`KEYS` 只扩不改） | S4 |
| `t_guide_quiet` | 10139 | **原样**（`mutes_result` 不动，`guide_bridge.gd:57-64`） | — |
| `t_guide_spotlight` | 11674 | **原样 + 扩表**（`FLAGS` 加 `hex`，判据形状不变） | S4 |
| `t_codex` | 11416 | **扩判据**（每条有 id、id 唯一、未解锁不出现在页面与搜索里） | S6 |
| `t_snapshot`（半径跟存档） | 12375-12385 | **原样**（与教程无关） | — |
| `t_no_engine_in_ui` | 20365 一带（`:20393-20394`） | **改判**：白名单两条 → 一条（check 条数不变） | S3 |
| `t_guide_director` | 10947-11345 | **改判**（断言对象 `CWGuideDirector` / `CWGuideLevels` 整体消失 → 数据版逐关开局；含 `:10957` 的关数互校与 `:10959` 的老半径表） | S3 |
| `t_guide_data` | 10854-10946 | **改判**（`CHAPTER_COUNT` 16 → **6**；`CODEX_PAGE` / `UI_STAGE` / 标题表跟着走；判据形状不变） | S3 |
| `t_guide_no_win` | 9789-9823 | **改判**（`:9792/9803/9810/9811` 调 `assemble` 与 `CWGuideLevels.count/formal` → 换成 `allow` 无结束回合 + E 阶段不产 `game_over`）。**注意：不是「原样」** | S3 |
| `t_tutorial_mechanism_trials` | 1817-1845 | **改判**（`:1819/1826/1834` 调 `assemble(11, 0/1/2)`；PRD 没有机制试炼 → 断言对象换成第七关三条 E 阶段结算，或并入 Q-17） | S3 |
| `t_guide_bridge` | 11556-11673 | **改判**（`:11592-11598` 的 `ui_stage`、`:11599` 的 `assemble(15)`、`:11601` 的 `graduation_assist`） | S3 |
| `t_tutorial` | 10651-10853 | 见本表第二行（**S3 一片改完**，初稿写的「S1 / S3」作废） | S3 |
| `t_tutorial_auto_advance` | 11346 | **改判**（步表换了） | S3 |
| `t_tutorial_pick` | 12978 | **改判**（新第一章不教落子） | S3 |
| `t_tutorial_chapter_swap` | 12256 | **改判**（跨关换局仍走 `_advance_tutorial_chapter`，只是装配入口换成舞台） | S3 |
| `t_entry_smoke_tutorial` | 20600-20633 | **改判**（`:20612` 的 `win_checks`；`:20613` 的三条，见 §1.3 后果表；`board.map.size() == 127` 不变） | S3 |

## 附 C · 八个坑（做之前先读）

1. **新增 `class_name` 要先 `--import`**，否则无头测试认不出来。本方案的新文件**一律不加 `class_name`、用 preload**
   （`guide.gd:60-62` 的先例与理由），从源头避开。
2. **`docs/*.md` 与 `.cs` 的补丁走 python load/save，别用 `sed -i`**（Git Bash 下会把 CRLF 压成 LF，`git status` 看不出来）。
3. **拆局次序钉死**：`abort → queue.stop → close → dispose`（`match.gd:524-534`）。`reload_world` 是这条序列的短路版，
   次序一个字都不能动 —— 先停队列就没人 ack 那条在飞的 roll，5 秒后内核报 barrier timeout，`tools/run_tests.sh` 当场判红。
4. **换局会新建桥 ⇒ 必须重挂同一个 `_guide`**（`match.gd:539-546`）。漏了不崩，但从第 2 关起提示、演示、
   「继续」代做全部静默失效。这是 PR 原样就漏过一次的坑。
5. **演出层的随机绝不能碰内核 rng**：开场跌落的 0~1 秒（PRD:81）、像素错误的抖动都走演出层自己的
   `RandomNumberGenerator`。碰了内核 rng，带子当场错位（`l0_runner.gd:80-82` 的 overrun 会静默回落到真 rng）。
6. **新测试要手工登记进 `_run_all`**：`headless_test.gd:117-165` 是一张**手写的函数名清单**
   （`t_board_small` 就在 `:144`），不是反射扫描；分片按清单下标分（`_assign`，`:59-75`）。
   新增 `t_*` 不登记就**永远不跑、也不报错**。每一片的「新增测试」都要顺手加进这张表。
7. **`step_begin` 在作答之后、不是之前**（`cw_kernel_inproc.gd:397 / 399 / 405`）。装闸一律在 `step_end`。
   连带：`CWGuideBridge.ask()` 要**自己先 `await _await_playback()`** 再读 `_allow` ——
   `CWUIBridge` 的那次等在 `super.ask` 内部（`ui_bridge.gd:199-205 → :236-240`），不先等就读到上一步的闸。
8. **过滤视图与「继续」代做的下标只许映射一次**：`_cur_req` 必须存**过滤后的 view**
   （`guide_bridge.gd:70` 今天存的是原始 req，`take_offer` 在 `:97-105` 直接 `p.fire(idx)`）。
   存错了就是「点继续选中了别的选项」或数组越界，而且**不崩**——静默错到底，正是最难查的那一类。

## 附 D · 缺席阵营怎么写（两条都留，真机各验一次）

**只有第一关**真的没有癌细胞（PRD:101-137）—— 第二关的癌细胞从关首就在盘上，只是 Step1 期间被遮罩挡着（§1.1）。
第一关的癌席两条合法写法，S3 真机各验一次后择一定稿：

- **A（默认）**：`players` 里照样写一个癌席、**但不给它细胞** —— `cell_id` 落成 -1，装载器允许
  （`cw_case_loader.gd:303-308`）。那一席永远轮不到（第一关不结束回合，§2.3）。
- **B（退路）**：给它一只 `alive:false` 的死细胞，占一个**遮罩外**的格 —— `cells_at()` 过滤 `alive`
  （`cw_game.gd:467-472`），死细胞既不占格也不进任何合法性判定；但装载器的「一格一细胞」检查
  **连死细胞一起数**（`:274-281`），所以它得单独占一格，放在活跃集之外玩家看不见也点不到（`hex_at` 只扫活跃集）。
  今天导演用的是板外哨兵 `(9999,9999)`（`guide_director.gd:87-93`），而装载器不收板外格（`cw_case_loader.gd:175`），所以必须换成板内遮罩外的格。

**别写成「只有一个免疫席位的局」**：两阵营的席位表形状一变，`FACTION_ORDER`、收入、UI 侧到处都要验（→ 已并入 Q-17 的默认口径）。
癌方每个 S 阶段的「无法复活」气泡今天已经被静掉（`guide_bridge.gd:57-64`），两条写法都不会弹。

---

**第四章 Game 待 PRD 补齐后另起切片。** 本方案的数据格式（章 / 关 / 步 + `worlds` + `tuning` + `rolls` + `active_tiles`）
不为它预留任何字段，也不需要 —— 到时候加几份 JSON 即可。

## 落地进度

- **S0 ✅ 2026-09-19**：装载器 → `scripts/kernel/cw_world_loader.gd`、带子 → `scripts/kernel/cw_roll_tape.gd`、旧名薄委托、C# `KeyTableTests` 路径同改、新测试 `t_kernel_loader_moved`（开发日志同日条）。
- **S1 ✅ 2026-09-19**：`board.gd` 的活跃格口径从半径换成集合 —— `_active_set` / `set_active_tiles` / `is_active`（即时谓词），`set_active_radius` 转调、`hex_at` 只扫集合、新进集合的格按 `ring_delays` 错峰浮现；新测试 `t_board_active_tiles` 9 项，`t_board_small` 原样通过、零改判。`main.gd` / `match.gd` 未动（含 `:1622` 细胞遮罩、`:1062` 活跃集闸），按方案 ③ 随 S3 走（开发日志同日条）。
- **S2 ✅ 2026-09-19**：`cwtut/1` 数据与校验落地 —— `scripts/kernel/cw_tutorial_data.gd`（`load_index` / `load_level` / `resolve` / `validate` 十条判据，只读）+ `game/data/tutorial/`（`index.json` 的 `_doc` 写九条纪律、第一章前两关各一份完整 world）+ 新测试 `t_tutorial_data` 19 项。**两处照现状改口，S3/S4 要回来对一遍**：`watch` 只许写 `CWGuideWatch.KEYS` 里的键，§1.2 样例的 `tile_healthy:3,-1` / `cancer_dead` 先写成 `purified` / `attacked`（校验只查冒号前那一截，S4 扩表后换回）；第一关癌席按附 D **写法 B** 给一只 `alive:false` 的死细胞 —— 写法 A（不给细胞）与 S2 判据③「每席恰好一只」冲突。还没接线（舞台在 S3）。
- **S3 ✅ 2026-09-19**：舞台接线 + 删老导演 / 老关卡表 + 数据门面 + 第一关（原子片）—— 新 `scripts/kernel/cw_tutorial_stage.gd`（`open_level` 返回 **CWKernel**、`reload_world` 的四步短路序列、`dispose`，带子在 `open()` 之前挂）与 `cw_tutorial_npc.gd`（纯函数 + 三级兜底骨架，本片不接席位）；删 `scripts/ui/guide_director.gd` / `guide_levels.gd`（含 `.uid`），结构闸白名单 **两条 → 一条**；`guide_data.gd` 退成读 JSON 的门面（签名全留、`CHAPTER_COUNT` = `index.json` 的关数 = 今天 2、`graduation_assist()` 返回 `{}`、`steps()` 交深拷贝并现取 `{{tune.*}}`）；`match.gd` 按 §2.3 第 5 条逐行改完（`_stage` / `tutorial_active_tiles()` / `seats`+`human_seat` / `queue.on_step` / `:1062` 活跃集闸 / `:1622` 细胞遮罩）、`main.gd:115`、`game/tests/dump_guide.gd`。测试：新 `t_tutorial_stage`（19 项）+ 12 条改判（逐条在测试注释里写「原断言 → 新断言 → 依据」，汇总表在开发日志同日条）。全量 **3748 项绿 / 245 个测试**，`run_l0.sh` 五段绿，闸三过。

  **本片偏离方案的地方**：
  1. **`guide.gd` 动了 4 行**（方案写「一行不改」）。§1.1 说 `graduation_assist()` 返回 `{}` 并称 `guide.gd:367-369` 已挡住 —— 但 `_render()` 里还有第二处**没挡**（`:429-434` 无条件 `assist["suggestion"]`），而 `CHAPTER_COUNT - 1` 现在就是普通的最后一关、天天成立 ⇒ 空表取键，每次翻页报运行时错误、正文贴不出来。处置：那三行外面套一个 `if not assist.is_empty():`（纯崩溃护栏）。**方案正文的 §1.1 去向表该补上这一处。**
  2. **`cw_tutorial_data.gd` 的 `_at` 改名成 `parse_at`**（S2 的文件）：舞台与门面都要解析 `"q,r"`，不想在仓库里留第三份解析。只改名。
  3. **`t_guide_spotlight` 也得改判**（附 B 写的是「原样 + 扩表，S4」）：它有一条反向断言「FLAGS 表里没有剧本不用的键」，新第一章只用 `move` 一个键，不改当场红。按 `CWGuideWatch.KEYS` 那条既定口径（只查「剧本用到的键必须有实现」这一个方向）改成正向 + 「每个键都指到一支真实存在的 `sync` 分支」。
  4. **数据补了 `act` 字段**：`c1_l1` / `c1_l2` 的可操作步写上 `"act": "move" / "purify" / "attack"` —— `guide_bridge.gd:112/131` 的实时提示与代做判定读的就是它（§1.1 去向表里列了 `steps[].act`，S2 的两关没写）。
  5. **`t_guide_director` 的 check 数 73 → 28**：降的 45 条全是第 3 ~ 16 关的 fixture 断言，那些关在新 PRD 里不存在。新的逐关循环按 `index.json` 走，S5 / S8 / S10 每补一关自动多 10 条。半径接缝 7 条、正式隔离与 RNG 隔离 4 条、L1 推进冒烟 3 条**原样保留**。
  6. **新脏数据源**：两关免疫起点不同格 ⇒ 跨关换局时 `watch: "moved"` 当场成立并写进度（`user://guide_progress.cfg`）。三个会换局的测试收尾各清一次、`t_tutorial` 开头自己先清。S4 在 `step_end` 装闸时要处置「换局那一瞬间的 `_watch_base`」。

- **S4 ✅ 2026-09-19**：常驻壳 + 决策闸 + `ui_layers` / `reveal` 落地 —— 新 `scripts/ui/guide_shell.gd`（`CWGuideShell`：章节全屏提示只在 `chapter` 变时弹、真·全屏 `STOP` 遮挡层、常驻「重置 / 目录」排在遮挡层之上、目录未通关灰显不可点、慢闪参数取 `CWGuide` 那三个常数）与 `scripts/ui/guide_layers.gd`（`CWGuideLayers`：八层白名单 + 增量覆写 + `energy_text()` 一条路喂三个渲染点）；`guide_bridge.gd` 的 `ask()` 重写成「等演出 → 过闸 → 交界面」，三态 + 前缀匹配 + **下标只映射一次**（`_cur_req` 存 view）+ 全落空 warning 并挂起 + `abort()` 多发一次 `allow_changed`；`match.gd` 新 `_apply_guide_step()`（两个调用点、同一个幂等函数：`step_end` 与 `CWGuide.on_step_changed`）、`_reset_tutorial_level()`（重置与 `reset_when` 共用）、`_sync_guide_shell()`；`board.gd` 补 `active_tiles()`；`guide.gd` 的 `plain()` / `reset_to_step0()` / `rebase_watch()` / `ACT_ZONE`。新测试 `t_tutorial_shell` 37 项 + `t_tutorial` 三条改判。全量 **3785 项绿 / 246 个测试**，`run_l0.sh` 五段绿，闸三过。

  **本片偏离方案的地方**：
  1. **§1.12 的排版被 Kevin 09-19 的拍板覆盖：「操作放屏幕下方」**。说明（眉行 / 标题 / 正文）留在 `CWGuide.ZONE`，行动提示 + 代做尾巴 + 三个按钮整组挪进新的 `CWGuide.ACT_ZONE = Rect2(8, 356, 512, 108)`（子容器 `_act`）。下界 464 是算出来的：目标选择态的行动栏 `CWActionBar.PROMPT_RECT` 横跨 x 12..685 / y 466..518，Kevin 给的参考带 y 420~535 会和它叠字，所以把下界收到它之上。⚠ 手牌抽屉抬起时上沿 y=428 仍会和尾巴 / 按钮叠 —— 第一章 `hand = false`，等 S8 开手牌的关再定让位。
  2. **§1.6 的「显示 ∞」改成「无限」**：缝合像素 10px 的 25070 个字形里没有 U+221E（实测），字形覆盖闸 `t_font_coverage` 会拦。`CWGuideLayers.INFINITE_MARK` 一处可改，等 Kevin / hxr 拍换字库还是补字形。
  3. **③ S4 里的 `guide_spotlight.gd`（`FLAGS` 加 `hex` + 一支 `sync` 分支）与 `guide_watch.gd`（`KEYS` 加条目）没做**：`hex` 今天和 `flag` 并存，要让剧本直接给坐标集提亮得多穿一条线，留给 S5 与第一章其余两关一起做；`reset_when` 本片只做「数据读入 + `CWGuideWatch` 现有键能表达的」，其余键 S5 扩表（`cw_tutorial_data` 的校验早就拦着了）。
  4. **两个新 UI 文件带了 `class_name`**（附 C 第 1 条写的是「一律不加」）：`CWGuideLayers` 要被三个互不认识的渲染点直接调，`CWGuideShell` 要被 `screenshot.gd` 的 `call:类名:方法` 驱动（合成的鼠标点击到不了 `Control`）。同 `guide.gd` / `guide_spotlight.gd` 的先例；代价是走不了热更。
  5. **S3 留下的三条小尾巴一起收了**：`subtitle` 补进 `LEVEL_KEYS` 与两关数据（`chapter_subtitles()` 读它、没写回落章名）；`_guide_key` 补一支 `purify`；跨关换局的脏基线由 `CWGuide.rebase_watch()` 在 `step_end` 与「新镜像刚落地」两处各取一次。

- **S5 ✅ 2026-09-19**：第一章其余两关落完 —— **第二关 S3 就在，本片补第三关 ATP**（新 `game/data/tutorial/levels/c1_l3.json`，纯数据）+ `index.json` 加一行。盘面按附 A 的提案（Q-02 仍未答）：免疫起 `(0,-1)`、`r = -1` 排铺到 `(6,-1)`、癌块 `(4,-1)(5,-1)(6,-1)` + `r = -2` 的 `(5,-2)` 做「凸」，3.0 能量的癌细胞站在**最靠近玩家的那一格** `(4,-1)`（否则「最少能量」那条路要踩癌组织，PRD:243 的算式当场不成立）；能量 `51 = 5×3 + 10×3 + 5 + 1` 逐项对得上，`rolls: [[1,6,3],[1,6,1],[1,6,6]]` = 成功 / 失效 / 大成功，伤害 1.0+0+2.0 = 3.0 **刚好**打死。配套三件代码：`CWGuideWatch.KEYS` 加 **两条状态谓词** `beside`（站到敌方细胞相邻格）与 `stuck`（能量不足以移动 —— 判法是「正问着这一席的行动问里一条 `act=move` 都没有」，付不起的迁移引擎已在 `can_pay` 那行滤掉）；`CWGuideSpotlight.FLAGS` 加 `hex` + 一支 `sync` 分支（`sync(flag, m, script_hexes)`，`CWGuide.highlight_hexes()` 从 `steps[].hex` 现取，**与 flag 并存**）；第一章三关 `ui_layers.energy_display` 一律 `"infinite"`（Kevin 09-19 拍板）。新测试 `t_tutorial_c1` 29 项（六条判据逐条）+ 三条改判。全量 **3841 项绿 / 247 个测试**，`run_l0.sh` 五段绿，闸三 `total_sites` 3400 → 3423（`--write` 抬一次：涨的全在 `guide` 档，core 分子分母不动）。

  **改判表**：`t_tutorial_data` 的 `rows.size() == 2` → `3`、`n_worlds == 2` → `3`（依据：S5 补第三关）；`t_tutorial_shell` 的「重置之后 `energy_mode() == "plain"`」→ `"infinite"`（依据：Kevin 09-19 的能量显示拍板）；`t_guide_watch` 的逐键护栏表 `moves` 十条 → 十二条（依据：那条护栏要求 `KEYS` 每个键都有一行样例，加键就得加行 —— 判据本身没动）。老 check 一条没删；`t_guide_director` / `t_guide_data` / `t_guide_bridge` / `t_guide_no_win` / `t_guide_spotlight` 是数据驱动的，一个字没改、各自多出几条。

  **本片偏离方案的地方**：
  1. **`KEYS` 加的是两条不是一条**（S4 回传与本片任务书都只点了 `reset_when` 要的那一条）。第三关 Step1「迁移到癌细胞相邻格」在现有表里一条都表达不了：`moved` 第一步就成立、`purified` 走抗原记忆、`attacked` 是下一步的事。备选是「把 Step1 拆成三步、每步 `watch: moved`」，但玩家走歪时会把「继续攻击癌细胞」提前贴出来，而这一关的全部教学量就在「自己算最省的那条路」。
  2. **PRD:251 的第二条自动重置条件「移动到癌细胞相邻格所剩的能量小于预期」没做**（任务书只点了第一条）。后果真实存在：Step1 绕路后带着不足 3.5 能量站到相邻格，Step2 打不完且不会自动重置，出路只剩常驻「重置」按钮。要做得再加一条**带参数**的判据 —— `cw_tutorial_data` 的 `键:参数` 校验文法早就支持，`CWGuideWatch.done()` 还没解析参数。等拍。
  3. **第一章三关的 `ui_stage` 仍是 0 ⇒ PRD:137/221 的「地图上目的格子闪烁」真机上看不见**。提亮闸是 `CWMatch` 的 `ui_stage() >= 1`，而 `t_guide_bridge` 钉着「第一阶段不提前开放辅助层（2026-09-12 提到 1 档当晚被 Kevin 回滚）」。本片只把 `hex` 那条线补通，**没动 `ui_stage`** —— 要开得 Kevin 再拍一次。第三关 PRD 本就没有「UI 提示」那一段，不受影响。
  4. **第三关剧本切成四步**（PRD 的 Step1/Step2 与面板的「步」不是一回事）：Step1 一步（`beside` + `reset_when: stuck`）；Step2 三步，前两步文案逐字相同 —— PRD:275 的「玩家前两次攻击」要等**两次**，而 `attacked` 一次就成立，只能拆两步（屏幕上看不出接缝），第三步才贴「Oops! 攻击失效…」。
  5. **`t_font_coverage` 扫不到关卡剧本**：它只扫 `res://scripts/**/*.gd` 的字符串字面量，`game/data/tutorial/*.json` 里的台词一个字都没过字形闸（剧本正本搬进 JSON 之后留下的洞；S4 的 ∞ 正是被这道闸拦下的）。本片文案没踩雷，建议单开一小片把 JSON 也扫进去。

- **S7 ✅ 2026-09-19**：开场动画（PRD:59-87）落地，**与 S5 / S6 并行、与对局完全解耦** —— 新 `game/scenes/tutorial_opening.tscn` + `game/scripts/ui/tutorial_opening.gd`（播放器，**不带 class_name**）+ `game/data/tutorial/cutscenes/opening.json`（分镜正本，`cwcut/1`）。**改**：只有 `main.gd:_begin_tutorial` 的接线（加 5 行、改 1 处），内核一行没动、`match.gd` 一行没动。新测试 `t_tutorial_opening` 29 项。全量 **3870 项绿 / 248 个测试**，`run_l0.sh` 五段绿，闸三 `total_sites` 3423 → 3452（`--write` 抬一次：涨的全在 `guide` 档，core 分子分母不动）。

  **分镜与 PRD 的对账口径**：一条 = PRD 里的一个编号行，`prd` 就是那一行的行号 —— 13 条对 PRD:63/65/67/69/71/73/75/77/79/81/83/85/87，`text` 是那一行的原句（只去掉 markdown 的转义反斜杠）。测试里抄了一份基准表逐条比，加一条减一条改一个字都当场红。PRD 的 4.1/4.2/4.3（:79/81/83）是挂在 4.1（同心圆 :77）身上的三条要求，所以它们与 :77 同刻起演、各自只带自己那一份参数（反向侵蚀的帧长、跌落的随机区间、不跌落的两格）。整段 10.75 秒，每条的 `t` 都落在 1/12 秒的格上（`PIX_FPS`，同 `CWSkillFx`）。

  **三段新演出**：
  1. **文字变细胞（:65）**：首页那行 `IMMUNE VS CANCER` 拆成三个 `Label`（字体 / 字号 / 字距 / 颜色 / 起点逐值抄 `MainMenu.tscn` 的 Sub，位置按**前缀宽度现算**，摆在一起逐像素等于首页那一个 Label），`IMMUNE` / `CANCER` 各自飞向自己那一格、缩小淡出，交接那几帧细胞贴图淡入并在落点炸一小把碎粒（`CWPix.burst`）。
  2. **同心圆净化 + 反向【侵蚀】（:77/79）**：以癌细胞所在格为心的**椭圆**环（棋盘是压扁的六边形网格，横距 36 / 纵距 20 ⇒ squash 同 `board.hex_at`）一格一格往外推；扫到的癌性格**倒着**播美术那两帧侵蚀过场 —— 正向 p33 → p66 是「癌漫过来」，`p66 → p33 → 健康` 就是「癌退回去」，方向取 `CWData.dir_toward(环心, 这一格)`（癌残在背着环心的那一侧）。**没有新素材**：直接用 `CWErosionFx.ART` 那 6 方向 × 2 帧。
  3. **组织跌落（:81）**：环扫过之后 `0~1 秒` 的随机时刻整格下坠（加速）并淡出。随机走**本层自己的 `RandomNumberGenerator`**（附 C 第 5 条）—— 开场连内核都没有，一滴也不许沾；测试里同种子逐格复现、中间搅 64 颗全局随机数也不受影响。跌落用「本层代画一张同贴图的副本 + 棋盘那一格从活跃集里摘掉」实现，只经 `board` 的公开面（`set_active_tiles` / `set_tissue` / `set_tile_tex` / `tile_center`），**`board.gd` 一行没改**。

  **自己的相机**：取景做在 `Stage` 这个 `Node2D` 的 `scale` / `position` 上（那正是相机变换的逆），看点 / 锚点 / zoom 三个参数与 `CWView` 同一套 ⇒「和首页一致」（:63/67）是**结构上成立**的。**不新起 `Camera2D`、更不抢 `Main` 那一台** —— 工程里只有一台相机，抢过来主菜单与对局的机位会跟着一起动。收尾那一拍（:85）从菜单机位（zoom 3.2）几何插值到 4.6，锚点插到屏幕正中，免疫细胞的胞体中心正好落在 (480, 270)。

  **整段是时间的纯函数**：`_apply(t)` 按量化到 1/12 秒的 t 把所有位置 / 透明度算一遍，**不挂任何 Tween**。于是「跳过」= `seek(duration())` 一步定格在末帧，无头测试 = 自己喂时间（10.75 秒的演出在测试里几毫秒走完）。唯一例外是攻击演出 —— **复用对局那支 `CWAttackFx`**（:75 的「触发攻击动画」）：`target_alive:false` ⇒ 癌细胞被打飞并淡出，`entered:false` ⇒ 免疫收势弹回自己那一格，PRD 那一行的三个分句一支演出全有了。

  **接线（:87 不闪一帧对局界面）**：`main.gd:_begin_tutorial` 里 `开场演完 → 装第一关（`CWMatch.start()` 的关首 `_apply_guide_step` 这时就把章节提示立起来了）→ 最后才把幕布淡掉（0.45 秒）`。开场自带全屏幕布 ⇒ 底下的菜单退场、镜头推进、癌组织绽开全被盖着；**开场播过的那一路不再空推 1.55 秒镜头**（`_look(1.0)` 直接到位）。测试里有一条源码次序闸盯着这三步的先后。

  **「看过就不再播」**：写在 `user://guide_progress.cfg` 的 `opening_seen` 键 —— 与 `CWGuideProgress` 同住一份 cfg，但**没有改 `cw_guide_progress.gd`**（S6 正在改那个文件）：两边各自 `ConfigFile.load` + `set_value`，谁也不覆盖谁，测试里正面比过。`clear_seen()` 只清自己那个键（真机截图要反复重看开场）。

  **本片偏离方案 / 要拍的地方**：
  1. **跳过规则是补的**：PRD 从头到尾没写开场能不能跳。本片按常规做成「按任意键 / 点任意处跳过，起步 0.25 秒内不认」（那 0.25 秒同 `main.gd` 的 `SKIP_GRACE_MS`：点「新手引导」的那一下会一路漏到这里来），右下角一行小字「按任意键跳过」。**等 hxr 一句话**：留 / 去、文案、要不要改成「长按跳过」。
  2. **目录里的「重看开场」没做**：PRD 的通用规则 5（:43）只写了「章节-关卡目录」，没有重看开场这一项，本片不擅自加。`clear_seen()` 已经备好，真要加就是 `guide_shell.gd` 的目录面板多一行 —— **等 hxr 拍**。
  3. **盘面坐标是本片定的**（PRD 只写了「棋盘右侧有部分组织为癌组织」这种意识流）：免疫起 `(-1,-1)`、癌细胞站 `(2,-1)`、癌区 = 像素横坐标 ≥ `(1,-1)` 那一列（**按像素切不按轴坐标切**：轴坐标的 q 是斜着走的，切出来不是一条竖界）、行进 `(0,-1) → (1,-1)` 两跳（第二跳踩上癌组织 ⇒ 触发 :73 的【净化】）。**开场机位比首页往右平移 112 棋盘像素**（`board_in.look_dx`，zoom 仍是 3.2）：不挪的话癌细胞贴着屏幕右缘演（x = 895 / 960）；挪过之后攻击收势时两只正好夹着屏幕正中。
  4. **PRD:75 的「弹回原格子」读成「攻击收势回到自己这一格」**（= 对局里攻击动画本来的样子），不是「退回出发点」。于是 :83 的「免疫细胞所在组织和右侧组织」= `(1,-1)` 与 `(2,-1)`，留下来的正是**两个横向连接的健康组织**，与第一关的地图同形（PRD:95 的「与开场动画相对应」）。另一种读法（退回 `(-1,-1)`、留 `(-1,-1)(0,-1)`）也说得通，**等 hxr 一句话**。
  5. **开场的癌种钉死骨肉瘤**：与主菜单首次进教程钉死的对手一致（Kevin 2026-09-05），这样开场里被打飞的那只和第一关遇上的是同一种。PRD 没写。
  6. **大标题只叠三层**（影 / 一圈辉光 / 正），首页是五层：开场里它只出现两秒，叠到第三层看不出差别。
  7. **真机这一轮抓到两个 bug（都已修，开发日志同日条有细节）**：① 末帧上叠着主菜单的 `CELL WAR` 幽灵 ——`menu.dismiss()` 的 1.1 秒原来排在开场之后，正好落在「幕布淡掉」那一段，挪到开场之前；② 右侧癌组织的逐格揭示归一化按的是整张棋盘的横跨，红色要到最后一刻才铺 —— 改按癌区自己的横跨，这一拍 0.75 → 0.5 s。
  8. **`t_font_coverage` 仍扫不到 `opening.json`**（S5 留下的同一个洞）：开场的屏幕文字只有 `CELL WAR` / `IMMUNE VS CANCER`（拉丁）与跳过提示（在 `.gd` 里，过闸），分镜里的 `text` 是**说明字段不上屏**，所以本片不受影响 —— 但那个洞还在。
